hmcts/darts-api

build.gradle
https://tools.hmcts.net/jira/browse/DMP-138
Sonar Exclusions for Darts Api
```
[ ] Yes
[x] No
```
=> dmp-138 : Sonar Exclusion for Darts Api

build.gradle, src/integrationTest/java/uk/gov/hmcts/darts/common/controller/DailyListTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/controller/GetWelcomeTest.java, src/main/java/uk/gov/hmcts/darts/common/entity/Annotation.java, src/main/java/uk/gov/hmcts/darts/common/entity/CachedMedia.java, src/main/java/uk/gov/hmcts/darts/common/entity/Case.java, src/main/java/uk/gov/hmcts/darts/common/entity/Courthouse.java, src/main/java/uk/gov/hmcts/darts/common/entity/DailyList.java, src/main/java/uk/gov/hmcts/darts/common/entity/Event.java, src/main/java/uk/gov/hmcts/darts/common/entity/Hearing.java, src/main/java/uk/gov/hmcts/darts/common/entity/Media.java, src/main/java/uk/gov/hmcts/darts/common/entity/Report.java, src/main/java/uk/gov/hmcts/darts/common/entity/Transcription.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionComment.java, src/main/java/uk/gov/hmcts/darts/common/entity/TransformationLog.java, src/main/java/uk/gov/hmcts/darts/common/entity/TransformationRequest.java, src/main/java/uk/gov/hmcts/darts/notification/dto/CreateNotificationReq.java, src/main/java/uk/gov/hmcts/darts/notification/entity/Notification.java, src/main/java/uk/gov/hmcts/darts/notification/enums/NotificationStatus.java, src/main/java/uk/gov/hmcts/darts/notification/repository/NotificationRepository.java, src/main/java/uk/gov/hmcts/darts/notification/service/NotificationService.java, src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java, src/main/resources/application-dev.yaml, src/main/resources/db/migration/notification_table.sql, src/test/java/uk/gov/hmcts/darts/notification/service/CreateNotificationReqServiceTest.java
https://tools.hmcts.net/jira/browse/DMP-54
Create database table for notifications
```
[ ] Yes
[x] No
```
=> DMP-54 Add Notification table

infrastructure/main.tf
=> DMP-45 Correcting Postgress resource group

src/main/java/uk/gov/hmcts/darts/Application.java, src/main/java/uk/gov/hmcts/darts/audio/config/AudioTransformConfigurationProperties.java, src/main/java/uk/gov/hmcts/darts/audio/model/AudioFileInfo.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioOperationService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-117
Concatenate audio streams in a channel
```
[ ] Yes
[x] No
```
=> DMP-117 Concatenate audio

src/main/java/uk/gov/hmcts/darts/authentication/component/TokenValidator.java, src/main/java/uk/gov/hmcts/darts/authentication/component/impl/TokenValidatorImpl.java, src/main/java/uk/gov/hmcts/darts/authentication/config/AuthenticationConfiguration.java, src/main/java/uk/gov/hmcts/darts/authentication/config/JwksConfiguration.java, src/main/java/uk/gov/hmcts/darts/authentication/model/JwtValidationResult.java, src/main/resources/application-dev.yaml, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/authentication/component/impl/TokenValidatorImplTest.java
This change implements JWT token validation. This is introduced as a standalone component, and will be later integrated into the request flow by [DMP-114](https://tools.hmcts.net/jira/browse/DMP-114), hence no integration/functional tests are included here.
```
[ ] Yes
[x ] No
```
=> DMP-137: Implement JWT validation

build.gradle, src/main/java/uk/gov/hmcts/darts/audio/service/AudioOperationService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/audio/util/AudioUtil.java, src/main/java/uk/gov/hmcts/darts/common/util/CommandRunner.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/audio/util/AudioUtilTest.java, src/test/java/uk/gov/hmcts/darts/common/util/CommandRunnerTest.java
https://tools.hmcts.net/jira/browse/DMP-81
Added a Callable Thread to execute any System command.
```
[ ] Yes
[x] No
```
=> dmp-81 : threadRunner to Execute SystemCommand

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/darts-api/Chart.yaml, charts/darts-api/values.dev.template.yaml, charts/darts-api/values.stg.template.yaml, charts/darts-api/values.yaml, src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java, src/main/resources/application.yaml
- in jenkins
- in the application
Running functional tests using test API Key
```
[ ] Yes
[x] No
```
=> DMP-122 Using Govuk notify API key from vault

src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-65
https://tools.hmcts.net/jira/browse/DMP-66
https://tools.hmcts.net/jira/browse/DMP-87
Transcriber templates added to config.
```
[ ] Yes
[x] No
```
=> DMP-65 DMP-66 DMP-87

README.md, docker-compose-local.yml, src/main/resources/application-local.yaml
=> DMP-141: Added docker-compose-dev.yml to enable local testing.

src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-124
Added Audio request being processed template and added a test
```
[ ] Yes
[ x] No
```
=> DMP-124 Add Audio request being processed template

charts/darts-api/values.stg.template.yaml
=> DMP-177-Postgress-terraform

docker-compose-local.yml
=> Fixing-docker-compose-local: aligning env vars

Dockerfile, src/main/java/uk/gov/hmcts/darts/Application.java, src/main/java/uk/gov/hmcts/darts/audio/config/AudioTransformConfigurationProperties.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioOperationService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-118
* Ensure that all input / output filenames include the full path
* Speed up docker build ffmpeg extract
* Check concatenate / merge / trim commands work with ffmpeg
```
[ ] Yes
[x] No
```
=> DMP-118 Trim audio using ffmpeg

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, build.gradle, charts/darts-api/Chart.yaml, charts/darts-api/values.dev.template.yaml, charts/darts-api/values.yaml, src/main/java/uk/gov/hmcts/darts/Application.java, src/main/resources/application.yaml
enabled application Insights logging
```
[ ] Yes
[x] No
```
=> DMP-160 enable application Insights

src/main/java/uk/gov/hmcts/darts/common/entity/Media.java, src/main/resources/db/migration/media_table.sql
https://tools.hmcts.net/jira/browse/DMP-157
```
[ ] Yes
[x ] No
```
=> DMP-157 create audio metadata table

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, charts/darts-api/Chart.yaml, charts/darts-api/values.dev.template.yaml, charts/darts-api/values.yaml, src/main/java/uk/gov/hmcts/darts/authentication/config/AuthenticationConfiguration.java, src/main/resources/application-dev.yaml, src/main/resources/application-stg.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-149
Added Secrets: AzureAdB2CTenantIdKey, AzureAdB2CClientIdKey, AzureAdB2CClientSecretKey
```
[ ] Yes
[x] No
```
=> DMP-149 Add Azure AD B2C Secrets: AzureAdB2CTenantIdKey, AzureAdB2CClientIdKey, AzureAdB2CClientSecretKey

Dockerfile, Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, build.gradle, charts/darts-api/Chart.yaml, charts/darts-api/values.dev.template.yaml, charts/darts-api/values.yaml, lib/applicationinsights.json, src/main/java/uk/gov/hmcts/darts/Application.java, src/main/java/uk/gov/hmcts/darts/common/config/OpenAPIConfiguration.java, src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java, src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java, src/main/resources/application-local.yaml, src/main/resources/application.yaml, src/main/resources/applicationinsights.json
https://tools.hmcts.net/jira/browse/DMP-160
```
[ ] Yes
[x] No
```
=> DMP-160 correct application Insights settings

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml, infrastructure/main.tf
Changes to the DB secret names in the key vault.
This is to match the expected values in the Jenkins library that is responsible for running the DB migration.
```
[X] Yes
[ ] No
```
=> DMP-140 Changes to fix DB migration running as part of the pipeline

charts/darts-api/values.stg.template.yaml
- it appears that a postgres pod is not available for staging test deployment
- no postgres
- removing env vars
```
[ ] Yes
[x] No
```
=> DMP-140 Amending stg helm values

Jenkinsfile_CNP, build.gradle
- necessary to clean down db object prior to using flyway
```
[ ] Yes
[x] No
```
=> DMP-140 Flyway clean on stg and prod

build.gradle
Fixing flyway clean
```
[ ] Yes
[x] No
```
=> DMP-140 Setting DB URL for flyway clean

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, README.md, build.gradle, charts/darts-api/Chart.yaml, charts/darts-api/values.yaml, docker-compose-local.yml, src/main/java/uk/gov/hmcts/darts/authentication/config/AuthenticationConfiguration.java, src/main/resources/application-local.yaml, src/main/resources/application.yaml
- [] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/DMP-232
The environment variables were never set into Docker which is causing issue while testing the application.
Also, the Azure AD environment variable names were wrong.
```
[ ] Yes
[x] No
```
=> dmp-232 : Environment variable issues

src/functionalTest/java/uk/gov/hmcts/darts/authentication/AuthenticationFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/HandleOAuthCodeIntTest.java, src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserController.java, src/main/java/uk/gov/hmcts/darts/authentication/service/AuthenticationService.java, src/main/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/config/security/SecurityConfig.java, src/main/resources/application-dev.yaml, src/main/resources/application-local.yaml, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserControllerTest.java, src/test/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-438
Added Token Filter in Security Config to check if Authorization Headers exist
```
[ ] Yes
[x] No
```
=> dmp-438 : Add Token Filter in Security Config

build.gradle, src/main/java/uk/gov/hmcts/darts/audit/controller/AuditController.java, src/main/resources/openapi/audit.yaml
https://tools.hmcts.net/jira/browse/DMP-198
This pull request is just for the swagger spec and an empty controller.
The bulk of the implementation and tests will be covered in DMP-197.
=> Dmp 198.audit search endpoint

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml, docker-compose-local.yml, src/main/java/uk/gov/hmcts/darts/common/config/SchedLockConfig.java, src/main/resources/application-dev.yaml, src/main/resources/application-h2db.yaml, src/main/resources/application-local.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-123
DMP-123 enforce schema on all parts of application.
Hibernate, flyway, and schedlock.
=> DMP-123 enforce schema on all parts of application.

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, build.gradle
fix build, give flyway migratePostgresDatabase task a schema
=> fix build, give flyway migratePostgresDatabase task a schema

build.gradle
=> Fix build flyway schema

README.md, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioTransformationService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-524
Method to fetch Audio Blob Data from Data store
```
[ ] Yes
[x] No
```
=> dmp-524 : Data Mananagement Blob Services GetAudioBlobData

config/pmd/ruleset.xml, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/HandleOAuthCodeIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioTransformationService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/entity/HearingMediaEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/HearingMediaRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/MediaRepository.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/authentication/component/impl/SimpleInMemorySessionCacheImplTest.java, src/test/java/uk/gov/hmcts/darts/authentication/component/impl/UriProviderImplTest.java
[DMP-522](https://tools.hmcts.net/jira/browse/DMP-522)
Implement getMediaMetadata service and repository layer.
```
[ ] Yes
[x] No
```
=> DMP-400-AudioTransformationService

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java, src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java
=> Adding response to endpoint

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/handlers/DefaultEventHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/notification/service/NotificationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationPerClassBase.java
Part 2: re-enabling media requests tests
=> Fixing and aligning media request tests, and a few other tidy ups.

build.gradle
This exclusion will be removed shortly.  The test are currently disabled, fix is in progress
=> Temporarily adding exclusion.

build.gradle
=> Setting flyway migration locations in gradle.

src/integrationTest/java/uk/gov/hmcts/darts/common/controller/AuditApiTest.java, src/integrationTest/resources/sql/add-audit-and-activity.sql, src/integrationTest/resources/sql/remove-audit-and-activity.sql, src/main/resources/db/migration/common/V1_7__create_audit_table.sql, src/main/resources/db/migration/common/V1_8__create_audit_activities_table.sql
=> Fixing audit tests

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/service/TransientObjectDirectoryServiceTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioTransformationService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/service/impl/TransientObjectDirectoryServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/DMP-548
Saving processed audio file into outbound data store.
```
[ ] Yes
[x ] No
```
=> DMP-548 Add saveProcessedData

build.gradle, src/main/java/uk/gov/hmcts/darts/audio/model/ViqMetaData.java, src/main/java/uk/gov/hmcts/darts/audio/service/ViqHeaderService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/ViqHeaderServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/ViqHeaderServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-80
Created the VIQ Header Service stub
```
[ ] Yes
[ X] No
```
=> DMP-80 ATS - VIQ header Service

ModernisedDarts.postman_collection.json, build.gradle, src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerSearchGetTest.java, src/main/java/uk/gov/hmcts/darts/cases/CasesConstants.java, src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/java/uk/gov/hmcts/darts/cases/model/GetCasesSearchRequest.java, src/main/java/uk/gov/hmcts/darts/cases/service/CaseService.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/resources/openapi/cases.yaml
Create a stub for the Advanced search for Case.
this will implement part of https://tools.hmcts.net/jira/browse/DMP-461
=> DMP-461 create advanced Case search stub

src/main/resources/db/reference/modernised_darts_schema.sql
=> Modernised DARTS database schema v35

src/main/java/uk/gov/hmcts/darts/common/repository/MediaRepository.java
Convert native query to JPA query
=> Convert native query to JPA query

ModernisedDarts.postman_collection.json
=> updating postman collection with a new folder for CaseHearings

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceProcessAudioRequestGivenBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceProcessAudioRequestTest.java, src/main/java/uk/gov/hmcts/darts/audio/component/OutboundFileProcessor.java, src/main/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImplTest.java
[DMP-402](https://tools.hmcts.net/jira/browse/DMP-402)
Implement audio playback functionality. This largely consists of calling existing lower-level functionality such that the requested audio is:
* concatenated
* merged
* trimmed
* re-encoded
* and stored into outbound storage
```
[ ] Yes
[x] No
```
=> DMP-402: Implement playback operation

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/ViqHeaderServiceTest.java, src/integrationTest/resources/tests/audio/playlist.xml, src/main/java/uk/gov/hmcts/darts/audio/model/PlaylistInfo.java, src/main/java/uk/gov/hmcts/darts/audio/model/xml/Playlist.java, src/main/java/uk/gov/hmcts/darts/audio/model/xml/ViqPlayListItem.java, src/main/java/uk/gov/hmcts/darts/audio/service/ViqHeaderService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/ViqHeaderServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/ViqHeaderServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-586
Created VIQ Header playlist.xml
```
[ ] Yes
[ X] No
```
=> Dmp 586 viq header create playlist xml

src/main/java/uk/gov/hmcts/darts/authorisation/model/Permission.java, src/main/java/uk/gov/hmcts/darts/authorisation/model/Role.java, src/main/java/uk/gov/hmcts/darts/authorisation/model/UserState.java, src/test/java/uk/gov/hmcts/darts/authorisation/model/PermissionTest.java, src/test/java/uk/gov/hmcts/darts/authorisation/model/RoleTest.java, src/test/java/uk/gov/hmcts/darts/authorisation/model/UserStateTest.java
https://tools.hmcts.net/jira/browse/DMP-614
Created authorisation model objects for Role, Permission and UserState
```
[ ] Yes
[ x] No
```
=> DMP-614 Authorisation - Create Models - Roles, Permission & Userstate

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerTest.java, src/integrationTest/resources/tests/cases/CaseControllerTest/casesPostEndpoint/expectedResponseNoHearing.json
=> Fixing test

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerCourtLogsTest.java, src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java, src/main/resources/openapi/events.yaml
Snake-casing query params in line with hmcts standards.  Part of fixing the integration between gateway and api.
=> Snake-casing query params

src/main/resources/db/reference/modernised_darts_schema.sql
modernised-darts-schema-v39
```
[ ] Yes
[ ] No
```
=> modernised-darts-schema-v39

src/main/resources/db/reference/security.sql
security-v12
```
[ ] Yes
[ ] No
```
=> security-v12

src/main/resources/db/reference/security.sql
=> security-v13 from Judith W.

src/main/java/uk/gov/hmcts/darts/common/entity/HearingEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/JudgeEntity.java
actioning review comments from previous PR
=> Update entities to match database scriptv40

src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/ResetPasswordIntTest.java, src/main/java/uk/gov/hmcts/darts/authentication/component/UriProvider.java, src/main/java/uk/gov/hmcts/darts/authentication/component/impl/UriProviderImpl.java, src/main/java/uk/gov/hmcts/darts/authentication/config/AuthenticationConfiguration.java, src/main/java/uk/gov/hmcts/darts/authentication/controller/AuthenticationController.java, src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserController.java, src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserController.java, src/main/java/uk/gov/hmcts/darts/authentication/service/AuthenticationService.java, src/main/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/config/security/SecurityConfig.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/authentication/component/impl/UriProviderImplTest.java, src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserControllerTest.java, src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserControllerTest.java, src/test/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-719
Adding Reset Password flow back again
```
[ ] Yes
[x] No
```
=> dmp-719 : Reset Password Flow

src/main/java/uk/gov/hmcts/darts/authorisation/model/Permission.java, src/main/java/uk/gov/hmcts/darts/authorisation/model/Role.java, src/main/java/uk/gov/hmcts/darts/authorisation/model/UserState.java
https://tools.hmcts.net/jira/browse/DMP-727
Fix the authorisation error on Stg
```
[ ] Yes
[x] No
```
=> dmp-727 : Fix Authorisation error on Stg

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerPostEventsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/InterpreterUsedHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/cases/repository/CaseRepository.java, src/main/java/uk/gov/hmcts/darts/common/service/impl/RetrieveCoreObjectServiceImpl.java
=> Fix event handle case search

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdvancedSearchTest.java, src/integrationTest/resources/tests/cases/CaseControllerSearchGetTest/casesSearchGetEndpoint/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdvancedSearchTest/getWithCaseNumber/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdvancedSearchTest/getWithCourtroom/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdvancedSearchTest/getWithCourtroomJudge/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdvancedSearchTest/getWithDateRangeFrom/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdvancedSearchTest/getWithDateRangeFromTo/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdvancedSearchTest/getWithDateRangeTo/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdvancedSearchTest/getWithEventText/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdvancedSearchTest/getWithJudge/expectedResponse.json, src/main/java/uk/gov/hmcts/darts/cases/mapper/AdvancedSearchResponseMapper.java, src/test/java/uk/gov/hmcts/darts/cases/mapper/AdvancedSearchResponseMapperTest.java, src/test/resources/Tests/cases/AdvancedSearchResponseMapperTest/fourWithTwoSameCase/expectedResponse.json, src/test/resources/Tests/cases/AdvancedSearchResponseMapperTest/one/expectedResponse.json, src/test/resources/Tests/cases/AdvancedSearchResponseMapperTest/twoSameCase/expectedResponse.json
https://tools.hmcts.net/jira/browse/DMP-733
=> Dmp 733.add judges to advanced search result

build.gradle
N/A
- don't always clean
- keeping the option there in case we need it in the future
```
[x] Yes
[ ] No
```
=> No longer clean the database on every deployment

src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java, src/main/java/uk/gov/hmcts/darts/common/config/security/SecurityConfig.java, src/main/java/uk/gov/hmcts/darts/notification/NotificationConstants.java, src/main/java/uk/gov/hmcts/darts/notification/entity/NotificationEntity.java, src/main/java/uk/gov/hmcts/darts/notification/mapper/GovNotifyRequestMapper.java, src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-185
=> DMP-185 - send caseNumbers to govNotify

src/integrationTest/java/uk/gov/hmcts/darts/dailylist/controller/DailyListHousekeepingControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/dailylist/service/DailyListServiceHousekeepingTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DailyListStub.java, src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java, src/main/java/uk/gov/hmcts/darts/dailylist/repository/DailyListRepository.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/DailyListService.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpl.java, src/main/resources/application-local.yaml, src/main/resources/application.yaml, src/main/resources/openapi/dailyList.yaml
https://tools.hmcts.net/jira/browse/DMP-203
=> DMP-203 - add DailyList housekeeping

src/main/java/uk/gov/hmcts/darts/cases/mapper/CasesMapper.java, src/main/resources/openapi/cases.yaml, src/test/java/uk/gov/hmcts/darts/cases/mapper/CasesMapperTest.java, src/test/resources/Tests/cases/CasesMapperTest/testMapToSingleCaseWithReportingRestriction/expectedResponse.json
https://tools.hmcts.net/jira/browse/DMP-780
=> DMP-780 - add reporting restrictions to Get /cases/{caseId}

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml, src/main/java/uk/gov/hmcts/darts/Application.java
=> DMP-107 Keda POC

src/main/resources/application-local.yaml
N/A
Update local dev postgres credentials.
=> Update local postgres credentials

src/integrationTest/java/uk/gov/hmcts/darts/dailylist/service/DailyListServiceHousekeepingTest.java, src/integrationTest/java/uk/gov/hmcts/darts/notification/service/NotificationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AutomatedTaskServiceTest.java, src/main/java/uk/gov/hmcts/darts/common/config/SchedLockConfig.java, src/main/java/uk/gov/hmcts/darts/common/repository/AutomatedTaskRepository.java, src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/DailyListService.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpl.java, src/main/java/uk/gov/hmcts/darts/notification/service/NotificationService.java, src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/task/config/AutomatedTaskConfig.java, src/main/java/uk/gov/hmcts/darts/task/config/TaskSchedulerConfig.java, src/main/java/uk/gov/hmcts/darts/task/exception/AutomatedTaskSetupError.java, src/main/java/uk/gov/hmcts/darts/task/model/TriggerAndAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/AutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/AutomatedTaskName.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/AbstractLockableAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/ProcessDailyListAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/service/AutomatedTaskService.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImpl.java, src/main/java/uk/gov/hmcts/darts/task/status/AutomatedTaskStatus.java, src/main/resources/application.yaml, src/main/resources/db/migration/common/V1_203__insert_automated_task_data.sql, src/test/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-182
Added code to enable automated cron tasks to be configured. Added stub for processing daily lists
```
[ ] Yes
[x ] No
```
=> DMP-182 Create spring scheduler task to process daily lists

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetEventsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/EventTestData.java, src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/java/uk/gov/hmcts/darts/cases/exception/CaseApiError.java, src/main/java/uk/gov/hmcts/darts/cases/mapper/CasesMapper.java, src/main/java/uk/gov/hmcts/darts/cases/service/CaseService.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/entity/EventEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java, src/main/resources/openapi/cases.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/ViqHeaderServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/cases/mapper/CasesMapperTest.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java, src/test/java/uk/gov/hmcts/darts/event/mapper/EventEntityToCourtLogMapperTest.java, src/test/java/uk/gov/hmcts/darts/event/service/impl/CourtLogsServiceImplTest.java, src/test/resources/Tests/cases/CasesMapperTest/testMapToEvents/expectedResponse.json
https://tools.hmcts.net/jira/browse/DMP-761
Added the getEvent endpoint
```
[ ] Yes
[ X] No
```
=> DMP-761 Request Audio - Get Event endpoint

src/integrationTest/java/uk/gov/hmcts/darts/task/service/AutomatedTaskServiceTest.java
https://tools.hmcts.net/jira/browse/DMP-182
Fixed unit test that randomly fails
```
[ ] Yes
[X ] No
```
=> Fixed broken unit tests

src/main/resources/db/reference/security.sql
=> security-v15

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DMP-107
As per title
```
[ ] Yes
[ ] No
```
=> DMP-107 Adding DB connection string into the vault

src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-761
Bug Fixes on dmp-761
```
[ ] Yes
[x] No
```
=> dmp-761 : Bug Fixes for Get Even for Hearing

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml
https://tools.hmcts.net/jira/browse/DMP-107
- required when using the `function` chart
```
[ ] Yes
[x] No
```
=> Adding function chart dependency and Keda chart configuration

charts/darts-api/Chart.yaml
https://tools.hmcts.net/jira/browse/DMP-107
- bug fix for postgres trigger is included in this versionhttps://tools.hmcts.net/jira/browse/DMP-107
```
[ ] Yes
[x] No
```
=> DMP-107 Upgrading function chart to 2.3.6

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, README.md, charts/darts-api/Chart.yaml, charts/darts-api/values.yaml, docker-compose-local.yml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-841
Added Azure AD configuration
```
[ ] Yes
[ X] No
```
=> DMP-841 Add Azure AD configuration in application.yaml & values.yaml

src/main/resources/openapi/event.yaml
https://tools.hmcts.net/jira/browse/DMP-877
=> DMP-877 - update max length to 256.

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerPatchCaseTest.java, src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/java/uk/gov/hmcts/darts/cases/exception/CaseApiError.java, src/main/java/uk/gov/hmcts/darts/cases/service/CaseService.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/cases/validator/PatchCaseRequestValidator.java, src/main/resources/openapi/cases.yaml, src/test/java/uk/gov/hmcts/darts/cases/validator/PatchCaseRequestValidatorTest.java
https://tools.hmcts.net/jira/browse/DMP-459
=> DMP-459 - patch case

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerPreviewIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceGivenBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/FileOperationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/MediaTestData.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioService.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioTransformationService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/service/FileOperationService.java, src/main/java/uk/gov/hmcts/darts/common/service/impl/FileOperationServiceImpl.java, src/main/resources/openapi/audio.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-829
Created preview endpoint
```
[ ] Yes
[x ] No
```
=> DMP-829 Preview Audio Endpoint

src/main/java/uk/gov/hmcts/darts/common/config/security/SecurityConfig.java
https://tools.hmcts.net/jira/browse/DMP-764
Whitelisting internal user endpoints
```
[ ] Yes
[x] No
```
=> dmp-764 : White list internal user endpoint

ModernisedDarts.postman_collection.json, src/functionalTest/java/uk/gov/hmcts/darts/events/CourtlogsFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/events/PostEventsFunctionalTest.java
https://tools.hmcts.net/jira/browse/DMP-813
=> DMP-813 - add functional tests for /events

ModernisedDarts.postman_collection.json, src/functionalTest/java/uk/gov/hmcts/darts/FunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/hearings/HearingsGetEventsFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsGetEventsControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/AudioTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/EventStub.java, src/main/java/uk/gov/hmcts/darts/hearings/controller/HearingsController.java, src/main/java/uk/gov/hmcts/darts/hearings/mapper/GetEventsResponseMapper.java, src/main/java/uk/gov/hmcts/darts/hearings/service/HearingsService.java, src/main/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImpl.java, src/main/resources/openapi/hearings.yaml, src/test/java/uk/gov/hmcts/darts/hearings/mapper/GetEventsResponseMapperTest.java, src/test/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-879
=> DMP-879 - copy hearings/events to hearings endpoint

src/main/java/uk/gov/hmcts/darts/authentication/client/OAuthClient.java, src/main/java/uk/gov/hmcts/darts/authentication/client/impl/OAuthClientImpl.java, src/main/java/uk/gov/hmcts/darts/authentication/component/impl/TokenValidatorImpl.java, src/main/java/uk/gov/hmcts/darts/authentication/config/AuthConfigurationProperties.java, src/main/java/uk/gov/hmcts/darts/authentication/config/external/ExternalAuthConfigurationProperties.java, src/main/java/uk/gov/hmcts/darts/authentication/config/internal/InternalAuthConfigurationProperties.java, src/main/java/uk/gov/hmcts/darts/authentication/dao/impl/AzureDaoImpl.java, src/main/java/uk/gov/hmcts/darts/authentication/model/OAuthProviderRawResponse.java, src/main/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/authentication/component/impl/TokenValidatorImplTest.java, src/test/java/uk/gov/hmcts/darts/authentication/dao/impl/AzureDaoImplTest.java, src/test/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-765
Authentication for Internal User
```
[ ] Yes
[x] No
```
=> dmp-765 : Authentication for Internal user

src/functionalTest/java/uk/gov/hmcts/darts/events/CourtlogsFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/events/PostEventsFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/hearings/HearingsGetEventsFunctionalTest.java
=> temporarily disable functional tests

charts/darts-api/Chart.yaml, charts/darts-api/values.dev.template.yaml, charts/darts-api/values.yaml
https://tools.hmcts.net/jira/browse/DMP-107
- the password is not real
```
[ ] Yes
[x] No
```
=> DMP-107 Using DB connection string from secret

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdvancedSearchTest.java, src/integrationTest/resources/tests/cases/CaseServiceAdvancedSearchTest/getWithDateRangeFrom/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdvancedSearchTest/getWithDateRangeFromToSameDate/expectedResponse.json, src/main/java/uk/gov/hmcts/darts/cases/helper/AdvancedSearchRequestHelper.java
https://tools.hmcts.net/jira/browse/DMP-920
=> DMP-920 - fix advanced search specific date picking up too many records.

src/integrationTest/java/uk/gov/hmcts/darts/dailylist/service/DailyListServiceTest.java, src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1OkJsonAndXml/DailyListRequest.json, src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1OkJsonAndXml/expectedResponse.json, src/main/java/uk/gov/hmcts/darts/dailylist/mapper/DailyListMapper.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpl.java, src/test/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpSaveDailyListTest.java
https://tools.hmcts.net/jira/browse/DMP-905
=> DMP-905 - fix DailyList not saving xml to database.

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioRequestIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerDeleteAudioRequestIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/resources/openapi/audio.yaml
[DMP-143](https://tools.hmcts.net/jira/browse/DMP-143)
DMP-143 BUGFIX POST /audio-requests
- changed BODY param: request_type
- also changed DELETE /audio-requests status to be 204
```
[ ] Yes
[x] No
```
=> DMP-143 BUGFIX POST /audio-requests

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerRequestTranscriptionIntTest.java, src/main/java/uk/gov/hmcts/darts/cases/service/CaseService.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionStatusEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionTypeEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionUrgencyEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionWorkflowEntity.java, src/main/java/uk/gov/hmcts/darts/common/enums/TranscriptionWorkflowStageEnum.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionStatusRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionTypeRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionUrgencyRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionWorkflowRepository.java, src/main/java/uk/gov/hmcts/darts/hearings/service/HearingsService.java, src/main/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/enums/TranscriptionStatusEnum.java, src/main/java/uk/gov/hmcts/darts/transcriptions/enums/TranscriptionTypeEnum.java, src/main/java/uk/gov/hmcts/darts/transcriptions/enums/TranscriptionUrgencyEnum.java, src/main/java/uk/gov/hmcts/darts/transcriptions/exception/TranscriptionError.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionService.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/resources/db/migration/common/V1_212__insert_transcription_urgency_data.sql, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-370
Created endpoint for transcriptions request
```
[ ] Yes
[X ] No
```
=> DMP-370 Request a Transcription endpoint

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DMP-986
Increasing the owasp suppression period to avoid build failure
```
[ ] Yes
[x] No
```
=> DMP-986 Correct until period of owasp suppression

src/integrationTest/java/uk/gov/hmcts/darts/common/controller/DailyListEntityTest.java, src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java, src/main/resources/openapi/dailylist.yaml
=> Removing /dailylists/getCases

src/main/resources/application-stg.yaml, src/main/resources/application.yaml
Added debug logging for staging environment
=> Dmp 172.add debug logging to staging

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioRequestIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java, src/main/java/uk/gov/hmcts/darts/audio/component/AudioResponseMapper.java, src/main/java/uk/gov/hmcts/darts/audio/component/impl/AudioResponseMapperImpl.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/main/resources/openapi/audio.yaml, src/test/java/uk/gov/hmcts/darts/audio/component/impl/AudioResponseMapperImplTest.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-982
Added response object
```
[ ] Yes
[X ] No
```
=> DMP-982 Update AddRequest Endpoint Response

src/main/java/uk/gov/hmcts/darts/common/config/security/SecurityConfig.java, src/main/resources/application.yaml
This is WIP, handing over to @hemantasharma1129 or another developer to complete in my absence.
Happy path ACs have been verified through manual testing, by obtaining both external and internal JWTs and attempting requests against protected endpoints.
Remaining work:
- Unit/integration/functional tests
- Code review
```
[ ] Yes
[x] No
```
=> DMP-946: Add support for multi-tenant JWT token validation

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized, README.md, charts/darts-api/Chart.yaml, charts/darts-api/values.yaml, docker-compose-local.yml
https://tools.hmcts.net/jira/browse/DMP-931
Added external service user details
```
[ ] Yes
[X ] No
```
=> DMP-395 (Dev Only) Configure External Service User details

src/integrationTest/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImplTest.java, src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AbstractUserController.java, src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserController.java, src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserController.java, src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImpl.java, src/main/java/uk/gov/hmcts/darts/authorisation/service/impl/AuthorisationServiceImpl.java, src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserControllerTest.java, src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserControllerTest.java, src/test/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1044
Added logic to extract Internal User Token claims.
```
[ ] Yes
[x] No
```
=> DMP-1044: Internal User Claim extract

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerUpdateLastAccessed.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerUpdateLastAccessedTest.java, src/integrationTest/java/uk/gov/hmcts/darts/authorisation/component/impl/AuthorisationImplTest.java, src/integrationTest/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImplTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/AuthorisationStub.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/audio/exception/AudioRequestsApiError.java, src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/main/java/uk/gov/hmcts/darts/authorisation/component/Authorisation.java, src/main/java/uk/gov/hmcts/darts/authorisation/component/UserIdentity.java, src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/AuthorisationImpl.java, src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImpl.java, src/main/java/uk/gov/hmcts/darts/authorisation/config/AuthorisationAspect.java, src/main/java/uk/gov/hmcts/darts/authorisation/exception/AuthorisationError.java, src/main/resources/openapi/audiorequests.yaml
https://tools.hmcts.net/jira/browse/DMP-1091
Added endpoint to patch media request to update the last accessed date. Also added authentication to only allow this operation is the requesor and signed in user are the same
```
[ ] Yes
[x ] No
```
=> DMP-1091-PatchMediaRequestLastAccessedDate

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1143
Now saves row in hearing_media_ae table
=> Dmp 1143.hearing media link bug

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/AuthorisationStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerRequestTranscriptionIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionApprovedIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/AuthorisationImpl.java, src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImpl.java, src/main/java/uk/gov/hmcts/darts/authorisation/constants/AuthorisationConstants.java, src/main/java/uk/gov/hmcts/darts/common/config/OpenAPIConfiguration.java, src/main/java/uk/gov/hmcts/darts/common/entity/ExternalObjectDirectoryEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionCommentEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionStatusEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionTypeEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionUrgencyEntity.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/enums/TranscriptionStatusEnum.java, src/main/java/uk/gov/hmcts/darts/transcriptions/exception/TranscriptionApiError.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionService.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java
[DMP-374](https://tools.hmcts.net/jira/browse/DMP-374)
Add PATCH /transcriptions/{transcription_id}
```
[ ] Yes
[x] No
```
=> DMP-374 Service to authorise a Transcription - updateTranscription

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioRequestIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1094
- required for testing the notifications on the staging env
```
[ ] Yes
[x] No
```
=> DMP-1094 Adding notification for pending audio request

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioRequestIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audit/controller/mapper/AuditDtoMapper.java, src/main/java/uk/gov/hmcts/darts/audit/enums/AuditActivityEnum.java, src/main/java/uk/gov/hmcts/darts/audit/service/AuditService.java, src/main/java/uk/gov/hmcts/darts/audit/service/AuditServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/entity/AuditEntity.java, src/main/java/uk/gov/hmcts/darts/common/exception/AuditApiError.java, src/main/java/uk/gov/hmcts/darts/common/repository/AuditRepository.java, src/test/java/uk/gov/hmcts/darts/audit/service/AuditServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1067
When a media request is created, create an audit entry for the "Request Audio" activity and the relevant user ID.
=> Dmp 1067.audit request audio

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionRejectedIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/exception/TranscriptionApiError.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/resources/openapi/transcriptions.yaml
[DMP-375](https://tools.hmcts.net/jira/browse/DMP-375)
* Add TRANSCRIPTION_103 api error for updateTranscription Rejected flow - The workflow comment is required for this transcription update
* Update transcriptions OAS to show the client error responses (problems)
```
[ ] Yes
[x] No
```
=> DMP-375 Service to reject a Transcription - updateTranscription

charts/darts-api/values.dev.template.yaml, charts/darts-api/values.stg.template.yaml, src/functionalTest/java/uk/gov/hmcts/darts/FunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/authentication/ExternalAuthenticationFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/events/CourtlogsFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/events/PostEventsFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/hearings/HearingsGetEventsFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/admin/test/TestSupportControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/resources/application-intTest.yaml, src/main/java/uk/gov/hmcts/darts/admin/test/TestSupportController.java
Adding support for functional tests
=> Dmp 955 functional test set up

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionApprovedIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionRejectedIntTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/resources/openapi/transcriptions.yaml
https://tools.hmcts.net/jira/browse/DMP-1128
Added validation to the TranscriptionServiceImpl
```
[ ] Yes
[ x] No
```
=> DMP-1128 Transcription state model restrictions

src/integrationTest/java/uk/gov/hmcts/darts/notification/service/NotificationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionApprovedIntTest.java, src/main/java/uk/gov/hmcts/darts/authorisation/api/AuthorisationApi.java, src/main/java/uk/gov/hmcts/darts/authorisation/api/impl/AuthorisationApiImpl.java, src/main/java/uk/gov/hmcts/darts/authorisation/service/AuthorisationService.java, src/main/java/uk/gov/hmcts/darts/authorisation/service/impl/AuthorisationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/UserAccountRepository.java, src/main/java/uk/gov/hmcts/darts/notification/NotificationConstants.java, src/main/java/uk/gov/hmcts/darts/notification/dto/SaveNotificationToDbRequest.java, src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-850
notify transcription company users when a transcription request has been approved.
=> Dmp 850.notify transcription company

charts/darts-api/values.dev.template.yaml, charts/darts-api/values.stg.template.yaml, src/integrationTest/resources/application-intTest.yaml, src/main/java/uk/gov/hmcts/darts/admin/test/TestSupportController.java, src/main/resources/application.yaml
Moving test support config to environments
```
[ ] Yes
[x] No
```
=> DMP-955: Moving test support config to environments

README.md
Updating readme for functional test data management
```
[ ] Yes
[x] No
```
=> DMP-955: Updating readme for functional test data management

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerRequestTranscriptionIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionApprovedIntTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/enums/TranscriptionTypeEnum.java, src/main/java/uk/gov/hmcts/darts/transcriptions/enums/TranscriptionUrgencyEnum.java, src/main/java/uk/gov/hmcts/darts/transcriptions/exception/TranscriptionApiError.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionService.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/resources/openapi/audio.yaml, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java
[DMP-1186](https://tools.hmcts.net/jira/browse/DMP-1186)
Manual request a Transcription - move to Awaiting Authorisation
* Also Fix swagger tag on addAudioMetaData
```
[ ] Yes
[x] No
```
=> DMP-1186 Manual request a Transcription - move to Awaiting Authorisation

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerRequestTranscriptionIntTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java
[DMP-1070](https://tools.hmcts.net/jira/browse/DMP-1070)
Add audit: Request Transcription
```
[ ] Yes
[x] No
```
=> DMP-1070 Add audit: Request Transcription

ModernisedDarts.postman_collection.json, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java
[DMP-1168](https://tools.hmcts.net/jira/browse/DMP-1168)
Updated Audio Requests swagger / postman
```
[ ] Yes
[x] No
```
=> DMP-1168 Audio Requests swagger / postman

src/main/resources/db/migration/local/afterMigrate.sql
=> remove incorrect sql

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/AuthorisationStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionApprovedIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionRejectedIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionWithTranscriberIntTest.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java
[DMP-378](https://tools.hmcts.net/jira/browse/DMP-378)
Service to accept transcription - updateTranscription
* transcriptionStatus [5 | With Transcriber]
```
[ ] Yes
[X] No
```
=> DMP-378 - Service to accept transcription - updateTranscription

charts/darts-api/Chart.yaml
N/A
Upgrading function chart, fixing KEDA to work with Workload Identity
```
[ ] Yes
[x] No
```
=> Upgrading function chart to v2.4.1

config/owasp/suppressions.xml, config/pmd/test-ruleset.xml, src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseTranscriptsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/TestUtils.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/casesSearchGetEndpointOneObjectReturned.json, src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/casesSearchGetEndpointTwoObjectsReturned.json, src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/java/uk/gov/hmcts/darts/cases/mapper/TranscriptionMapper.java, src/main/java/uk/gov/hmcts/darts/cases/service/CaseService.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/main/resources/openapi/cases.yaml, src/test/java/uk/gov/hmcts/darts/cases/mapper/TranscriptionMapperTest.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java
https://tools.hmcts.net/jira/browse/DMP-738
=> DMP-738 - implement GET /cases/{caseId}/transcripts

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseTranscriptsTest.java, src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/casesSearchGetEndpointOneObjectReturned.json, src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/casesSearchGetEndpointTwoObjectsReturned.json
Fix unit tests so they aren't using todays date
=> fix unit tests

Jenkinsfile_CNP
N/A
To help with debugging, as requested by platops
```
[ ] Yes
[x] No
```
=> Adding disableCleanupOfHelmReleaseOnFailure() to jenkinsfile

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseByIdTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseHearingsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerPatchCaseTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionWithTranscriberIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/authorisation/exception/AuthorisationError.java, src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/resources/openapi/audiorequests.yaml, src/main/resources/openapi/cases.yaml, src/main/resources/openapi/transcriptions.yaml
[DMP-1170](https://tools.hmcts.net/jira/browse/DMP-1170)
Add Authorisation to the Cases API endpoints (403 Forbidden Error)
* GET /cases/{case_id}
* PATCH /cases/{case_id}
* GET /cases/{case_id}/hearings
```
[ ] Yes
[x] No
```
=> DMP-1170 Add Authorisation to the Cases API endpoints (403 Forbidden Error)

config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerAddAudioRequestIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/AuthorisationStub.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/authorisation/annotation/Authorisation.java, src/main/java/uk/gov/hmcts/darts/authorisation/config/AuthorisationAspect.java
[DMP-1171](https://tools.hmcts.net/jira/browse/DMP-1171)
Update AuthorisationAspect to handleRequestBodyAuthorisation
* POST /audio-requests
```
[ ] Yes
[x] No
```
=> DMP-1171 Update AuthorisationAspect to handleRequestBodyAuthorisation

src/functionalTest/java/uk/gov/hmcts/darts/courthouses/CourthousesFunctionalTest.java
[DMP-811](https://tools.hmcts.net/jira/browse/DMP-811)
Update CourthousesFunctionalTest to change test method order for POST / DELETE failing and disabled tests
* Fix pipeline issues seen master/508/console: CourthousesFunctionalTest > createCourthouse() FAILED
```
[ ] Yes
[x] No
```
=> DMP-811 Update CourthousesFunctionalTest to change test method order for POST / DELETE failing and disabled tests

src/main/java/uk/gov/hmcts/darts/usermanagement/SecurityGroupController.java, src/main/java/uk/gov/hmcts/darts/usermanagement/UserController.java, src/main/resources/openapi/usermanagement.yaml
User Management OpenAPI spec per https://tools.hmcts.net/confluence/display/DMP/Admin+Portal+LLD+-+User+Management..
```
[ ] Yes
[x] No
```
=> Add usermanagement OpenAPI spec

ModernisedDarts.postman_collection.json, config/owasp/suppressions.xml
[DMP-1169](https://tools.hmcts.net/jira/browse/DMP-1169)
Update Postman Collection to add /audio/preview/{media_id}
```
[ ] Yes
[x] No
```
=> DMP-1169 Update Postman Collection to add /audio/preview/{media_id}

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriptionTypesTest.java, src/integrationTest/resources/tests/transcriptions/transcription_types/expectedResponse.json, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionService.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java, src/test/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapperTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceGetTranscriptionTypeTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java, src/test/resources/Tests/transcriptions/mapper/TranscriptionTypeResponseMapper/expectedResponseMultipleEntities.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionTypeResponseMapper/expectedResponseSingleEntity.json, src/test/resources/Tests/transcriptions/service/TranscriptionTypeResponseMapper/expectedResponseMultipleEntities.json
https://tools.hmcts.net/jira/browse/DMP-1335
Added endpoint to get transcription types
```
[ ] Yes
[x ] No
```
=> DMP-1335 REST endpoint to get transcription types

src/main/java/uk/gov/hmcts/darts/common/config/BankHolidayCacheConfig.java, src/main/resources/application.yaml
Changing ttl representation from days to minutes
```
[ ] Yes
[x] No
```
=> DMP-666: Changing ttl representation from days to minutes

src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/AudioTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/MediaRequestRepository.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1271
Only count media requests with Completed status
```
[ ] Yes
[x] No
```
=> DMP-1271 Audio requests not accessed count completed

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestNonAccessedCountIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerDeleteAudioRequestIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerGetYourAudioIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerPlaybackIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerUpdateLastAccessedTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/service/TransientObjectDirectoryServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/AudioTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/audio/exception/AudioRequestsApiError.java, src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/main/resources/openapi/audio.yaml, src/main/resources/openapi/audiorequests.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1398
Added endpoint for playback and modified download so it can only be performed on a media request for the action
```
[ ] Yes
[ x] No
```
=> Dmp 1398 new endpoint for playback

src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAttachTranscriptIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/config/AudioConfigurationProperties.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/common/entity/ExternalObjectDirectoryEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionDocumentEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java, src/main/java/uk/gov/hmcts/darts/datamanagement/api/DataManagementApi.java, src/main/java/uk/gov/hmcts/darts/datamanagement/api/impl/DataManagementApiImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/config/TranscriptionConfiguration.java, src/main/java/uk/gov/hmcts/darts/transcriptions/config/TranscriptionConfigurationProperties.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/exception/TranscriptionApiError.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionService.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/validator/TranscriptFileValidator.java, src/main/resources/application.yaml, src/main/resources/db/migration/common/V1_228__update_external_object_directory_schema.sql, src/main/resources/openapi/transcriptions.yaml
[DMP-381](https://tools.hmcts.net/jira/browse/DMP-381)
* attachTranscript: POST /transcriptions/{transcription_id}/document
```
[ ] Yes
[x] No
```
=> DMP-381 Service to attach a transcription - attachTranscript

charts/darts-api/values.dev.template.yaml, charts/darts-api/values.stg.template.yaml, src/main/java/uk/gov/hmcts/darts/event/service/impl/DarNotifyServiceImpl.java
Fixing connectivity to darts gateway
```
[ ] Yes
[N] No
```
=> DMP-398: Fixing connectivity to darts gateway

README.md, bin/dbuild, bin/dcup, docker-compose-local.yml
Added the gateway and stub to docker compose.  Also added convenience scripts for bring up docker compose with the additional services.
```
[ ] Yes
[ ] No
```
=> DMP-938: added darts-gateway and stub to docker compose

bin/dbuild, bin/dcup
Fixes to docker compose script
```
[ ] Yes
[x] No
```
=> DMP-938: Fixes to docker compose script

src/integrationTest/java/uk/gov/hmcts/darts/authorisation/service/AuthorisationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/main/java/uk/gov/hmcts/darts/common/entity/SecurityGroupEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/SecurityRoleEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/UserAccountEntity.java, src/main/resources/db/migration/common/V1_232__security_tables_add_columns.sql
Adding columns to security_group, security_role & user_ tables
```
[ ] Yes
[x] No
```
=> DMP-1451: Adding columns to security_group, security_role & user_ tables

ModernisedDarts.postman_collection.json
[DMP-410](https://tools.hmcts.net/jira/browse/DMP-410)
[DMP-381](https://tools.hmcts.net/jira/browse/DMP-381)
[DMP-1336](https://tools.hmcts.net/jira/browse/DMP-1336)
[DMP-1335](https://tools.hmcts.net/jira/browse/DMP-1335)
POST /transcriptions/{transcription_id}/document - Transcribers can upload a transcription document (Attach file and complete)
GET /transcriptions/{transcription_id}/document - Download transcript file
GET /transcriptions/urgencies - Gets a list of the transcription urgency values
GET /transcriptions/types - Gets a list of the transcription types
```
[ ] Yes
[x] No
```
=> Updated Postman collection: transcriptions

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerPreview2IntTest.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java
N/A
As per title.
```
[ ] Yes
[x] No
```
=> Returning HTTP 206 partial content

src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java
N/A
Trying with non-audio header to see if that's causing some issues.
```
[ ] Yes
[x] No
```
=> Amending audio/preview2 to use different headers

src/main/resources/openapi/usermanagement.yaml
Update usermanagement openapi to align with LLD https://tools.hmcts.net/confluence/display/DMP/Admin+Portal+LLD+-+User+Management.
```
[ ] Yes
[x] No
```
=> Update usermanagement openapi to align with LLD

ModernisedDarts.postman_collection.json
n/a
Added new transcription endpoint to postman
```
[ ] Yes
[X] No
```
=> Added new transcription endpoint to postman

src/main/resources/db/migration/common/V1_233__v53_updates.sql
https://tools.hmcts.net/jira/browse/DMP-1409
fix for script
```
[ ] Yes
[x] No
```
=> DMP 1409 fix script

src/main/java/uk/gov/hmcts/darts/common/repository/MediaRepository.java
https://tools.hmcts.net/jira/browse/DMP-1538
Sorting findAllByHearingId by start time
```
[ ] Yes
[x] No
```
=> DMP-1538 Audio endpoint sort order

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/TestUtils.java, src/main/java/uk/gov/hmcts/darts/cases/mapper/CasesMapper.java, src/main/resources/openapi/cases.yaml, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/common/util/TestUtils.java
https://tools.hmcts.net/jira/browse/DMP-1548
=> DMP-1548 Supply case_id

src/main/resources/db/migration/common/V1_234__v54_updates.sql
https://tools.hmcts.net/jira/browse/DMP-1465
fixed script
```
[ ] Yes
[x] No
```
=> 1465 fix for script

bin/dcdown, src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java
N/A
- get transcriptions for case and hearing - order by createdDateTime
- get events for hearing - order by event timestamp
```
[ ] Yes
[x] No
```
=> Adding default ordering for some endpoints

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerPostEventsTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/EventHandlerRepository.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/EventTypeToHandlerMap.java
https://tools.hmcts.net/jira/browse/DMP-1527
=> DMP-1527 - use default error handle for Type is SubType not found.

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriptionUrgenciesTest.java, src/integrationTest/resources/tests/transcriptions/transcription_urgencies/expectedResponse.json, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionUrgencyEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionUrgencyRepository.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/TranscriptionRequestHandler.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/enums/TranscriptionUrgencyEnum.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionService.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/resources/db/migration/common/V1_235__Update_TransactionUrgency_Table.sql, src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceGetTranscriptionUrgencyTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java, src/test/resources/Tests/transcriptions/mapper/TranscriptionUrgencyResponseMapper/expectedResponseMultipleEntities.json, src/test/resources/Tests/transcriptions/service/TranscriptionUrgencyResponse/expectedResponseMultipleEntities.json
returns only display_state set to true
```
[ ] Yes
[ ] No
```
=> DMP-1420 transcription_urgency display_state added

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/DarStartHandlerTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/DarNotifyServiceImpl.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandler.java
https://tools.hmcts.net/jira/browse/DMP-417
=> DMP-417 - Don't Notify DAR PC if case is closed.

src/main/resources/db/reference/modernised_darts_standing_data.sql
https://tools.hmcts.net/jira/browse/DMP-1420
Adding "Up to " prefix
```
[ ] Yes
[ ] No
```
=> Updating transcription_urgency values in standing data

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerRequestTranscriptionIntTest.java, src/main/java/uk/gov/hmcts/darts/common/exception/DartsApiException.java, src/main/java/uk/gov/hmcts/darts/common/exception/DartsApiTrait.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-762
Adding the conflicting transcription ID to the error response.
```
[ ] Yes
[x] No
```
=> Reporting duplicate transcription id in error detail

src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java, src/main/resources/application.yaml
[DMP-1469](https://tools.hmcts.net/jira/browse/DMP-1469)
Change Gov Notify template for audio being processed
```
[ ] Yes
[x] No
```
=> DMP-1469 Update audio being processed template

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1417
Save filename & fileformat at the end of ATS process
```
[ ] Yes
[X] No
```
=> DMP-1417 Save filename & fileformat at the end of ATS process

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAttachTranscriptIntTest.java, src/main/java/uk/gov/hmcts/darts/common/util/FileContentChecksum.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/test/java/uk/gov/hmcts/darts/common/util/FileContentChecksumTest.java
[DMP-1465](https://tools.hmcts.net/jira/browse/DMP-1465)
BUGFIX not-null constraint violation: transcription_document (checksum)
```
[ ] Yes
[x] No
```
=> DMP-1465 BUGFIX not-null constraint violation: transcription_document (checksum)

src/main/resources/openapi/transcriptions.yaml
N/A
- to include the extra property returning the POST /transcriptions 409 error
```
[ ] Yes
[x] No
```
=> Amending transcriptions openapi spec

src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java
https://tools.hmcts.net/jira/browse/DMP-923
The template has also been updated on GOV.UK notify
```
[ ] Yes
[x] No
```
=> DMP-923 Updating transcription request approved notification template test

src/main/java/uk/gov/hmcts/darts/admin/test/TestSupportController.java, src/main/java/uk/gov/hmcts/darts/audit/service/impl/AuditServiceImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/audit/service/AuditServiceImplTest.java
N/A
- using `CLUSTER_NAME` env var or "not available" as default
```
[ ] Yes
[x] No
```
=> Fixing audit application_server

.idea/codeStyles/Project.xml, src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/notification/helper/TemplateIdHelperTest.java, src/integrationTest/java/uk/gov/hmcts/darts/notification/service/NotificationServiceTest.java, src/main/java/uk/gov/hmcts/darts/notification/NotificationConstants.java, src/main/java/uk/gov/hmcts/darts/notification/helper/GovNotifyRequestHelper.java, src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java, src/main/resources/application.yaml
Update templates to new format with hyperlink
[Update Notify template for "Approver to Approve Transcript Request"](https://tools.hmcts.net/jira/browse/DMP-1472)
[Update Notify template for "Request to transcriber"](https://tools.hmcts.net/jira/browse/DMP-1477)
[Update notify template for "Requested Audio Available"](https://tools.hmcts.net/jira/browse/DMP-1474)
=> DMP-1474, DMP-1477, DMP-1472 - update various templates

src/integrationTest/java/uk/gov/hmcts/darts/notification/service/NotificationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerRequestTranscriptionIntTest.java, src/main/java/uk/gov/hmcts/darts/notification/NotificationConstants.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-795
- adding notification for approvers
- removing `NotificationConstants` in favour of the already used `NotificationTemplate` enum
```
[ ] Yes
[x] No
```
=> DMP-795 Adding notification to approvers on transcription request

ModernisedDarts.postman_collection.json
adding a test script to the postman collection as other devs may find it useful
=> add test script to postman collection

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerGetYourAudioIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-1361
=> DMP-1361 - Change query to use currentOwner instead of requestor

src/main/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityGroupController.java, src/main/resources/openapi/usermanagement.yaml
This change is preparation for development of https://tools.hmcts.net/jira/browse/DMP-1636.
```
[ ] Yes
[x] No
```
=> Add usermanagement POST /security-groups to openapi

src/integrationTest/java/uk/gov/hmcts/darts/notification/service/NotificationServiceTest.java, src/main/java/uk/gov/hmcts/darts/notification/NotificationConstants.java, src/main/java/uk/gov/hmcts/darts/notification/dto/SaveNotificationToDbRequest.java, src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/util/TranscriptionUtil.java
https://tools.hmcts.net/jira/browse/DMP-1644
=> DMP-1644 - fix rejection email not being sent

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/DarStartHandlerTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/DarNotifyServiceImpl.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/DarStartHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/DarStopHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/EventHandlerBase.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/InterpreterUsedHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/SetReportingRestrictionEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/StandardEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/TranscriptionRequestHandler.java
https://tools.hmcts.net/jira/browse/DMP-1531
=> DMP-1654 - Check for court cases using courthouse and case number combo

ModernisedDarts.postman_collection.json
https://tools.hmcts.net/jira/browse/DMP-447  
Added addAudio (/audios) test to the postman collection to assist in testing 
```
[ ] Yes
[ x] No
```
=> DMP-447 added a post /audios to postman collection

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-1660
Attempt to stop Hibernate throwing a Lazy loading exception from trying to schedule the audio request completed notification
```
[ ] Yes
[x ] No
```
=> DMP-1660 Audio request processed hibernate fix

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-1660
Remove tempory logging around audio ready notification
```
[ ] Yes
[ x] No
```
=> DMP-1660 Remove tempory logging around audio ready notification

ModernisedDarts.postman_collection.json
https://tools.hmcts.net/jira/browse/DMP-1296
Added postman collection changes
```
[ ] Yes
[x ] No
```
=> Added postman collection changes

charts/darts-api/values.dev.template.yaml
N/A
As per title
```
[ ] Yes
[X] No
```
=> Setting pod limits for Dev deployments, same as staging

src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/notification/NotificationConstants.java, src/main/resources/application.yaml
(https://tools.hmcts.net/jira/browse/DMP-1473)
The notify template "Error in Processing Audio" has been updated to "Error in Processing Audio v2"  and extra data parameters have been added to the  new notify screen.
Following have been updated:
NotificationConstants.java
NotificationApi.java
AudioTransformationServiceImpl.java
Functional test errorProcessingAudioV2() added to GovNotifyServiceTest.java
application.yaml
```
[ ] Yes
[ x] No
```
=> DMP-1473 Updated notify template - "Error in Processing Audio" fields added

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/UnstructuredAudioDeleterProcessorTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AutomatedTaskServiceTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/UnstructuredAudioDeleterProcessor.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/UnstructuredAudioDeleterProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/task/runner/AutomatedTaskName.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/UnstructuredAudioDeleterAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImpl.java, src/main/resources/application.yaml, src/main/resources/db/migration/common/V1_245__insert_mark_for_deletion.sql, src/main/resources/db/migration/common/V1_246__insert_mark_for_deletion.sql
https://tools.hmcts.net/jira/browse/DMP-599
```
[ ] Yes
[x] No
```
=> dmp 599 add new mark delete task

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/DataManagementServiceImpl.java
add logging to aid investigation into DMP-1666
=> add logging to aid investigation into DMP-1666

src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java
Fix up the notification tests to match latest in Gov Notify
```
[ ] Yes
[ ] No
```
=> Update functional test content for notifications

ModernisedDarts.postman_collection.json, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/darts/noderegistration/NodeRegistrationFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/noderegistration/controller/NodeRegistrationControllerTest.java, src/main/java/uk/gov/hmcts/darts/noderegistration/controller/NodeRegistrationController.java, src/main/resources/openapi/noderegistration.yaml
DMP 705 fix
removed underscore
```
[ ] Yes
[x] No
```
=> DMP 705 fix text case

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CasesControllerGetTranscriptsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsControllerGetTranscriptsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerRequestTranscriptionIntTest.java, src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/casesSearchGetEndpointOneObjectReturned.json, src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/casesSearchGetEndpointTwoObjectsReturned.json, src/integrationTest/resources/tests/transcriptions/transcription_types/expectedResponse.json, src/integrationTest/resources/tests/transcriptions/transcription_urgencies/expectedResponse.json, src/main/java/uk/gov/hmcts/darts/cases/mapper/TranscriptionMapper.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/TranscriptionRequestHandler.java, src/main/java/uk/gov/hmcts/darts/hearings/mapper/TranscriptionMapper.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/resources/openapi/cases.yaml, src/main/resources/openapi/hearings.yaml, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/cases/mapper/TranscriptionMapperTest.java, src/test/java/uk/gov/hmcts/darts/hearings/mapper/TranscriptionMapperTest.java, src/test/resources/Tests/transcriptions/mapper/TranscriptionTypeResponseMapper/expectedResponseMultipleEntities.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionTypeResponseMapper/expectedResponseSingleEntity.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionUrgencyResponseMapper/expectedResponseMultipleEntities.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionUrgencyResponseMapper/expectedResponseSingleEntity.json, src/test/resources/Tests/transcriptions/service/TranscriptionTypeResponse/expectedResponseMultipleEntities.json, src/test/resources/Tests/transcriptions/service/TranscriptionUrgencyResponse/expectedResponseMultipleEntities.json
adding full name for ids in request/response 
main task - https://tools.hmcts.net/jira/browse/DMP-1564
subtask for this pr - https://tools.hmcts.net/jira/browse/DMP-1565
=> DMP-1565: add full ids

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsIntTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/YourTranscriptsQuery.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/YourTranscriptsQueryImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionService.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-1720
- updating the custom query
```
[ ] Yes
[x] No
```
=> DMP-1720 Checking `hide_request_from_requestor` is "Your transcripts" endpoint

src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityGroupFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostSecurityGroupIntTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/SecurityGroupRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/SecurityRoleRepository.java, src/main/java/uk/gov/hmcts/darts/usermanagement/component/validation/Validator.java, src/main/java/uk/gov/hmcts/darts/usermanagement/component/validation/impl/SecurityGroupCreationValidation.java, src/main/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityGroupController.java, src/main/java/uk/gov/hmcts/darts/usermanagement/controller/UserController.java, src/main/java/uk/gov/hmcts/darts/usermanagement/exception/UserManagementError.java, src/main/java/uk/gov/hmcts/darts/usermanagement/mapper/impl/SecurityGroupMapper.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/SecurityGroupService.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/SecurityGroupServiceImpl.java, src/main/resources/openapi/usermanagement.yaml
=> DMP-1636: Implement POST /security-groups

src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorImpl.java
https://tools.hmcts.net/jira/browse/DMP-1768
No new record is inserted in external_object_directory table for Media File and Transcription Document. Cannot say if the validation is passed or failed.
```
[ ] Yes
[X] No
```
=> DMP-1768 Changed loop control to continue

build.gradle
No jira
Upgrade flyway to version 10
```
[ x] Yes
[ ] No
```
=> Upgrade org.flywaydb.flyway 10.x

build.gradle
Attempt to fix the flyway issue after upgrading to version 10.
```
[ ] Yes
[ x] No
```
=> Add flyway postgresql to buildscript

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerRequestTranscriptionIntTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java
https://tools.hmcts.net/jira/browse/DMP-1727
Bug with times
```
[ ] Yes
[x] No
```
=> DMP-1727 written failing test

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/UserManagementFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/authorisation/service/AuthorisationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriberTranscriptsIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriberTranscriptsWithTranscriberStatusOnlyIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriptionTranscriberCountsIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchUserIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostUserIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerSearchIntTest.java, src/main/java/uk/gov/hmcts/darts/common/entity/UserAccountEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/UserAccountRepository.java, src/main/java/uk/gov/hmcts/darts/usermanagement/mapper/impl/UserAccountMapper.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserManagementServiceImpl.java, src/main/resources/db/migration/common/V1_247__use_boolean_to_represent_user_account_activation.sql, src/main/resources/openapi/usermanagement.yaml
Using a boolean to represent whether a user is active
```
[ ] Yes
[x] No
```
=> DMP-1744: Using a boolean to represent whether a user is active

src/main/java/uk/gov/hmcts/darts/cases/helper/AdvancedSearchRequestHelper.java
https://tools.hmcts.net/jira/browse/DMP-1719
Case Search is not returning data for Judge
```
[ ] Yes
[X] No
```
=> DMP-1719 Added global access to security roles criteria

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdvancedSearchTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/main/java/uk/gov/hmcts/darts/cases/helper/AdvancedSearchRequestHelper.java
https://tools.hmcts.net/jira/browse/DMP-1719
Bug for DMP-1033: Case Search is not returning data for Judge
```
[ ] Yes
[X] No
```
=> DMP-1719 Added integration tests

src/main/java/uk/gov/hmcts/darts/audio/service/impl/ViqHeaderServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileZipGeneratorImplTest.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/ViqHeaderServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1666
Fixed hearing events
```
[ ] Yes
[x ] No
```
=> DMP-1666-Fix-HearingEvents

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsGivenBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java
(https://tools.hmcts.net/jira/browse/DMP-1473)
notifyUser unit test testNotifyUserScheduleErrorNotification added
```
[ ] Yes
[x ] No
```
=> Origin/dmp 1473 update notify template  error in processing audio 

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/HearingReportingRestrictionsRepositoryTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/EventStub.java, src/main/java/uk/gov/hmcts/darts/common/entity/HearingReportingRestrictionsEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/HearingReportingRestrictionsRepository.java, src/main/resources/db/migration/common/V1_249__view_reporting_restrictions.sql
https://tools.hmcts.net/jira/browse/DMP-1599
Added view
```
[ ] Yes
[x] No
```
=> DMP-1599 added view, entity and test

src/main/java/uk/gov/hmcts/darts/audit/controller/AuditController.java, src/main/java/uk/gov/hmcts/darts/courthouse/controller/CourthousesController.java, src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DarStartHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DarStopHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DartsEventNullHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/InterpreterUsedHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SetReportingRestrictionEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StandardEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StopAndCloseHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/TranscriptionRequestHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/base/EventHandlerBase.java, src/main/java/uk/gov/hmcts/darts/noderegistration/controller/NodeRegistrationController.java
Creating this PR off the back of this one https://github.com/hmcts/darts-api/pull/782 which was created by Mario on a fork, so the Jenkins build wasn't starting.
=> DMP-1347: replaced field-based injection with constructor-based injection

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerPreviewIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/audio/util/StreamingResponseEntityUtil.java, src/test/java/uk/gov/hmcts/darts/audio/util/StreamingResponseEntityUtilTest.java
https://tools.hmcts.net/jira/browse/DMP-1805
- always respond with 206 when a range header is present
```
[ ] Yes
[x] No
```
=> DMP-1805 Audio preview/playback seek fix

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerSearchIntTest.java, src/main/java/uk/gov/hmcts/darts/usermanagement/component/UserSearchQuery.java, src/main/java/uk/gov/hmcts/darts/usermanagement/component/impl/UserSearchQueryImpl.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserManagementServiceImpl.java, src/main/resources/openapi/usermanagement.yaml
Search for user using is_active field
```
[ ] Yes
[x] No
```
=> DMP-1763: user search by state

src/main/java/uk/gov/hmcts/darts/common/entity/HearingReportingRestrictionsEntity.java
dmp-1599 bug fix
Fix bug
```
[ ] Yes
[x] No
```
=> dmp 1599 fixed type

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerDeleteAudioRequestIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerDeleteTransformedMediaIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerDownloadIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerGetYourAudioIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerGetYourAudioV2IntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerPlaybackIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerTransMediaUpdateLastAccessedTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerUpdateLastAccessedTest.java, src/integrationTest/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImplTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/service/TransientObjectDirectoryServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/TestUtils.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/HearingStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/MediaRequestStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/GetAudioRequestResponseMapper.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/MediaRequestDetailsMapper.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/TransformedMediaDetailsMapper.java, src/main/java/uk/gov/hmcts/darts/audio/model/TransformedMediaDetailsDto.java, src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/TransformedMediaRepository.java, src/main/resources/openapi/audiorequests.yaml
https://tools.hmcts.net/jira/browse/DMP-1726
=> Dmp 1726.get audio requests v2

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerGetYourAudioIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerGetYourAudioV2IntTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-1726
=> DMP-1726 - slight correct to logic

src/main/java/uk/gov/hmcts/darts/authentication/client/impl/OAuthClientImpl.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-1864
SSO config
```
[ ] Yes
[x] No
```
=> DMP-1864: Add SSO configuration

src/main/java/uk/gov/hmcts/darts/common/entity/HearingReportingRestrictionsEntity.java, src/main/resources/db/migration/common/V1_252__add_artificial_id_to_view.sql
Adding artificial id to view
```
[ ] Yes
[x] No
```
=> DMP-1586: Adding artificial id to view

charts/darts-api/values.demo.template.yaml
=> Dmp-1864-demo-env

src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorImpl.java
N/A
For debugging purposes.
```
[ ] Yes
[x] No
```
=> Adding logs to InboundToUnstructuredProcessorImpl

src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorImpl.java, src/test/java/uk/gov/hmcts/darts/datamanagement/service/InboundToUnstructuredProcessorImplTest.java
N/A
- catch any exception
- always save eod entity
```
[ ] Yes
[x] No
```
=> Amending exception handling in inbound to unstructured automated task

src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorImpl.java
N/A
Adding stacktrace
```
[ ] Yes
[x] No
```
=> Adding stacktrace to inbound to unstructured error log

src/main/java/uk/gov/hmcts/darts/arm/service/impl/UnstructuredToArmProcessorImpl.java
https://tools.hmcts.net/jira/browse/DMP-1625
Added extra logging to push arm manifest file
```
[ ] Yes
[x ] No
```
=> Added extra logging to push arm manifest file

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseByIdTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerPatchCaseTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseMapperTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/CaseTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/EventTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/HearingTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/cases/mapper/CasesMapper.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/entity/CourtCaseEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/HearingEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/HearingReportingRestrictionsEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/HearingReportingRestrictionsRepository.java, src/main/resources/openapi/cases.yaml, src/test/java/uk/gov/hmcts/darts/cases/mapper/CasesMapperTest.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java, src/test/resources/Tests/cases/CasesMapperTest/testMapToSingleCase/expectedResponse.json, src/test/resources/Tests/cases/CasesMapperTest/testMapToSingleCaseWithReportingRestriction/expectedResponse.json
handle multiple reporting restrictions
```
[ ] Yes
[x] No
```
=> DMP-1586: handle multiple reporting restrictions

src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorImpl.java
N/A
Adding null check for inbound checksum
Reducing logging
```
[ ] Yes
[ ] No
```
=> Inbound unstructured fixes

src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityGroupFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/UserManagementFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchUserIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostSecurityGroupIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostUserIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerGetUsersIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerSearchIntTest.java, src/main/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityGroupController.java, src/main/resources/openapi/usermanagement.yaml
https://tools.hmcts.net/jira/browse/DMP-1750
As per title
```
[X] Yes
[ ] No
```
=> DMP-1750 Adding /admin to start of admin endpoints

src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsGetControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/hearings/service/GetHearingResponseMapperTest.java, src/main/java/uk/gov/hmcts/darts/cases/mapper/CasesMapper.java, src/main/java/uk/gov/hmcts/darts/hearings/mapper/GetHearingResponseMapper.java, src/main/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImpl.java, src/main/resources/openapi/hearings.yaml, src/test/java/uk/gov/hmcts/darts/hearings/mapper/GetHearingResponseMapperTest.java, src/test/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1587
```
[ ] Yes
[x] No
```
=> dmp 1587 reporting restrictions for hearings

README.md, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/AnnotationArchiveRecordMapperImpl.java, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/TranscriptionArchiveRecordMapperImpl.java, src/test/java/uk/gov/hmcts/darts/arm/service/ArchiveRecordServiceImplTest.java, src/test/resources/Tests/arm/component/ArchiveAnnotationMetadata/expectedResponse.a360, src/test/resources/Tests/arm/component/ArchiveTranscriptionMetadata/expectedResponse.a360, src/test/resources/Tests/arm/service/testGenerateAnnotationArchiveRecord/expectedResponse.a360, src/test/resources/Tests/arm/service/testGenerateTranscriptionArchiveRecord/expectedResponse.a360
https://tools.hmcts.net/jira/browse/DMP-1625
Fixed issue with transcription and annotations manifest file
```
[ ] Yes
[x ] No
```
=> DMP-1625-ARM-CreateMediaManifestFile

src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/MediaArchiveRecordMapperImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/UnstructuredToArmProcessorImpl.java
https://tools.hmcts.net/jira/browse/DMP-1625
Fixed null created date formating
```
[ ] Yes
[ x] No
```
=> Dmp 1625 arm manifest file fix created date

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAttachTranscriptIntTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionNotifications.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionNotificationsTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1136
- Notify requester when transcription is available
- Refactoring transcriptions notifications
```
[ ] Yes
[x] No
```
=> DMP-1136 Notification routing for transcription uploaded and available

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CasesControllerGetTranscriptsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsControllerGetTranscriptsTest.java, src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/ignoreAutomaticTranscripts.json, src/integrationTest/resources/tests/hearings/HearingsControllerGetTranscriptsTest/ignoreAutomaticTranscripts.json, src/main/java/uk/gov/hmcts/darts/audio/service/impl/LastAccessedDeletionDayCalculator.java, src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/java/uk/gov/hmcts/darts/cases/service/CaseService.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/hearings/controller/HearingsController.java, src/main/java/uk/gov/hmcts/darts/hearings/service/HearingsService.java, src/main/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-1397
=> DMP-1397 - dont show automatic transcriptions

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/DataManagementServiceImpl.java
Add logging to see timing on staging
=> DMP-1681 - Add logging

src/main/resources/openapi/audio.yaml
https://tools.hmcts.net/jira/browse/DMP-1937
Added error code
```
[ ] Yes
[x] No
```
=> DMP 1937 add error code

src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java, src/main/resources/openapi/dailylist.yaml, src/test/java/uk/gov/hmcts/darts/dailylist/controller/DailyListProcessEndpointTest.java
https://tools.hmcts.net/jira/browse/DMP-1822
```
[ ] Yes
[x] No
```
=> DMP 1822 changed int to string

src/integrationTest/java/uk/gov/hmcts/darts/dailylist/service/DailyListProcessorTest.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListProcessorImpl.java, src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java
https://tools.hmcts.net/jira/browse/DMP-1712
```
[ ] Yes
[x] No
```
=> DMP 1712 reopen case for new hearing

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-2011
=> DMP-2011 - specify audio encoding rate to same as source.

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/DarStartHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/DarStopHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/InterpreterUsedHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StandardEventHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBase.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBaseWithGatewayStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/TranscriptionTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriptionTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionReportingRestrictionsMapperTest.java, src/integrationTest/resources/tests/transcriptions/transcription/expectedResponse.json, src/main/java/uk/gov/hmcts/darts/cases/mapper/CasesMapper.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/resources/openapi/cases.yaml, src/main/resources/openapi/common.yaml, src/main/resources/openapi/hearings.yaml, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapperTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionMapperTranscriptionTypeTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceGetTranscriptionUrgencyTest.java, src/test/resources/Tests/transcriptions/mapper/TranscriptionResponseMapper/expectedResponseNoStatusSingleEntity.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionResponseMapper/expectedResponseSingleEntity.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionResponseMapper/expectedResponseSingleEntityAutomated.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionResponseMapper/expectedResponseSingleEntityNoHearing.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionResponseMapper/expectedResponseSingleEntityWithWorkflow.json
Handle multiple reporting restrictions for transcriptions
```
[ ] Yes
[x] No
```
=> Handle multiple reporting restrictions for transcriptions

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml
N/A
- doesn't work just in flux
- adding back in here to avoid more disruption
```
[ ] Yes
[ ] No
```
=> Adding function back into chart

src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityGroupFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/UserManagementFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchUserIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostSecurityGroupIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostUserIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerSearchIntTest.java, src/main/java/uk/gov/hmcts/darts/usermanagement/controller/UserController.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/SecurityGroupServiceImpl.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserManagementServiceImpl.java, src/main/resources/openapi/usermanagement.yaml
Changes to API spec to reflect Create User use-case per: https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1722059332#AdminPortalLLDUserManagement-CreateaUserAccount.
See associated Figma design: https://www.figma.com/file/F9hGLvJg18Hya6gUodDXIZ/DARTS-Admin-(SPEC)?type=design&node-id=106-1901&mode=design&t=HyOxMsarFhLgwOON-4
```
[ ] Yes
[x] No
```
=> Update User Management API spec per latest LLD

src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsGetControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/hearings/service/GetHearingResponseMapperTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionReportingRestrictionsMapperTest.java, src/integrationTest/resources/tests/transcriptions/transcription/expectedResponse.json, src/main/java/uk/gov/hmcts/darts/hearings/mapper/GetHearingResponseMapper.java, src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java, src/main/resources/openapi/hearings.yaml, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/hearings/mapper/GetHearingResponseMapperTest.java, src/test/resources/Tests/transcriptions/mapper/TranscriptionResponseMapper/expectedResponseNoStatusSingleEntity.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionResponseMapper/expectedResponseSingleEntity.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionResponseMapper/expectedResponseSingleEntityAutomated.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionResponseMapper/expectedResponseSingleEntityNoHearing.json, src/test/resources/Tests/transcriptions/mapper/TranscriptionResponseMapper/expectedResponseSingleEntityWithWorkflow.json
Correcting-api-field-name
```
[ ] Yes
[x] No
```
=> Correcting-api-field-name

src/main/resources/db/migration/common/V1_255_1_1_v59_v60_updates_annotation.sql, src/main/resources/db/migration/common/V1_255_2_1_v59_v60_updates_case_document_overflow.sql, src/main/resources/db/migration/common/V1_255_2_3_v59_v60_updates_case_document_overflow.sql, src/main/resources/db/migration/common/V1_255_3_1_v59_v60_updates_user_account.sql, src/main/resources/db/migration/postgres/V1_255_1_2_v59_v60_updates_annotation.sql, src/main/resources/db/migration/postgres/V1_255_2_2_v59_v60_updates_case_document_overflow.sql
https://tools.hmcts.net/jira/browse/DMP-2063
=> DMP-2063 - v59 and v60 flyway changes

src/integrationTest/java/uk/gov/hmcts/darts/task/service/ExternalDataStoreDeleterTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/OutboundAudioDeleterProcessorTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/AudioTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/MediaRequestStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TransientObjectDirectoryStub.java, src/main/java/uk/gov/hmcts/darts/audio/service/OutboundAudioDeleterProcessor.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/MediaRequestRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/TransformedMediaRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/TransientObjectDirectoryRepository.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/InboundToUnstructuredAutomatedTask.java, src/main/resources/application-local.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1856
=> DMP-1856 - Mark audios to be deleted from Outbound data store [Task Automation]

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioMetadataIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/EventStub.java, src/main/java/uk/gov/hmcts/darts/audio/config/AudioConfigurationProperties.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-483 
Link audio that has not already been linked to a hearing that is associated with hearings for event/case logs that occurred within a 30 minute window of the audio start and end time.
```
[ ] Yes
[X ] No
```
=> DMP-483 initial implementation

src/main/resources/db/reference/retention.sql
correcting file retention.sql for v7, previous had missed a change documented in the change header and making end_date on retention_policy_type nullable
```
[ ] Yes
[ ] No
```
=> V7 Retention data model

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseMapperTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/service/RetentionPolicyTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/cases/mapper/CasesMapper.java, src/main/java/uk/gov/hmcts/darts/common/entity/CaseRetentionEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/CourtCaseEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRetentionRepository.java, src/main/java/uk/gov/hmcts/darts/retention/enums/CaseStatus.java, src/main/java/uk/gov/hmcts/darts/retention/enums/Policy.java, src/main/resources/openapi/cases.yaml, src/test/java/uk/gov/hmcts/darts/cases/mapper/CasesMapperTest.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/retention/enums/PolicyTest.java
(https://tools.hmcts.net/jira/browse/DMP-1816)
The following fields are added to the get cases (GET /cases/{case_id}) endpoint:
retain_until_date_time (Date/Time field) from the case_retention table
case_closed_date_time (Date/Time field) from the court_case table
retention_date_time_applied (Date/Time field) from the case_retention table 
retention_policy_applied (String) from the case_retention table with rpt_id mapping to a value in retention_policy_type table
```
[ ] Yes
[ x] No
```
=> DMP-1816 Source and test updated to add new fields

src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/AuthorisationImpl.java, src/main/java/uk/gov/hmcts/darts/common/entity/HearingEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/MediaEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/SecurityGroupEntity.java
[DMP-1569](https://tools.hmcts.net/jira/browse/DMP-1569)
Updated authoriseByMediaId to go via Media-Hearing-Courtroom-Courthouse links
```
[ ] Yes
[x] No
```
=> DMP-1569 Change MediaId Authorisation to use Hearing

README.md, bin/db-stg-to-local.sh
https://tools.hmcts.net/jira/browse/DMP-1549
As per title and instructions in the README.
```
[ ] Yes
[x] No
```
=> DMP-1549 Adding script to restore the staging database locally

ModernisedDarts.postman_collection.json, src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityRoleFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerCourtLogsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityRoleControllerIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerGetUsersIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerSearchIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/MediaArchiveRecordMapperImpl.java, src/main/java/uk/gov/hmcts/darts/arm/model/record/metadata/MediaCreateArchiveRecordMetadata.java, src/main/java/uk/gov/hmcts/darts/authorisation/config/AuthorisationAspect.java, src/main/java/uk/gov/hmcts/darts/authorisation/exception/AuthorisationError.java, src/main/java/uk/gov/hmcts/darts/common/repository/SecurityRoleRepository.java, src/main/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityRoleController.java, src/main/java/uk/gov/hmcts/darts/usermanagement/mapper/impl/SecurityRoleMapper.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/SecurityRoleService.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/SecurityRoleServiceImpl.java, src/main/resources/openapi/usermanagement.yaml, src/test/java/uk/gov/hmcts/darts/arm/service/ArchiveRecordServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1994
and fied a flaky test from https://tools.hmcts.net/jira/browse/DMP-2068
=> DMP-1994 - Add GET /admin/security-roles

src/main/java/uk/gov/hmcts/darts/admin/test/TestSupportController.java
N/A
Fixing retention functional tests clean up
```
[ ] Yes
[x] No
```
=> Don't remove retention policy types in functional test cleanup

src/main/resources/db/reference/retention.sql
version 7 of the retention schema, detailed description of the changes in the file header.
```
[ ] Yes
[ ] No
```
=> V7 of Retention Data Model

src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/JudgeTestData.java, src/main/java/uk/gov/hmcts/darts/common/entity/ExternalObjectDirectoryEntity.java, src/main/java/uk/gov/hmcts/darts/datamanagement/api/DataManagementApi.java, src/main/java/uk/gov/hmcts/darts/datamanagement/api/impl/DataManagementApiImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionDownloader.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionDownloaderTest.java
Downloading the document from the latest location.  The downloading functionality has been refactored out of the main service as it was too big.  This has allowed a simpler unit test to cover the new functionality.
```
[ ] Yes
[x] No
```
=> DMP-1908: Downloading transcription documents from the latest location

src/main/resources/db/migration/common/V1_262__retention_policies_update.sql
https://tools.hmcts.net/jira/browse/DMP-2032
Correcting format for duration
```
[ ] Yes
[x] No
```
=> dmp 2032 correct values for retention

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseMapperTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/TestUtils.java, src/test/java/uk/gov/hmcts/darts/common/util/TestUtils.java
https://tools.hmcts.net/jira/browse/DMP-2068
Fixed a flakey test truncating the date time
```
[ ] Yes
[ x] No
```
=> DMP-2068 (Dev only) Fix flaky tests

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseMapperTest.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmResponseFilesProcessorImpl.java
https://tools.hmcts.net/jira/browse/DMP-1737
Added extra logging
```
[ ] Yes
[ x] No
```
=> Dmp 1737 arm pull response files extra logging

src/main/java/uk/gov/hmcts/darts/arm/api/impl/ArmDataManagementApiImpl.java, src/test/java/uk/gov/hmcts/darts/arm/api/impl/ArmDataManagementApiImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1737
Fixed issue with duplicated paths
```
[ ] Yes
[ x] No
```
=> DMP-1737-ARM-PullResponseFiles

src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityGroupFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/UserManagementFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/SecurityGroupTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/GetSecurityGroupsIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/GetSecurityGroupsTest.java, src/main/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityGroupController.java, src/main/java/uk/gov/hmcts/darts/usermanagement/mapper/impl/SecurityGroupCourthouseMapper.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/SecurityGroupService.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/SecurityGroupServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-1251
New endpoint for admin to get security groups
```
[ ] Yes
[x] No
```
=> DMP 1251 get security groups

src/integrationTest/java/uk/gov/hmcts/darts/retention/controller/RetentionControllerPostRetentionIntTest.java, src/main/java/uk/gov/hmcts/darts/retention/exception/RetentionApiError.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImpl.java, src/test/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImplTest.java
=> DMP-1818 change

src/main/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImpl.java, src/test/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImplTest.java
Changing order that errors are thrown.
=> Dmp 1818.comments

src/integrationTest/java/uk/gov/hmcts/darts/task/service/OutboundAudioDeleterProcessorTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorImpl.java
Updating last_modified_by for transformed media
```
[ ] Yes
[x] No
```
=> DMP-2175: Updating last_modified_by for transformed media

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetMetadataIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceGivenBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsGivenBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseMapperTest.java, src/integrationTest/java/uk/gov/hmcts/darts/hearings/service/GetHearingResponseMapperIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/EventTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/MediaTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/SecurityGroupTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/CourtroomStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/EventStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionReportingRestrictionsMapperTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostSecurityGroupIntTest.java, src/main/java/uk/gov/hmcts/darts/common/entity/AnnotationDocumentEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/CaseManagementRetentionEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/CourthouseEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/EventEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/ExternalObjectDirectoryEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/MediaEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/SecurityGroupEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionDocumentEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java, src/main/java/uk/gov/hmcts/darts/usermanagement/mapper/impl/SecurityGroupMapper.java, src/main/resources/db/migration/common/V1_266_1__v62_database_updates.sql, src/main/resources/db/migration/postgres/V1_266_2__v62_database_updates.sql
https://tools.hmcts.net/jira/browse/DMP-2176
=> Dmp 2176.v62 database changes

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmResponseFilesProcessorIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmResponseFilesProcessorImpl.java
https://tools.hmcts.net/jira/browse/DMP-1737
Fixed issue whereby the rows were being locked by the transsctional updating most of the EOD table
```
[ ] Yes
[x ] No
```
=> Dmp 1737 arm pull response files fix row locking

src/main/java/uk/gov/hmcts/darts/retention/mapper/RetentionMapper.java, src/main/resources/openapi/retentions.yaml, src/test/java/uk/gov/hmcts/darts/retention/mapper/RetentionMapperTest.java
https://tools.hmcts.net/jira/browse/DMP-1817
Fix date format
```
[ ] Yes
[x] No
```
=> dmp 1817 truncated date format

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsControllerGetAnnotationsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/TestUtils.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/AnnotationStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerSearchIntTest.java, src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/casesSearchGetEndpointOneObjectReturned.json, src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/casesSearchGetEndpointTwoObjectsReturned.json, src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/ignoreAutomaticTranscripts.json, src/integrationTest/resources/tests/hearings/HearingsControllerGetTranscriptsTest/ignoreAutomaticTranscripts.json, src/integrationTest/resources/tests/transcriptions/transcription/expectedResponse.json, src/main/java/uk/gov/hmcts/darts/common/entity/AnnotationDocumentEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/AnnotationEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/AnnotationRepository.java, src/main/java/uk/gov/hmcts/darts/hearings/controller/HearingsController.java, src/main/java/uk/gov/hmcts/darts/hearings/mapper/GetAnnotationsResponseMapper.java, src/main/java/uk/gov/hmcts/darts/hearings/service/HearingsService.java, src/main/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImpl.java, src/main/resources/openapi/hearings.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/LastAccessedDeletionDayCalculatorTest.java, src/test/java/uk/gov/hmcts/darts/cases/mapper/CasesMapperTest.java, src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java, src/test/java/uk/gov/hmcts/darts/common/util/TestUtils.java, src/test/java/uk/gov/hmcts/darts/hearings/mapper/GetAnnotationsResponseMapperTest.java, src/test/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1889
=> Dmp 1889 GET /hearings/{hearing-id}/annotations endpoint

.idea/codeStyles/Project.xml, ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/retention/controller/RetentionControllerPostRetentionIntTest.java, src/main/java/uk/gov/hmcts/darts/retention/controller/RetentionController.java, src/main/java/uk/gov/hmcts/darts/retention/service/RetentionPostService.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImpl.java, src/main/resources/openapi/retentions.yaml, src/test/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2160
=> DMP-2160 - add validate_only to endpoint

src/integrationTest/java/uk/gov/hmcts/darts/retention/controller/RetentionControllerPostRetentionIntTest.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImpl.java, src/main/resources/openapi/retentions.yaml, src/test/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2184
=> DMP-2184 - Show last automated retention date

src/integrationTest/java/uk/gov/hmcts/darts/retention/controller/RetentionControllerPostRetentionIntTest.java, src/main/java/uk/gov/hmcts/darts/retention/exception/RetentionApiError.java, src/main/java/uk/gov/hmcts/darts/retention/helper/RetentionDateHelper.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImpl.java, src/main/resources/openapi/retentions.yaml, src/test/java/uk/gov/hmcts/darts/retention/helper/RetentionDateHelperTest.java, src/test/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2180
=> DMP-2180 - Max retention Date

src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/SecurityGroupTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/UserAccountTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/AnnotationStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/annotation/component/AnnotationDocumentBuilder.java, src/main/java/uk/gov/hmcts/darts/annotation/component/AnnotationMapper.java, src/main/java/uk/gov/hmcts/darts/annotation/component/AnnotationValidator.java, src/main/java/uk/gov/hmcts/darts/annotation/component/ExternalObjectDirectoryBuilder.java, src/main/java/uk/gov/hmcts/darts/annotation/controller/AnnotationController.java, src/main/java/uk/gov/hmcts/darts/annotation/errors/AnnotationApiError.java, src/main/java/uk/gov/hmcts/darts/annotation/persistence/AnnotationPersistenceService.java, src/main/java/uk/gov/hmcts/darts/annotation/service/AnnotationService.java, src/main/java/uk/gov/hmcts/darts/annotation/service/impl/AnnotationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/authorisation/config/AuthorisationAspect.java, src/main/java/uk/gov/hmcts/darts/common/entity/AnnotationDocumentEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/HearingRepository.java, src/main/resources/openapi/annotations.yaml, src/test/java/uk/gov/hmcts/darts/annotation/AnnotationDocumentBuilderTest.java, src/test/java/uk/gov/hmcts/darts/annotation/AnnotationMapperTest.java, src/test/java/uk/gov/hmcts/darts/annotation/AnnotationServiceTest.java, src/test/java/uk/gov/hmcts/darts/annotation/AnnotationValidatorTest.java, src/test/java/uk/gov/hmcts/darts/annotation/ExternalObjectDirectoryBuilderTest.java
Create annotation with file upload. 
Note: an attempt has been made on this ticket to push more of the testing into the unit test coverage while being lighter ono the integration test.
```
[ ] Yes
[ ] No
```
=> Dmp 1887 create annotation with file upload

src/main/java/uk/gov/hmcts/darts/annotation/component/AnnotationMapper.java, src/test/java/uk/gov/hmcts/darts/annotation/AnnotationMapperTest.java
Adding created by to annotation entity
```
[ ] Yes
[x] No
```
=> DMP-1887: Adding created by to annotation entity

.idea/codeStyles/Project.xml, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/DarStartHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/DarStopHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/InterpreterUsedHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/SetReportingRestrictionEventHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StandardEventHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseManagementRetentionRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRetentionRepository.java, src/main/java/uk/gov/hmcts/darts/event/model/CreatedHearingAndEvent.java, src/main/java/uk/gov/hmcts/darts/event/model/stopandclosehandler/PendingRetention.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DarStartHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DarStopHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DartsEventNullHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/InterpreterUsedHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SentencingRemarksAndRetentionPolicyHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SetReportingRestrictionEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StandardEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StopAndCloseHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/TranscriptionRequestHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/base/EventHandlerBase.java, src/main/java/uk/gov/hmcts/darts/retention/api/RetentionApi.java, src/main/java/uk/gov/hmcts/darts/retention/api/impl/RetentionApiImpl.java, src/main/java/uk/gov/hmcts/darts/retention/helper/RetentionDateHelper.java, src/main/resources/db/migration/common/V1_269__retentionEventHandler.sql, src/test/java/uk/gov/hmcts/darts/retention/helper/RetentionDateHelperTest.java
https://tools.hmcts.net/jira/browse/DMP-2029
=> DMP-2029 - Add retention functionality to the StopAndCloseHandler

ModernisedDarts.postman_collection.json, infrastructure/providers.tf, src/integrationTest/java/uk/gov/hmcts/darts/retention/controller/RetentionControllerPostRetentionIntTest.java, src/main/java/uk/gov/hmcts/darts/retention/controller/RetentionController.java, src/main/java/uk/gov/hmcts/darts/retention/service/RetentionPostService.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImpl.java, src/main/resources/openapi/retentions.yaml, src/test/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2245
=> DMP-2245 - move validate_only to query param

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/DMP-2159
```
[ ] Yes
[ ] No
```
=> DMP-2159 Running gradle assemble before demo DB migration

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandlerTest.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StopAndCloseHandler.java
https://tools.hmcts.net/jira/browse/DMP-1899
=> DMP-1899 - implement default retention policy

src/main/java/uk/gov/hmcts/darts/event/service/handler/DarStartHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DarStopHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DartsEventNullHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/InterpreterUsedHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SentencingRemarksAndRetentionPolicyHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SetReportingRestrictionEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StandardEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StopAndCloseHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/TranscriptionRequestHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/base/EventHandlerBase.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/DarNotifyServiceImpl.java, src/main/java/uk/gov/hmcts/darts/log/api/LogApi.java, src/main/java/uk/gov/hmcts/darts/log/api/impl/LogApiImpl.java, src/main/java/uk/gov/hmcts/darts/log/service/EventLoggerService.java, src/main/java/uk/gov/hmcts/darts/log/service/impl/EventLoggerServiceImpl.java, src/test/java/uk/gov/hmcts/darts/log/service/impl/EventLoggerServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1993
=> DMP-1993 - make use of new LogApi

src/main/java/uk/gov/hmcts/darts/common/entity/CaseDocumentEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/ExternalObjectDirectoryEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/ExternalServiceAuthTokenEntity.java
https://tools.hmcts.net/jira/browse/DMP-2327
=> DMP-2327 - change LocalDateTime to OffsetDateTime

index.html
N/A
As title
```
[ ] Yes
[x] No
```
=> Adding annotations to GitHub Swagger file

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/log/api/LogApi.java, src/main/java/uk/gov/hmcts/darts/log/api/impl/LogApiImpl.java, src/main/java/uk/gov/hmcts/darts/log/service/AtsLoggerService.java, src/main/java/uk/gov/hmcts/darts/log/service/impl/AtsLoggerServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/log/service/impl/AtsLoggerServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1907 
Added logging to ats via an ats logging service
```
[ ] Yes
[ X] No
```
=> DMP-1907 ATS processing/result logging

src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/log/service/impl/AtsLoggerServiceImpl.java, src/test/java/uk/gov/hmcts/darts/log/service/impl/AtsLoggerServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1905 
Logging when each audio request is made
```
[ ] Yes
[X] No
```
=> DMP-1905 added log of audio requests to ats logging service

Jenkinsfile_CNP
=> Feat-darts-test-db-migration

src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/main/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-2353
The "All transcriptions" tab was only showing case-associated transcriptions.
```
[ ] Yes
[x] No
```
=> DMP-2353 Case all transcriptions fix

src/integrationTest/java/uk/gov/hmcts/darts/common/controller/DailyListEntityTest.java, src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java
https://tools.hmcts.net/jira/browse/DMP-2358
- body auth is not required
```
[ ] Yes
[ ] No
```
=> DMP-2358 Fixing authorisation check for dailylists POST

src/main/java/uk/gov/hmcts/darts/cases/mapper/HearingEntityToCaseHearing.java, src/test/java/uk/gov/hmcts/darts/cases/mapper/HearingEntityToCaseHearingTest.java
https://tools.hmcts.net/jira/browse/DMP-2353
- the count should not include automated transcripts unless they are legacy
```
[ ] Yes
[ ] No
```
=> DMP-2353 Hearing transcriptions count fix

src/integrationTest/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImplTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerSearchPostTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdvancedSearchTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/main/java/uk/gov/hmcts/darts/authorisation/api/AuthorisationApi.java, src/main/java/uk/gov/hmcts/darts/authorisation/api/impl/AuthorisationApiImpl.java, src/main/java/uk/gov/hmcts/darts/authorisation/component/UserIdentity.java, src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImpl.java, src/main/java/uk/gov/hmcts/darts/cases/helper/AdvancedSearchRequestHelper.java, src/main/java/uk/gov/hmcts/darts/common/entity/UserRolesCourthousesEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/compositeid/UserRoleCourthouseId.java, src/main/java/uk/gov/hmcts/darts/common/repository/UserRolesCourthousesRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/base/ReadOnlyRepository.java
https://tools.hmcts.net/jira/browse/DMP-2359
=> DMP-2359 - Fix permissions lookup for advanced search

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/CaseRetentionStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/common/repository/RetentionPolicyTypeRepository.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StopAndCloseHandler.java, src/main/java/uk/gov/hmcts/darts/retention/helper/RetentionDateHelper.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImpl.java, src/test/java/uk/gov/hmcts/darts/retention/helper/RetentionDateHelperTest.java, src/test/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2078
=> DMP-2078 - throw error when multiple retention policies

src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/base/EventHandlerBase.java
[DMP-2026](https://tools.hmcts.net/jira/browse/DMP-2026)
As title
```
[ ] Yes
[x] No
```
=> DMP-2026 Always set last modified datetime on case/hearing entities

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAttachTranscriptIntTest.java, src/main/java/uk/gov/hmcts/darts/datamanagement/DataManagementConstants.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-2236
Upload Transcript Document to Unstructured Data store alongwith Inbound.
```
[ ] Yes
[x] No
```
=> dmp-2236 : Upload Transcript to Unstructured Datastore

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/annotation/service/impl/AnnotationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java, src/test/java/uk/gov/hmcts/darts/annotation/AnnotationDownloadServiceTest.java, src/test/java/uk/gov/hmcts/darts/annotation/AnnotationServiceTest.java
=> fix to handle multiple eod Entities.

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerPreviewIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/java/uk/gov/hmcts/darts/hearings/controller/HearingsController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java
https://tools.hmcts.net/jira/browse/DMP-2379
Admin roles are missing from some endpoints, needed in order to test DMP-1508, so this is to give some of the missing roles
=> DMP-2379- add some missing admin roles

src/main/java/uk/gov/hmcts/darts/common/entity/CourthouseEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/RegionEntity.java
This PR relates to 2 jira tickets:
1. https://tools.hmcts.net/jira/browse/DMP-2282
2. https://tools.hmcts.net/jira/browse/DMP-2296
Updates to both RegionEntity and CourthouseEntity table associations
```
[ ] Yes
[ x] No
```
=> DMP-2282_DMP-2296_ implement_get_admin_courthouses_and_extar_parameters

src/integrationTest/java/uk/gov/hmcts/darts/noderegistration/controller/NodeRegistrationControllerTest.java, src/main/java/uk/gov/hmcts/darts/noderegistration/service/impl/NodeRegistrationServiceImpl.java, src/main/resources/openapi/noderegistration.yaml
https://tools.hmcts.net/jira/browse/DMP-2419
Allow courtroom to be auto created
=> DMP-2419 - allow node register to auto create the courtroom

src/functionalTest/java/uk/gov/hmcts/darts/courthouses/CourthousesFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/controller/CourthouseApiTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/RegionStub.java, src/main/java/uk/gov/hmcts/darts/common/repository/RegionRepository.java, src/main/java/uk/gov/hmcts/darts/courthouse/controller/CourthousesController.java, src/main/java/uk/gov/hmcts/darts/courthouse/mapper/AdminRegionToRegionEntityMapper.java, src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseService.java, src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseServiceImpl.java, src/main/resources/openapi/courthouse.yaml, src/test/java/uk/gov/hmcts/darts/courthouse/service/CourthouseServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2281 
Added the GET all regions endpoint to the courthouse feature
```
[ ] Yes
[X] No
```
=> Dmp 2281 admin get regions

infrastructure/main.tf
=> enable pg-stat-statements

src/integrationTest/java/uk/gov/hmcts/darts/common/controller/CourthouseApiTest.java, src/main/java/uk/gov/hmcts/darts/common/entity/CourthouseEntity.java, src/main/java/uk/gov/hmcts/darts/courthouse/controller/CourthousesController.java, src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseService.java, src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseServiceImpl.java
[
](https://tools.hmcts.net/jira/browse/DMP-2280)
Update the existing `GET /courthouses` endpoint to include a `region_id` 
```
[ ] Yes
[x ] No
```
=> DMP-2280_Update_GET_courthouses_to_include_region_id

src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchUserIntTest.java, src/main/resources/openapi/usermanagement.yaml
=> DMP-2459: Allow existing user descriptions to be removed

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java, src/main/java/uk/gov/hmcts/darts/log/api/LogApi.java, src/main/java/uk/gov/hmcts/darts/log/api/impl/LogApiImpl.java, src/main/java/uk/gov/hmcts/darts/log/service/AudioLoggerService.java, src/main/java/uk/gov/hmcts/darts/log/service/impl/AudioLoggerServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/log/service/impl/AudioLoggerServiceImplTest.java
Added logging when audio uploaded
```
[ ] Yes
[x] No
```
=> DMP-1986: Added logging when audio uploaded

src/integrationTest/java/uk/gov/hmcts/darts/task/service/InboundToUnstructuredProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/MediaTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/MediaStub.java, src/integrationTest/resources/application-intTest.yaml, src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/InboundToUnstructuredProcessorSingleElement.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorSingleElementImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/datamanagement/service/InboundToUnstructuredProcessorImplTest.java, src/test/java/uk/gov/hmcts/darts/datamanagement/service/InboundToUnstructuredProcessorSingleElementImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1919
Change the query for processing
```
[ ] Yes
[x] No
```
=> dmp 1919 change to single query

src/main/java/uk/gov/hmcts/darts/courthouse/controller/CourthousesController.java, src/main/java/uk/gov/hmcts/darts/courthouse/exception/CourthouseApiError.java, src/main/resources/openapi/courthouse.yaml, src/test/java/uk/gov/hmcts/darts/courthouse/controller/CourthousesControllerTest.java
https://tools.hmcts.net/jira/browse/DMP-2282
```
[ ] Yes
[x] No
```
=> Using standard error patterns for courthouse not found

src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/log/api/LogApi.java, src/main/java/uk/gov/hmcts/darts/log/api/impl/LogApiImpl.java, src/main/java/uk/gov/hmcts/darts/log/service/CasesLoggerService.java, src/main/java/uk/gov/hmcts/darts/log/service/impl/CasesLoggerServiceImpl.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/log/service/impl/CasesLoggerServiceImplTest.java
Added logging when get cases requested by dar pc
```
[ ] Yes
[x] No
```
=> DMP-2003: Added logging when get cases requested by dar pc

src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArmResponseFilesProcessSingleElementImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-2045
Added logging before deleting blob data
```
[ ] Yes
[ x] No
```
=> Added logging before deleteing blob data

src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListUpdater.java
https://tools.hmcts.net/jira/browse/DMP-2439
```
[ ] Yes
[ ] No
```
=> DMP-2439 Setting modified date time on case/hearing on daily list processing

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerSearchIntTest.java, src/main/java/uk/gov/hmcts/darts/usermanagement/component/impl/UserSearchQueryImpl.java, src/main/java/uk/gov/hmcts/darts/usermanagement/mapper/impl/UserAccountMapper.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserManagementServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-2207
User search mapping fullName to userName
```
[ ] Yes
[X] No
```
=> DMP-2207 Fixed mappings for user search only

src/main/resources/db/migration/common/V1_230__update_audit_activity_standing_data.sql, src/main/resources/db/migration/common/V1_279__update_audit_activity.sql, src/main/resources/db/reference/modernised_darts_standing_data.sql
[DMP-1072](https://tools.hmcts.net/jira/browse/DMP-1072)
Fix flyway migration checksum mismatch
```
[ ] Yes
[x] No
```
=> Fix flyway migration checksum mismatch

src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityGroupFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/GetSecurityGroupsIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/java/uk/gov/hmcts/darts/hearings/controller/HearingsController.java, src/main/java/uk/gov/hmcts/darts/retention/controller/RetentionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/resources/db/migration/common/V1_278__setTranslationQA_Role_To_global_and_use_interpreter.sql
https://tools.hmcts.net/jira/browse/DMP-2137
This PR is for point 1 of DMP-2137. 
Point 2 (search api) has got different requirements as such is addressed in a dedicated PR: https://github.com/hmcts/darts-api/pull/1169
- updated permissions for Translation QA role
- fixed permissions for RCJ Appeals role
```
[ ] Yes
[x] No
```
=> DMP-2137 changed permissions for Translation QA

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml
N/A
It is open on HTTP only now.
```
[ ] Yes
[ ] No
```
=> Setting DARTS_GATEWAY_URL to http

src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationGetTest.java, src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationPostTest.java, src/main/java/uk/gov/hmcts/darts/annotation/builders/AnnotationDocumentBuilder.java, src/main/java/uk/gov/hmcts/darts/annotation/builders/ExternalObjectDirectoryBuilder.java, src/main/java/uk/gov/hmcts/darts/annotation/persistence/AnnotationPersistenceService.java, src/main/java/uk/gov/hmcts/darts/annotation/service/impl/AnnotationDataManagement.java, src/main/java/uk/gov/hmcts/darts/annotation/service/impl/AnnotationUploadServiceImpl.java, src/test/java/uk/gov/hmcts/darts/annotation/builders/AnnotationDocumentBuilderTest.java, src/test/java/uk/gov/hmcts/darts/annotation/builders/ExternalObjectDirectoryBuilderTest.java, src/test/java/uk/gov/hmcts/darts/annotation/service/impl/AnnotationDataManagementTest.java, src/test/java/uk/gov/hmcts/darts/annotation/service/impl/AnnotationUploadTest.java
Fixing annotations and deleting from correct container
```
[ ] Yes
[x] No
```
=> DMP-2051: Fixing annotations and deleting from correct container

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArchiveRecordServiceIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmResponseFilesProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/UnstructuredToArmProcessorTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java, src/main/java/uk/gov/hmcts/darts/common/entity/ExternalObjectDirectoryEntity.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionService.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-2490
Files are not moving from Unstructured to ARM for Media and Transcription types
```
[ ] Yes
[x ] No
```
=> Dmp 2490 Files are not moving from Unstructured to ARM for Transcription types

README.md, charts/darts-api/Chart.yaml, charts/darts-api/values.yaml, docker-compose-local.yml, src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/LogoutIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/ResetPasswordIntTest.java, src/integrationTest/resources/application-intTest.yaml, src/main/resources/application.yaml, src/smokeTest/resources/application-smoke.yaml
https://tools.hmcts.net/jira/browse/DMP-2506
To use dynamic Azure B2C tenant
```
[ ] Yes
[x] No
```
=> dmp-2506 : To use Dynamic Azure Tenant

Jenkinsfile_CNP
DMP-2506
```
[ ] Yes
[ ] No
```
=> dmp-2506 : Add ITHC jenkins config

src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java, src/test/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapperTest.java
DMP-2293 Modify transcription case relationship.
https://tools.hmcts.net/jira/browse/DMP-2293
```
[ ] Yes
[x] No
```
=> DMP-2293 Modify transcription case relationship.

src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityRoleFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityRoleControllerIntTest.java, src/main/resources/openapi/usermanagement.yaml
N/A
As per title
```
[ ] Yes
[x] No
```
=> Adding `role_name` to GET /admin/security-roles endpoint

src/functionalTest/java/uk/gov/hmcts/darts/courthouses/CourthousesFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationDeleteTest.java, src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationGetTest.java, src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationPostTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/controller/CourthouseApiTest.java, src/integrationTest/java/uk/gov/hmcts/darts/courthouse/CourthousePatchTest.java, src/integrationTest/java/uk/gov/hmcts/darts/courthouse/CourthouseUpdateTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/GivenBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/TransactionalAssert.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/RegionTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/common/component/validation/BiValidator.java, src/main/java/uk/gov/hmcts/darts/common/entity/CourthouseEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/CourthouseRepository.java, src/main/java/uk/gov/hmcts/darts/courthouse/controller/CourthousesController.java, src/main/java/uk/gov/hmcts/darts/courthouse/exception/CourthouseApiError.java, src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseService.java, src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseUpdateMapper.java, src/main/java/uk/gov/hmcts/darts/courthouse/validation/CourthousePatchValidator.java, src/main/resources/openapi/courthouse.yaml, src/test/java/uk/gov/hmcts/darts/common/entity/CourthouseEntityTest.java, src/test/java/uk/gov/hmcts/darts/courthouse/service/CourthouseEntityToAdminCourthouseMapperTest.java, src/test/java/uk/gov/hmcts/darts/courthouse/service/CourthouseServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/courthouse/service/CourthouseUpdatePatchToEntityMapperTest.java, src/test/java/uk/gov/hmcts/darts/courthouse/validation/CourthousePatchValidatorTest.java
Added patching courthouse service.  Also a few small steps towards cleaning up the integration test infrastructure.
```
[ ] Yes
[x] No
```
=> DMP-2339: patch courthouses

src/integrationTest/java/uk/gov/hmcts/darts/authorisation/service/AuthorisationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerSearchPostTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdvancedSearchTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdvancedSearchUseInterpreterTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/CaseTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/HearingTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/main/java/uk/gov/hmcts/darts/authorisation/api/AuthorisationApi.java, src/main/java/uk/gov/hmcts/darts/authorisation/api/impl/AuthorisationApiImpl.java, src/main/java/uk/gov/hmcts/darts/authorisation/service/AuthorisationService.java, src/main/java/uk/gov/hmcts/darts/authorisation/service/impl/AuthorisationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/cases/helper/AdvancedSearchRequestHelper.java, src/main/java/uk/gov/hmcts/darts/common/entity/CourtCaseEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/UserAccountCourtCaseEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/compositeid/UserCourtCaseId.java, src/main/resources/db/migration/common/V1_285__user_account_court_case_view.sql
https://tools.hmcts.net/jira/browse/DMP-2137
This PR is for Point 2 of the ticket, the one related to updating the search api to consider the use interpreter permission flag.
See this PR for the changes related to part 1 of the ticket: 
https://github.com/hmcts/darts-api/pull/1148
```
[ ] Yes
[x] No
```
=> DMP-2137: update search API to consider use interpreter flag

config/owasp/suppressions.xml
=> Suppress CVE-2023-36052 (azure-core)

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArchiveRecordServiceIntTest.java, src/integrationTest/resources/tests/arm/service/testGenerateAnnotationArchiveRecord/all_properties/expectedResponse.a360, src/integrationTest/resources/tests/arm/service/testGenerateAnnotationArchiveRecord/live/expectedResponse.a360, src/integrationTest/resources/tests/arm/service/testGenerateAnnotationArchiveRecord/nle/expectedResponse.a360, src/integrationTest/resources/tests/arm/service/testGenerateCaseArchiveRecord/all_properties/expectedResponse.a360, src/integrationTest/resources/tests/arm/service/testGenerateCaseArchiveRecord/live/expectedResponse.a360, src/integrationTest/resources/tests/arm/service/testGenerateCaseArchiveRecord/nle/expectedResponse.a360, src/integrationTest/resources/tests/arm/service/testGenerateMediaArchiveRecord/all_properties/expectedResponse.a360, src/integrationTest/resources/tests/arm/service/testGenerateMediaArchiveRecord/live/expectedResponse.a360, src/integrationTest/resources/tests/arm/service/testGenerateMediaArchiveRecord/nle/expectedResponse.a360, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/AnnotationArchiveRecordMapperImpl.java, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/CaseArchiveRecordMapperImpl.java, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/TranscriptionArchiveRecordMapperImpl.java, src/test/java/uk/gov/hmcts/darts/arm/service/ArchiveRecordServiceImplTest.java, src/test/resources/Tests/arm/service/testGenerateAnnotationArchiveRecord/all_properties/expectedResponse.a360, src/test/resources/Tests/arm/service/testGenerateAnnotationArchiveRecord/invalid_properties_path/expectedResponse.a360, src/test/resources/Tests/arm/service/testGenerateAnnotationArchiveRecord/live/expectedResponse.a360, src/test/resources/Tests/arm/service/testGenerateAnnotationArchiveRecord/nle/expectedResponse.a360, src/test/resources/Tests/arm/service/testGenerateCaseArchiveRecord/all_properties/expectedResponse.a360, src/test/resources/Tests/arm/service/testGenerateCaseArchiveRecord/invalid_properties_path/expectedResponse.a360, src/test/resources/Tests/arm/service/testGenerateCaseArchiveRecord/live/expectedResponse.a360, src/test/resources/Tests/arm/service/testGenerateCaseArchiveRecord/nle/expectedResponse.a360, src/test/resources/Tests/arm/service/testGenerateMediaArchiveRecord/invalid_properties_path/expectedResponse.a360, src/test/resources/Tests/arm/service/testGenerateTranscriptionArchiveRecord/invalid_properties_path/expectedResponse.a360
https://tools.hmcts.net/jira/browse/DMP-2555
Added code to get the file tag from the filename
```
[ ] Yes
[ x] No
```
=> DMP-2555-ManifestFileTag

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerAddAudioRequestDownloadIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerAddAudioRequestPlaybackIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/resources/openapi/audiorequests.yaml
https://tools.hmcts.net/jira/browse/DMP-1559
POST /audio-requests: Only Allow Transcriber, Super_user & Super_Admin to Download Audio Request
```
[ ] Yes
[X] No
```
=> DMP-1559 New audio-requests endpoints

src/functionalTest/java/uk/gov/hmcts/darts/courthouses/CourthousesFunctionalTest.java, src/main/java/uk/gov/hmcts/darts/courthouse/controller/CourthousesController.java, src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseService.java, src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseServiceImpl.java, src/main/resources/openapi/courthouse.yaml, src/test/java/uk/gov/hmcts/darts/courthouse/service/CourthouseServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1244
Removed delete courthouse endpoint
```
[ ] Yes
[x] No
```
=> dmp 1244 removed endpoint

src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseServiceImpl.java
Flushing so that we get the latest last modified timestamp
```
[ ] Yes
[x] No
```
=> DMP-2339: Flushing so that we get the latest last modified timestamp

src/integrationTest/resources/tests/retention/expectedResponse.json, src/main/resources/db/migration/common/V1_260__retention_policies.sql, src/main/resources/db/migration/common/V1_286__update_external_location.sql
DMP-2030 Implement GET /admin/retention-policy-types
fix retention policy table
[### JIRA link (if applicable) ###](https://tools.hmcts.net/jira/browse/DMP-2530)
```
[ ] Yes
[ x] No
```
=> DMP-2030 fix retention policy table

src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java
Catch json parse exception and throwing darts specific exception
```
[ ] Yes
[x] No
```
=> DMP-2518: Catch json parse exception and throwing darts specific exception

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml
https://tools.hmcts.net/jira/browse/DMP-2536
Needs to be false by default.
```
[ ] Yes
[x] No
```
=> DMP-2536 Set TESTING_SUPPORT_ENDPOINTS_ENABLED to false by default

src/functionalTest/java/uk/gov/hmcts/darts/retention/RetentionFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/retention/controller/RetentionControllerGetPolicyByIdTest.java, src/integrationTest/resources/tests/retention/expectedResponsePolicyTypeId.json, src/main/java/uk/gov/hmcts/darts/retention/controller/RetentionController.java, src/main/java/uk/gov/hmcts/darts/retention/exception/RetentionApiError.java, src/main/java/uk/gov/hmcts/darts/retention/mapper/RetentionPolicyMapper.java, src/main/java/uk/gov/hmcts/darts/retention/service/RetentionService.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/RetentionServiceImpl.java, src/main/resources/openapi/retentions.yaml, src/test/java/uk/gov/hmcts/darts/retention/service/impl/RetentionGetPolicyTypesServiceImplTest.java
DMP-2531 Get Retention Policy Type by id
https://tools.hmcts.net/jira/browse/DMP-2531
```
[ ] Yes
[ x] No
```
=> DMP-2531 Get Retention Policy Type by id

infrastructure/providers.tf
N/A
- checking if this is causing the terraform issues we are seeing
```
[ ] Yes
[ ] No
```
=> Downgrade azurerm version

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml
N/A
Setting `API_MODE` and `AUTOMATED_TASK_MODE` for ATS mode.
```
[ ] Yes
[x] No
```
=> ATS mode config fix

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-2479
Updated ARM container and directory structure.
```
[ ] Yes
[x] No
```
=> dmp-2479 : Change ARM blob storage directory

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArchiveRecordServiceIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/CaseDocumentStub.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchUserIntTest.java, src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1OkJsonAndXml/expectedResponse.json, src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1_duplicate_ok/expectedResponse.json, src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1_ok/expectedResponse.json, src/main/java/uk/gov/hmcts/darts/annotation/service/impl/AnnotationDataManagement.java, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/CaseArchiveRecordMapperImpl.java, src/main/java/uk/gov/hmcts/darts/common/entity/AnnotationDocumentEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/AnnotationEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/AuditEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/AuditHeritageEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/CaseDocumentEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/CourtCaseEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/DailyListEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/ExternalObjectDirectoryEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/MediaEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/ObjectHiddenReasonEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionCommentEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionDocumentEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/UserAccountEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/base/ModifiedBaseEntity.java, src/main/resources/db/migration/common/V1_288_1__v63_v64_v65_database_updates.sql, src/main/resources/db/migration/common/V1_288_3__v63_v64_v65_database_updates.sql, src/main/resources/db/migration/common/V1_289_1__v66_database_updates.sql, src/main/resources/db/migration/common/V1_289_2__v66_database_updates.sql, src/main/resources/db/migration/h2/V1_288_2__v63_v64_v65_database_updates.sql, src/main/resources/db/migration/postgres/V1_288_2__v63_v64_v65_database_updates.sql, src/test/java/uk/gov/hmcts/darts/arm/service/ArchiveRecordServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2662
=> Dmp 2662.database updates

src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchSecurityGroupIntTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/UserAccountRepository.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/SecurityGroupServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-2701
Aligning users in a security group with those specified in a patch request
```
[ ] Yes
[x] No
```
=> DMP-2701: Users not being removed from group

ModernisedDarts.postman_collection.json, src/main/java/uk/gov/hmcts/darts/authentication/controller/AuthenticationCommonController.java, src/main/java/uk/gov/hmcts/darts/authentication/controller/AuthenticationController.java, src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationCommonControllerImpl.java, src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationCommonControllerTest.java
https://tools.hmcts.net/jira/browse/DMP-2636
=> DMP-2636 - add GET /userstate endpoint

src/integrationTest/java/uk/gov/hmcts/darts/dailylist/service/DailyListServiceTest.java, src/main/java/uk/gov/hmcts/darts/dailylist/mapper/DailyListMapper.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpl.java, src/test/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpSaveDailyListTest.java
https://tools.hmcts.net/jira/browse/DMP-2249
- covering various scenarios when creating/updating a daily list
- removing a duplicate parse/save of the daily list JSON
```
[ ] Yes
[x] No
```
=> DMP-2249 Setting created/lastModified by columns on daily list

src/main/java/uk/gov/hmcts/darts/authentication/controller/AuthenticationCommonController.java
https://tools.hmcts.net/jira/browse/DMP-2636
As per title
```
[ ] Yes
[x] No
```
=> DMP-2636 Set produces JSON for userstate endpoint

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2730
Add Audio failure due to File Size Check
```
[ ] Yes
[X] No
```
=> DMP-2730 Remove file size validation

src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListUpdater.java, src/test/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListUpdaterTest.java
https://tools.hmcts.net/jira/browse/DMP-2717
DMP-2717 bug: timestamp on hearing and courtcases for daily list
```
[ ] Yes
[ x] No
```
=> DMP-2717 bug: timestamp on hearing and courtcases for daily list

src/main/resources/db/reference/modernised_darts_indexes.sql
revised a number of indexes on character columns, to utilise upper() function
```
[ ] Yes
[ ] No
```
=> V4 Database Indexes

src/integrationTest/java/uk/gov/hmcts/darts/dailylist/service/DailyListProcessorTest.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListProcessorImpl.java
https://tools.hmcts.net/jira/browse/DMP-2631
=> DMP-2631 - Fix Daily List processed status

src/main/resources/db/migration/postgres/V1_291__indexes_v4.sql
https://tools.hmcts.net/jira/browse/DMP-2742
=> DMP-2742 - applv indexes v4

build.gradle, config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/darts/audio/repository/MediaRepositoryIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/repository/CaseRepositoryIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/repository/EodRepositoryHasMediaNotBeenCopiedFromInboundStorageIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/retention/repository/CaseRetentionRepositoryIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/retention/service/ApplyRetentionCaseAssociatedObjectsProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AutomatedTaskServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/UnstructuredToArmBatchProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/CaseRetentionStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/CourtCaseStub.java, src/main/java/uk/gov/hmcts/darts/common/entity/MediaEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRetentionRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/EntityIdOnly.java, src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/MediaRepository.java, src/main/java/uk/gov/hmcts/darts/retention/service/ApplyRetentionCaseAssociatedObjectsProcessor.java, src/main/java/uk/gov/hmcts/darts/retention/service/ApplyRetentionCaseAssociatedObjectsSingleCaseProcessor.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionCaseAssociatedObjectsProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionCaseAssociatedObjectsSingleCaseProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/task/runner/AutomatedTaskName.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/ApplyRetentionCaseAssociatedObjectsAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImpl.java, src/main/resources/application.yaml, src/main/resources/db/migration/common/V1_293__add_task_case_object_apply_retention.sql, src/main/resources/db/migration/common/V1_294__add_task_case_object_apply_retention.sql, src/test/java/uk/gov/hmcts/darts/task/runner/impl/ApplyRetentionCaseAssociatedObjectsAutomatedTaskTest.java
https://tools.hmcts.net/jira/browse/DMP-2627
To keep PRs size reasonably small, this PR tackles applying retention to medias associated to a court case. Separate PRs will tackle annotations, transcriptions and case documents
=> DMP-2627 Implemented apply retention to medias associated to a court case Automated Task

config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CloseOldCasesProcessorTest.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CloseOldCasesProcessorImpl.java
https://tools.hmcts.net/jira/browse/DMP-2204
Is failing to pick up event if there is only one
```
[ ] Yes
[x] No
```
=> dmp 2204 fails if only one event

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerGetUsersIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArmResponseFilesProcessSingleElementImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmBatchProcessResponseFilesImpl.java, src/main/java/uk/gov/hmcts/darts/arm/util/files/BatchInputUploadFileFilenameProcessor.java, src/main/java/uk/gov/hmcts/darts/arm/util/files/CreateRecordFilenameProcessor.java, src/main/java/uk/gov/hmcts/darts/arm/util/files/InputUploadFilenameProcessor.java, src/main/java/uk/gov/hmcts/darts/arm/util/files/InvalidLineFileFilenameProcessor.java, src/main/java/uk/gov/hmcts/darts/arm/util/files/UploadFileFilenameProcessor.java, src/test/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesImplTest.java, src/test/java/uk/gov/hmcts/darts/arm/util/files/BatchInputUploadFileFilenameProcessorTest.java, src/test/java/uk/gov/hmcts/darts/arm/util/files/CreateRecordFilenameProcessorTest.java, src/test/java/uk/gov/hmcts/darts/arm/util/files/InputUploadFilenameProcessorTest.java, src/test/java/uk/gov/hmcts/darts/arm/util/files/InvalidLineFilenameProcessorTest.java, src/test/java/uk/gov/hmcts/darts/arm/util/files/UploadFileFilenameProcessorTest.java
https://tools.hmcts.net/jira/browse/DMP-2803
Fixed issue with pull response files saving json with full path to temp workspace
```
[ ] Yes
[ x] No
```
=> DMP-2803-FixTempWorkspaceSaving

src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/MediaArchiveRecordMapperImpl.java
https://tools.hmcts.net/jira/browse/DMP-2410
Added checking to get via hearing if it exists
```
[ ] Yes
[x ] No
```
=> DMP-2410 Fetching Courtroom details via Hearing table

src/main/resources/application.yaml
Fix for demo environment DailyList header too large
=> dailyList header too large fix

src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListProcessorImpl.java
allow all exceptions to be caught when processing daily list.
=> add extra logging for dailyList processing

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmBatchProcessResponseFilesImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java
https://tools.hmcts.net/jira/browse/DMP-2884
Added functionality to delete the batch IU file
```
[ ] Yes
[ x] No
```
=> DMP-2884 ARM Synchronous Deletion - IU file deletion

src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmBatchProcessResponseFilesImpl.java
https://tools.hmcts.net/jira/browse/DMP-2878
Fixed issue whereby ARM batch pull is unable to find the EOD
```
[ ] Yes
[x ] No
```
=> DMP-2878 ARM Batch Pull Failing to Update EOD where EOD does not exist

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionAdminApprovedIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionRejectedIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerUpdateTranscriptionWithTranscriberIntTest.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SentencingRemarksAndRetentionPolicyHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/TranscriptionRequestHandler.java, src/main/java/uk/gov/hmcts/darts/transcriptions/api/TranscriptionsApi.java, src/main/java/uk/gov/hmcts/darts/transcriptions/api/impl/TranscriptionsApiImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionService.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionNotifications.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/validator/WorkflowValidator.java, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionNotificationsTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/validator/WorkflowValidatorTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/validator/model/StatusTransitionCheck.java
https://tools.hmcts.net/jira/browse/DMP-2736
=> DMP-2736 - add the PATCH /admin/transcriptions/{id} endpoint

src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmBatchProcessResponseFilesImpl.java
https://tools.hmcts.net/jira/browse/DMP-2915
Fixed issue with checksum compare not being case insensitive
```
[ ] Yes
[x ] No
```
=> DMP-2915 MD5 checksum issue

src/main/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/audio/component/impl/SystemCommandExecutorImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2726
Added logging to ATS
```
[ ] Yes
[x ] No
```
=> DMP-2726 Refactor code - If No Media exist against the Media Request

src/main/resources/application.yaml
N/A
Enable shedlock logging
```
[ ] Yes
[x ] No
```
=> Enable shedlock logging

build.gradle, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java
https://tools.hmcts.net/jira/browse/DMP-2754
Bumping springboot
```
[ ] Yes
[x] No
```
=> DMP-2754: Bumping springboot

.github/workflows/ci.yml, README.md
https://tools.hmcts.net/jira/browse/DMP-1731 part 1
Added a change to fix the issue of the integration tests trying to run ffmpeg on github as per changes made in DMP-1661
```
[ ] Yes
[ x] No
```
=> DMP-1731 (Dev Only) Integration tests for ATS - Playback

src/main/resources/application-local.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-2670
Removing cron after migrating to db
```
[ ] Yes
[x] No
```
=> DMP-2670: Removing cron after migrating to db

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/AnnotationStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/CaseDocumentStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAttachTranscriptIntTest.java, src/main/java/uk/gov/hmcts/darts/annotation/builders/AnnotationDocumentBuilder.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/main/resources/db/migration/common/V1_295__alter_tables_for_lastModifiedBy_nonNull.sql
DMP 2696 populate last modified By
https://tools.hmcts.net/jira/browse/DMP-2696
```
[ ] Yes
[ x] No
```
=> DMP-2696-populate-last-modifiedBy

src/integrationTest/java/uk/gov/hmcts/darts/task/service/AdminGetAutomatedTaskServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AdminGetAutomatedTasksTest.java, src/main/java/uk/gov/hmcts/darts/task/controller/AutomatedTasksController.java, src/main/java/uk/gov/hmcts/darts/task/service/AdminAutomatedTaskService.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AdminAutomatedTasksServiceImpl.java, src/main/resources/openapi/tasks.yaml
https://tools.hmcts.net/jira/browse/DMP-2810
Returning all automated tasks
```
[ ] Yes
[x] No
```
=> DMP-2810: Returning all automated tasks

src/integrationTest/java/uk/gov/hmcts/darts/testutils/TestUtils.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/AnnotationTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/CaseTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/CourthouseTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/CourtroomTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/RegionTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/SecurityGroupTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/TranscriptionTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/TranscriptionWorkflowTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/UserAccountTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerSearchTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/given/MigratedTranscriptionSearchGivensBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/given/ModernisedTranscriptionSearchGivensBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/given/TranscriptionSearchGivensBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/service/MigratedTranscriptionSearchTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/service/ModernisedTranscriptionSearchTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionWorkflowRepository.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/model/TranscriptionIdsAndLatestWorkflowTs.java, src/main/java/uk/gov/hmcts/darts/transcriptions/model/TranscriptionSearchResult.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/AdminTranscriptionSearchService.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionSearchQuery.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionSearchServiceImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionSearchQueryImpl.java, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/common/util/TestUtils.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionSearchServiceTest.java
https://tools.hmcts.net/jira/browse/DMP-2735
Admin search transcriptions.  
```
[ ] Yes
[x] No
```
=> DMP-2735: Transcription search

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/SentencingRemarksAndRetentionPolicyHandlerTest.java, src/main/java/uk/gov/hmcts/darts/event/service/CaseManagementRetentionService.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SentencingRemarksAndRetentionPolicyHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StopAndCloseHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/CaseManagementRetentionServiceImpl.java, src/test/java/uk/gov/hmcts/darts/event/service/impl/CaseManagementRetentionServiceImplTest.java
DMP 2748 Move store retention details
https://tools.hmcts.net/jira/browse/DMP-2748
```
[ ] Yes
[x ] No
```
=> DMP-2748 Move store retention details

.idea/codeStyles/Project.xml, src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CloseOldCasesProcessorTest.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CloseOldCasesProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/retention/api/RetentionApi.java, src/main/java/uk/gov/hmcts/darts/retention/api/impl/RetentionApiImpl.java, src/main/java/uk/gov/hmcts/darts/retention/service/RetentionPostService.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-2205
=> DMP-2205 - add pending retention to auto closed cases.

src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/YourTranscriptsQueryImpl.java
Fixing sql bug
```
[ ] Yes
[x] No
```
=> Fixing sql bug

src/integrationTest/java/uk/gov/hmcts/darts/task/service/AdminRunAutomatedTaskTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/common/repository/AutomatedTaskRepository.java, src/main/java/uk/gov/hmcts/darts/task/controller/AutomatedTasksController.java, src/main/java/uk/gov/hmcts/darts/task/exception/AutomatedTaskApiError.java, src/main/java/uk/gov/hmcts/darts/task/service/AdminAutomatedTaskService.java, src/main/java/uk/gov/hmcts/darts/task/service/AutomatedTaskService.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AdminAutomatedTasksServiceImpl.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskRunner.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImpl.java, src/main/resources/application-local.yaml, src/main/resources/openapi/tasks.yaml, src/test/java/uk/gov/hmcts/darts/task/service/impl/AdminAutomatedTasksServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2811
New endpoint that can be used by super admins to trigger an otherwise automated task.
```
[ ] Yes
[x] No
```
=> DMP-2811: trigger task endpoint

README.md, src/integrationTest/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceIntTest.java, src/test/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImplTest.java
https://tools.hmcts.net/jira/browse/DMP-1731
Added integration tests for OutboundFileProcessor
```
[ ] Yes
[x ] No
```
=> Dmp 1731 ATS integration tests playback

src/main/java/uk/gov/hmcts/darts/event/service/impl/EventDispatcherImpl.java
https://tools.hmcts.net/jira/browse/DMP-3056
Remove in-memory cache. Redis cache will be introduced as part of a future change, depending on performance. 
```
[ ] Yes
[x ] No
```
=> DMP-3056 Remove in-memory cache

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml
=> Adding ARM_URL config for KEDA

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerPreviewIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AdminPatchAutomatedTaskTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AdminUpdateAutomatedTaskServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/AwaitabilityUtil.java, src/main/java/uk/gov/hmcts/darts/task/controller/AutomatedTasksController.java, src/main/java/uk/gov/hmcts/darts/task/service/AdminAutomatedTaskService.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AdminAutomatedTasksServiceImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java, src/main/resources/openapi/tasks.yaml
https://tools.hmcts.net/jira/browse/DMP-2813
Adding endpoint to patch automated tasks
```
[ ] Yes
[x] No
```
=> DMP-2813: Adding endpoint to patch automated tasks

.github/workflows/ci.yml, src/test/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3005
```
[ ] Yes
[x] No
```
=> DMP-3005 Adding test for failed automated task log entry

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventControllerGetEventsMappingTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/EventHandlerTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java, src/main/java/uk/gov/hmcts/darts/event/service/EventMappingService.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/EventMappingServiceImpl.java, src/main/resources/openapi/event.yaml, src/test/java/uk/gov/hmcts/darts/event/service/impl/EventMappingServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2819
Implement the GET /event-mappings/{id} endpoint
```
[ ] Yes
[ x] No
```
=> DMP-2819 Implement GET event mappings endpoint

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArchiveRecordServiceIntTest.java, src/integrationTest/resources/tests/arm/service/testGenerateAnnotationArchiveRecord/expectedResponse.a360, src/integrationTest/resources/tests/arm/service/testGenerateCaseArchiveRecord/expectedResponse.a360, src/integrationTest/resources/tests/arm/service/testGenerateMediaArchiveRecord/expectedResponse.a360, src/integrationTest/resources/tests/arm/service/testGenerateTranscriptionArchiveRecord/expectedResponse.a360, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/AnnotationArchiveRecordMapperImpl.java, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/CaseArchiveRecordMapperImpl.java, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/MediaArchiveRecordMapperImpl.java, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/TranscriptionArchiveRecordMapperImpl.java
https://tools.hmcts.net/jira/browse/DMP-2889
Fetching the Event Date from Retention Date if present else use the Creation Date
```
[ ] Yes
[ ] No
```
=> dmp-2889: Fetch Event Date for ARM Manifest file

src/integrationTest/java/uk/gov/hmcts/darts/audio/component/impl/AudioBeingProcessedFromArchiveQueryImplIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/component/impl/AudioBeingProcessedFromArchiveQueryImpl.java, src/main/java/uk/gov/hmcts/darts/audio/component/impl/AudioBeingProcessedFromArchiveQueryResultRowMapper.java, src/main/java/uk/gov/hmcts/darts/audio/model/AudioBeingProcessedFromArchiveQueryResult.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java, src/main/resources/openapi/audio.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2978
Completes the implementation of deactivating a user and how the transcriptions are managed
```
[ ] Yes
[x ] No
```
=>  DMP-2978 preview message if media is archived in ARM

src/main/java/uk/gov/hmcts/darts/common/datamanagement/api/DataManagementFacadeImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/ObjectRetrievalQueueRepository.java, src/test/java/uk/gov/hmcts/darts/common/datamanagement/api/DataManagementFacadeImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2308 
When no strored EOD object exist for a media and transcription document, create an entry in retrieval queue table
```
[ ] Yes
[X] No
```
=> DMP-2308 add missing blob to object retrieval queue table

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventControllerGetEventHandlersTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java, src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java, src/main/resources/openapi/event.yaml
https://tools.hmcts.net/jira/browse/DMP-2816
Implementation of the GET /admin/event-handlers endpoint
```
[ ] Yes
[x ] No
```
=> DMP-2816 Get event handlers endpoint

build.gradle, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/AbstractLockableAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/service/AutomatedTaskService.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AdminAutomatedTasksServiceImpl.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImpl.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/ManualTaskService.java, src/main/resources/application-local.yaml, src/test/java/uk/gov/hmcts/darts/task/service/impl/AdminAutomatedTasksServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3079
Configure tasks for manual execution
```
[ ] Yes
[x] No
```
=> DMP-3079: Configure tasks for manual execution

README.md, src/functionalTest/java/uk/gov/hmcts/darts/events/EventMapperFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventControllerGetEventMappingByIdTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventControllerGetEventMappingsTest.java, src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java, src/main/java/uk/gov/hmcts/darts/event/service/EventMappingService.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/EventMappingServiceImpl.java, src/main/resources/openapi/event.yaml, src/test/java/uk/gov/hmcts/darts/event/service/impl/EventMappingServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2817
Implementation of the GET /admin/event-mappings endpoint
```
[ ] Yes
[x ] No
```
=> DMP-2817 Get event mappings endpoint

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventControllerDeleteEventMappingTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventControllerGetEventMappingByIdTest.java, src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java, src/main/java/uk/gov/hmcts/darts/event/exception/EventError.java, src/main/java/uk/gov/hmcts/darts/event/service/EventMappingService.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/EventMappingServiceImpl.java, src/main/resources/openapi/event.yaml, src/test/java/uk/gov/hmcts/darts/event/service/impl/EventMappingServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2820
=> DMP-2820 - admin endpoint to delete event handlers

src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmApiServiceImpl.java
DMP-3140 - Temp change
```
[ ] Yes
[x] No
```
=> dmp-3140: Temporary log change to ARM token

src/main/resources/application.yaml, src/main/resources/db/migration/common/V1_300__update_arm_automated_tasks_batch_size.sql
https://tools.hmcts.net/jira/browse/DMP-3128
Set the arm automated tasks batch size to 10
```
[ ] Yes
[ x] No
```
=> DMP-3128 Change ARM batch size

src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmApiServiceImpl.java
DMP-3140
```
[ ] Yes
[x] No
```
=> Dmp 3140 arm logs

src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java
https://tools.hmcts.net/jira/browse/DMP-2208
Apply a cast when working with timestamps against postgres
```
[ ] Yes
[x] No
```
=> DMP-2208: Apply fix to sql so that we dont fail when working against postgres

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetMediaRequestTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/service/TransientObjectDirectoryServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/MediaRequestTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestMapper.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/main/resources/openapi/audiorequests.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-2880
Find media request by id
```
[ ] Yes
[x] No
```
=> DMP-2880: Find media request by id

src/main/java/uk/gov/hmcts/darts/audio/validation/AddAudioFileValidator.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-3208
=> DMP-3208 - fix Add Audio media type filter to allow files from mid-tier

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/dailylist/controller/DailyListPatchControllerV2Test.java, src/integrationTest/java/uk/gov/hmcts/darts/dailylist/controller/DailyListPostControllerV2Test.java, src/integrationTest/java/uk/gov/hmcts/darts/dailylist/service/DailyListServiceTest.java, src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java, src/main/java/uk/gov/hmcts/darts/dailylist/mapper/DailyListMapper.java, src/main/java/uk/gov/hmcts/darts/dailylist/mapper/DailyListPostRequestMapper.java, src/main/java/uk/gov/hmcts/darts/dailylist/model/DailyListPostRequestInternal.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/DailyListService.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpl.java, src/main/java/uk/gov/hmcts/darts/dailylist/validation/DailyListPostValidator.java, src/main/resources/openapi/dailylist.yaml, src/test/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpSaveDailyListTest.java, src/test/java/uk/gov/hmcts/darts/dailylist/validation/DailyListPostValidatorTest.java
https://tools.hmcts.net/jira/browse/DMP-3209
DailyLists were too big to be transmitted via header, so changing to request body.
=> Dmp 3209.daily list request body

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventControllerDeleteEventMappingTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/SentencingRemarksAndRetentionPolicyHandlerTest.java, src/main/resources/db/migration/common/V1_303__update_event_andler_mappings.sql
https://tools.hmcts.net/jira/browse/DMP-3060
Updating event handlers
```
[ ] Yes
[x] No
```
=> DMP-3060: Updating event handlers

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsGivenBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3204
Added additional checks to handle multiple processing of same media requests
```
[ ] Yes
[x] No
```
=> Dmp 3204 ats parallel run check

src/main/resources/db/migration/common/V1_304__update_updcase_handler.sql
Set updcase handler to null handler
```
[ ] Yes
[x] No
```
=> DMP-3060: set updcase handler to null handler

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/SentencingRemarksAndRetentionPolicyHandler2Test.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/SentencingRemarksAndRetentionPolicyHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/SentencingRemarksAndRetentionPolicyHandlerTest2.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SentencingRemarksAndRetentionPolicyHandler.java
https://tools.hmcts.net/jira/browse/DMP-3103
=> DMP-3103 - Handle a duplicate automatic transcription event gracefully.

src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListUpdater.java, src/test/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListUpdaterTest.java
https://tools.hmcts.net/jira/browse/DMP-3245
=> DMP-3245 - Fix for daily list unable to process times after noon.

src/main/java/uk/gov/hmcts/darts/common/datamanagement/api/DataManagementFacadeImpl.java, src/test/java/uk/gov/hmcts/darts/common/datamanagement/api/DataManagementFacadeImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3218
Object Retrieval Queue Bug
```
[ ] Yes
[x] No
```
=> dmp-3218: Object Retrieval Queue missing mandatory fields

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImplTest.java
DMP-3242
Added the missing ExternalLocation and Checksum in ExternalObject directory and Media table.
```
[ ] Yes
[x] No
```
=> dmp-3242: Add Audio missing External Location and Checksum

ModernisedDarts.postman_collection.json, src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java, src/main/resources/openapi/dailylist.yaml
part 5 of 5 - remove temporary v2 endpoint
https://tools.hmcts.net/jira/browse/DMP-3209
=> DMP-3209 - remove temp dailyList v2 endpoint

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetAdminMediasIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/main/resources/openapi/audio.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplAdminMediaSearchTest.java, src/test/java/uk/gov/hmcts/darts/audio/validation/AdminMediaSearchRequestValidatorTest.java
https://tools.hmcts.net/jira/browse/DMP-3254
Correct various error messages in the /admin/medias endpoint
=> DMP-3254 - correct /admin/medias error messages

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml
=> Changing default ATS max replicas to 5

README.md, bin/secrets-stg.sh, charts/darts-api/Chart.yaml, charts/darts-api/values.dev.template.yaml, charts/darts-api/values.yaml, docker-compose-local.yml, src/functionalTest/resources/application-functionalTest.yaml, src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmApiServiceIntTest.java, src/integrationTest/resources/application-intTest.yaml, src/main/java/uk/gov/hmcts/darts/arm/client/ArmTokenClient.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/AvailableEntitlementProfile.java, src/main/java/uk/gov/hmcts/darts/arm/config/ArmApiConfigurationProperties.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmApiServiceImpl.java, src/main/resources/application-dev.yaml, src/main/resources/application.yaml, src/smokeTest/resources/application-smoke.yaml
https://tools.hmcts.net/jira/browse/DMP-3183
Integrated ARM Authorisation endpoints
```
[ ] Yes
[x] No
```
=> Dmp 3183 integrate arm authentication endpoints

ModernisedDarts.postman_collection.json
No JIRA ticket
Apply postman tests for admin endpoints DMP-3104, DMP-3105, DMP-2845, DMP-2208
```
[ ] Yes
[ x] No
```
=> Apply postman tests for DMP-3104, DMP-3105, DMP-2845, DMP-2208

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmBatchProcessResponseFilesImpl.java
DMP-3248
Added null check during ARM checksum validation
```
[ ] Yes
[x] No
```
=> dmp-3248: Null check during ARM checksum validation

src/functionalTest/java/uk/gov/hmcts/darts/datamanagement/DataManagementServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/UnstructuredToArmBatchProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/UnstructuredToArmProcessorTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DataManagementServiceStubImpl.java, src/main/java/uk/gov/hmcts/darts/arm/api/ArmDataManagementApi.java, src/main/java/uk/gov/hmcts/darts/arm/api/impl/ArmDataManagementApiImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractUnstructuredToArmProcessor.java, src/main/java/uk/gov/hmcts/darts/datamanagement/config/DataManagementConfiguration.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/DataManagementService.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/DataManagementServiceImpl.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorSingleElementImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/api/impl/ArmDataManagementApiImplTest.java, src/test/java/uk/gov/hmcts/darts/arm/service/UnstructuredToArmProcessorImplTest.java, src/test/java/uk/gov/hmcts/darts/datamanagement/service/DataManagementServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/datamanagement/service/InboundToUnstructuredProcessorSingleElementImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3126
```
[ ] Yes
[x] No
```
=> DMP-3126 use azcopy to push raw data from unstructured to arm

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java
DMP-3204
Multiple Pod ATS execution issue fix
```
[ ] Yes
[x] No
```
=> dmp-3204: ATS multiple pods execution issue

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetAdminMediasByIdIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/retention/service/ApplyRetentionCaseAssociatedObjectsProcessorIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/AdminMediaMapper.java, src/main/java/uk/gov/hmcts/darts/audio/service/AdminMediaService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/entity/MediaEntity.java, src/main/resources/openapi/audio.yaml, src/test/java/uk/gov/hmcts/darts/audio/mapper/AdminMediaMapperTest.java
Implement GET /admin/medias/\<id\>
```
[ ] Yes
[x] No
```
=> DMP-3169: Implement GET /admin/medias/<id>

src/main/java/uk/gov/hmcts/darts/common/entity/ObjectHiddenReasonEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionDocumentEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/ObjectHiddenReasonRepository.java, src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapperTest.java, src/test/java/uk/gov/hmcts/darts/util/EntityIdPopulator.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/ObjectAdminActionTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/ObjectHiddenReasonTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/TranscriptionDocumentTestData.java
https://tools.hmcts.net/jira/browse/DMP-3171
Adding extra fields to transcription doc response
```
[ ] Yes
[x] No
```
=> DMP-3171: Adding extra fields to transcription doc response

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceGivenBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
DMP-3091
Dont process hidden media during ATS
```
[ ] Yes
[x] No
```
=> Dmp 3091 ats dont process hidden media

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmResponseFilesProcessorIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArmResponseFilesProcessSingleElementImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmBatchProcessResponseFilesImpl.java
DMP-3273
added logic to Increment ARM transfer attempt
```
[ ] Yes
[x] No
```
=> dmp-3273: Increment ARM Transfer Attempt for INVALID file scenario

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetMetadataIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/MediaStub.java, src/main/java/uk/gov/hmcts/darts/common/repository/MediaRepository.java
DMP-3090
Dont show Audio when Audio is Hidden.
```
[ ] Yes
[x] No
```
=> dmp-3090: Dont show hidden media on Hearing screen

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioMetadataIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/entity/HearingEntity.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImplTest.java
https://github.com/hmcts/darts-api/pull/1546
=> DMP-3318 - resolve issue with hearing_media_ae_pk constraint violation

.gitignore, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImplTest.java
remove duplicate case numbers before processing addAudio
https://tools.hmcts.net/jira/browse/DMP-3318
=> Dmp 3318.duplicate hearing media pk

src/main/resources/db/migration/common/V1_316__adding_aud_act_resetting_pks.sql
https://tools.hmcts.net/jira/browse/DMP-2799
Redoing audit activities db migrations
```
[ ] Yes
[x] No
```
=> DMP-2799: Redoing audit activities db migrations

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerAdminSearchTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdminSearchTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/CourtCaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/HearingStub.java, src/integrationTest/resources/tests/cases/CaseControllerAdminSearchTest/testOk/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdminSearchTest/allResults/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdminSearchTest/hearingDateEndOnly/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdminSearchTest/hearingDateStartAndEndOnly/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdminSearchTest/hearingDateStartOnly/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdminSearchTest/multipleFieldsExcludingHearingDate/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdminSearchTest/usingCourthouseIds/expectedResponse.json, src/integrationTest/resources/tests/cases/CaseServiceAdminSearchTest/usingEmptyCourthouseIds/expectedResponse.json, src/integrationTest/resources/tests/cases/usingEmptyCourthouseIds/expectedResponse.json, src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/java/uk/gov/hmcts/darts/cases/helper/AdminCasesSearchRequestHelper.java, src/main/java/uk/gov/hmcts/darts/cases/mapper/AdminCasesSearchResponseMapper.java, src/main/java/uk/gov/hmcts/darts/cases/service/CaseService.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/resources/application.yaml, src/main/resources/openapi/cases.yaml, src/test/java/uk/gov/hmcts/darts/cases/mapper/AdminCasesSearchResponseMapperTest.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/CaseTestData.java
https://tools.hmcts.net/jira/browse/DMP-3266
=> DMP-3266 implement POST /admin/cases/search

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionWorkflowAuditTest.java, src/main/java/uk/gov/hmcts/darts/audit/api/AuditApi.java, src/main/java/uk/gov/hmcts/darts/audit/api/impl/AuditApiImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-2799
Adding overloaded audit method to record case
```
[ ] Yes
[x] No
```
=> DMP-2799: Adding overloaded audit method to record case

ModernisedDarts.postman_collection.json, src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsControllerGetTranscriptsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionDocumentStub.java, src/integrationTest/resources/tests/hearings/HearingsControllerGetTranscriptsTest/ignoreHiddenTranscripts.json, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/test/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3199
=> DMP-3199 - hide transcripts on GET /hearings/{hearing_id}/transcripts

src/main/java/uk/gov/hmcts/darts/util/AzureCopyUtil.java
to investigate issue on Demo env.
```
[ ] Yes
[ x] No
```
=>  DMP-3349 temporarily logging az copy error output

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceGetTranscriptsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepositoryTest.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3197
- when the associated transcription documents are marked as hidden
```
[ ] Yes
[ ] No
```
=> DMP-3197 Hiding transcripts for get by case ID response

src/main/java/uk/gov/hmcts/darts/arm/client/model/ArmTokenResponse.java
DMP-3359
Ignore unwanted attributes from ARM token endpoint
```
[ ] Yes
[x] No
```
=> dmp-3359: Ignore unwanted attributes from ARM token endpoint

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsIntTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/YourTranscriptsQueryImpl.java
https://tools.hmcts.net/jira/browse/DMP-3200
Amending `YourTranscriptsQueryImpl` SQL queries 
- formatting sensibly (IMO)
- adding EXISTS/NOT EXISTS for hidden document functionality
- testing
```
[ ] Yes
[ ] No
```
=> DMP-3200 Hidden transcripts should not be visible on Your Transcripts screen

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImplTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java
https://tools.hmcts.net/jira/browse/DMP-3338
Hiding completed transcripts with hidden documents
- for the transcribers "Your work" tab
- better SQL formatting (IMO)
```
[ ] Yes
[x] No
```
=> DMP-3338 Hidden transcripts should not be visible in Completed tab on Your Work (Transcriber flow)

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmApiServiceIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmApiServiceImpl.java
[DMP-3359](https://tools.hmcts.net/jira/browse/DMP-3359)
Format ARM's Bearer Token
```
[ ] Yes
[x] No
```
=> dmp-3359: Format ARM bearer token

src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityRoleFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/repository/SecurityRoleRepositoryTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/OutboundAudioDeleterProcessorTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBase.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/OpenInViewUtil.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityRoleControllerIntTest.java, src/integrationTest/resources/tests/usermanagement/SecurityGroupControllerGetTest/securityGroupsGetEndpointAllReturned.json, src/main/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/common/entity/TransformedMediaEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/UserAccountEntity.java, src/main/java/uk/gov/hmcts/darts/common/enums/SecurityGroupEnum.java, src/main/resources/db/migration/common/V1_322__media_in_perpetuity.sql, src/main/resources/db/migration/common/V1_325__media_in_perpetuity.sql, src/test/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorImplTest.java, src/test/java/uk/gov/hmcts/darts/common/entity/UserAccountEntityTest.java
https://tools.hmcts.net/jira/browse/DMP-3096
Add group and role, media_in_perpetuity and media_accessor
```
[ ] Yes
[x] No
```
=> DMP-3096: Add group and role, media_in_perpetuity and media_accessor

src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmApiServiceImpl.java, src/main/resources/application.yaml
DMP-3359
Add Feign Logging
```
[ ] Yes
[x] No
```
=> dmp-3359: Enable FEIGN Full Logging

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmResponseFilesProcessorIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArmResponseFilesProcessSingleElementImpl.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/AutomatedTaskProcessorFactoryImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmBatchProcessResponseFilesImpl.java, src/test/java/uk/gov/hmcts/darts/arm/component/impl/UnstructuredToArmProcessorFactoryTest.java, src/test/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3184
```
[ ] Yes
[x] No
```
=> DMP-3184 use eod checksum for ARM pull checksum validation

src/integrationTest/java/uk/gov/hmcts/darts/task/service/OutboundAudioDeleterProcessorTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/TransformedMediaRepository.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3096?devStatusDetailDialog=branch
Using entity graph to force load lazy fields
```
[ ] Yes
[x] No
```
=> DMP-3096: Using entity graph to force load lazy fields

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/HandlerTestData.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StandardEventHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/common/entity/HearingReportingRestrictionsEntity.java, src/main/java/uk/gov/hmcts/darts/common/repository/EventLinkedCaseRepository.java, src/main/java/uk/gov/hmcts/darts/event/service/EventPersistenceService.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DarStartHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DarStopHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DartsEventNullHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/InterpreterUsedHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SentencingRemarksAndRetentionPolicyHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SetReportingRestrictionEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StandardEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StopAndCloseHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/base/EventHandlerBase.java, src/main/resources/db/migration/common/V1_328__drop_case_number_from_view.sql
https://tools.hmcts.net/jira/browse/DMP-3054
Recording event_linked_case for darts events
```
[ ] Yes
[x] No
```
=> DMP-3054: Recording event_linked_case for darts events

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-3425
```
[ ] Yes
[x ] No
```
=> DMP-3425 updated dets container name to new container

src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java
N/A
The variable was named in a confused way, renaming to avoid any future confusion.
```
[ ] Yes
[ ] No
```
=> Minor name change for notification service

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StandardEventHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/EventStub.java, src/main/java/uk/gov/hmcts/darts/event/enums/EventStatus.java, src/main/java/uk/gov/hmcts/darts/event/service/EventPersistenceService.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/EventTestData.java
https://tools.hmcts.net/jira/browse/DMP-1713
- set to "2" which means modernised
```
[ ] Yes
[x] No
```
=> DMP-1713 Setting event.event_status when receiving events

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerPreviewIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioPreviewTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBase.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/PostgresIntegrationBase.java
https://tools.hmcts.net/jira/browse/DMP-3514
```
[ ] Yes
[x] No
```
=>  DMP-3514 Re-enable tests relying on Redis testcontainer

src/functionalTest/java/uk/gov/hmcts/darts/cases/CasesFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetEventByCaseIdTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceGetEventsTest.java, src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/java/uk/gov/hmcts/darts/cases/mapper/EventMapper.java, src/main/java/uk/gov/hmcts/darts/cases/service/CaseService.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java, src/main/resources/openapi/cases.yaml, src/test/java/uk/gov/hmcts/darts/cases/mapper/EventMapperTest.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java, src/test/java/uk/gov/hmcts/darts/hearings/mapper/GetEventsResponseMapperTest.java, src/test/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImplTest.java, src/test/resources/Tests/cases/CaseServiceTest/testGetEventsByCase/expectedResponse.json
https://tools.hmcts.net/jira/browse/DMP-3461
Endpoint to get events by case id
```
[ ] Yes
[ x] No
```
=> DMP-3461 Get events by case id endpoint

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImplTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java
https://tools.hmcts.net/jira/browse/DMP-3336
- picking the latest "with transcriber" transcription workflow for each transcription
- ensuring that if multiple exist, it only returns the parent transcription once
```
[ ] Yes
[x] No
```
=> DMP-3336 Fixing assigned transcripts query

src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationDeleteTest.java, src/integrationTest/java/uk/gov/hmcts/darts/courthouse/CourthouseUpdateTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventSearchControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/AdminEventSearchTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/AdminEventsSearchGivensBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/TransactionalUtil.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/CourtCaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostSecurityGroupIntTest.java, src/integrationTest/resources/logback-test.xml, src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java, src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java, src/main/java/uk/gov/hmcts/darts/event/exception/EventError.java, src/main/java/uk/gov/hmcts/darts/event/mapper/EventSearchMapper.java, src/main/java/uk/gov/hmcts/darts/event/model/EventSearchResult.java, src/main/java/uk/gov/hmcts/darts/event/service/EventSearchService.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/EventSearchServiceImpl.java, src/main/resources/application.yaml, src/main/resources/openapi/event.yaml, src/test/java/uk/gov/hmcts/darts/event/mapper/EventSearchMapperTest.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/CourthouseTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/CourtroomTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/EventTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/HearingTestData.java
https://tools.hmcts.net/jira/browse/DMP-3174
Admin event search
```
[ ] Yes
[x] No
```
=> DMP-3174: Admin event search

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StandardEventHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandlerTest.java, src/main/java/uk/gov/hmcts/darts/event/service/EventPersistenceService.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DarStartHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DarStopHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/DartsEventNullHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/InterpreterUsedHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SentencingRemarksAndRetentionPolicyHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/SetReportingRestrictionEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StandardEventHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StopAndCloseHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/base/EventHandlerBase.java
Fixing courtroom doesn't exist when receiving darts event
https://tools.hmcts.net/jira/browse/DMP-3054
```
[ ] Yes
[x] No
```
=> DMP-3054: Fixing courtroom doesn't exist when receiving darts event

src/main/java/uk/gov/hmcts/darts/audio/config/AudioConfigurationProperties.java, src/main/java/uk/gov/hmcts/darts/audio/validation/AddAudioFileValidator.java, src/main/java/uk/gov/hmcts/darts/audio/validation/AddAudioMetaDataValidator.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-3256
=> DMP-3256 - add extra allowed media extensions

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerRequestTranscriptionIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/given/MigratedTranscriptionSearchGivensBuilder.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java, src/test/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntityTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3302
```
[ ] Yes
[x ] No
```
=>  DMP-3302 set courtroom when linking transcription request to hearing(s)

src/integrationTest/java/uk/gov/hmcts/darts/testutils/DateHelper.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriberTranscriptsIntTest.java
https://tools.hmcts.net/jira/browse/DMP-1550
Improve transcription integration tests by using established pattern of comparing the whole JSON response 
```
[ ] Yes
[x ] No
```
=> DMP-1550 Improve transcription integration tests

src/main/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentSingleCaseProcessorImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentSingleCaseProcessorImplTest.java
DMP-3562
Updated the CaseDocument Filename to include extension
```
[ ] Yes
[x] No
```
=> dmp-3562: update the case document filename to include extension

.github/workflows/ci.yml, .github/workflows/codeql.yml, Dockerfile, README.md, build.gradle, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StandardEventHandlerTest.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/OutboundFileZipGeneratorHelperImplTest.java, src/test/java/uk/gov/hmcts/darts/common/util/CommandRunnerTest.java
https://tools.hmcts.net/jira/browse/DMP-3387
Upgrade Java to version 21
```
[ ] Yes
[ x] No
```
=> DMP-3387 Upgrade Java to version 21

src/main/java/uk/gov/hmcts/darts/event/exception/DarNotifyError.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StopAndCloseHandler.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/DarNotifyServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-3354
- this to ensure the notification occurs when then case is closed
- adding a DARTS specific error and catching it
```
[ ] Yes
[ ] No
```
=> DMP-3354 Reverting StopAndCloseHandler to use sync DAR stop notification

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-3470
```
[ ] Yes
[ x] No
```
=>  DMP-3470 improved logging for ATS processing

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriberTranscriptsIntTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java
https://tools.hmcts.net/jira/browse/DMP-3574
=> Dmp 3574.mutlriple transcript request results

build.gradle, src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerSearchPostTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/repository/EventRepositoryTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/EventProcessorTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AutomatedTaskServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/EventStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriberTranscriptsIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/component/AutomatedTaskProcessorFactory.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/AutomatedTaskProcessorFactoryImpl.java, src/main/java/uk/gov/hmcts/darts/cases/util/RequestValidator.java, src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java, src/main/java/uk/gov/hmcts/darts/event/service/CleanupCurrentFlagEventProcessor.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/CleanupCurrentFlagEventProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/task/runner/AutomatedTaskName.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/CleanupCurrentEventTask.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImpl.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/ManualTaskService.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java, src/main/resources/db/migration/common/V1_332__add_task_cleanup_current_event.sql, src/test/java/uk/gov/hmcts/darts/arm/component/impl/UnstructuredToArmProcessorFactoryTest.java, src/test/java/uk/gov/hmcts/darts/task/runner/impl/CleanCurrentEventTaskTest.java
=> sync demo with master

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerSearchPostTest.java, src/main/java/uk/gov/hmcts/darts/cases/util/RequestValidator.java
https://tools.hmcts.net/jira/browse/DMP-3501
=> DMP-3501 - allow advanced search with just courthouse and date range

src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityGroupFunctionalTest.java, src/main/resources/db/migration/common/V1_333__insert_security_groups.sql, src/main/resources/db/migration/postgres/V1_333_1__insert_security_groups.sql, src/main/resources/db/migration/postgres/V1_333_2__insert_security_groups.sql, src/main/resources/db/migration/postgres/V1_333_3__insert_security_groups.sql
https://tools.hmcts.net/jira/browse/DMP-3448
=> DMP-3448 - populate security Groups

src/main/resources/openapi/retentions.yaml
https://tools.hmcts.net/jira/browse/DMP-3638
Fixing retentions swagger.
```
[ ] Yes
[ ] No
```
=> DMP-3638 Minor summary changes on retentions swagger doc

src/functionalTest/java/uk/gov/hmcts/darts/dailylist/DailylistFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/main/resources/db/migration/common/V1_334__insert_user_accounts.sql, src/main/resources/db/migration/local/V1_334_5__insert_user_accounts.sql, src/main/resources/db/migration/local/afterMigrate.sql, src/main/resources/db/migration/postgres/V1_334_1__insert_user_accounts.sql, src/main/resources/db/migration/postgres/V1_334_2__insert_user_accounts.sql, src/main/resources/db/migration/postgres/V1_334_3__insert_user_accounts.sql, src/main/resources/db/migration/postgres/V1_334_4__insert_user_accounts.sql
https://tools.hmcts.net/jira/browse/DMP-3628
=> DMP-3628 - add System User Accounts

jitpack.yml
N/A
Jitpack config that allows the project to build with java 21.
```
[ ] Yes
[x] No
```
=> Add new jitpack config to refer to java 21

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
DMP-3470
Add some logs for dynatrace panels
```
[ ] Yes
[x] No
```
=> dmp-3470: improve ats logs for dynatrace

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRetentionEventDateProcessorIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArmRetentionEventDateCalculatorImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmApiServiceImpl.java
DMP-3449
Added some improvements on ARM's downloadBlob & UpdateMetadata endoints
```
[ ] Yes
[x] No
```
=> dmp-3449: arm downloadblob and updatemetadata improvements

src/main/resources/db/migration/postgres/V1_336__insert_user_account_security_groups.sql
https://tools.hmcts.net/jira/browse/DMP-3658
=> DMP-3658 - populate security_group_user_account_ae

src/main/resources/db/migration/postgres/V1_337_1__add_4_new_courthouses.sql, src/main/resources/db/migration/postgres/V1_337_2__add_4_new_courthouses.sql, src/main/resources/db/migration/postgres/V1_337_3__add_4_new_courthouses.sql, src/main/resources/db/migration/postgres/V1_337__add_4_new_courthouses.sql
https://tools.hmcts.net/jira/browse/DMP-3664
```sql
SELECT ch.cth_id, ch.courthouse_name, ch.display_name, reg.region_name, sg.group_name, sg.display_name  
FROM darts.courthouse ch, darts.courthouse_region_ae chr, darts.region reg, darts.security_group_courthouse_ae sgc, darts.security_group sg
where ch.cth_id = chr.cth_id
and chr.reg_id = reg.reg_id
and ch.cth_id = sgc.cth_id
and sgc.grp_id= sg.grp_id
and ch.cth_id >151
ORDER BY cth_id, sg.group_name
```
=> DMP-3664 - Add 4 new courthouses

src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityGroupFunctionalTest.java, src/main/resources/db/migration/common/V1_344_3__v71_3.sql, src/main/resources/db/migration/common/V1_344__v71_3.sql, src/main/resources/db/migration/postgres/V1_344_1__v71_3.sql, src/main/resources/db/migration/postgres/V1_344_2__v71_3.sql
https://tools.hmcts.net/jira/browse/DMP-3661
=> DMP-3661 - add unique constraint on security_group(group_name)

src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/RemoveDuplicateEventsProcessorImpl.java, src/test/java/uk/gov/hmcts/darts/event/service/impl/RemoveDuplicateEventsProcessorImplTest.java
Using created_ts to sort events
https://tools.hmcts.net/jira/browse/DMP-3365
```
[ ] Yes
[x] No
```
=> DMP-3365: Using created_ts to sort events

src/main/java/uk/gov/hmcts/darts/arm/component/impl/AutomatedTaskProcessorFactoryImpl.java, src/main/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentBatchProcessorImpl.java, src/test/java/uk/gov/hmcts/darts/arm/component/impl/UnstructuredToArmProcessorFactoryTest.java, src/test/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentBatchProcessorImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3720
=> DMP-3720 fixed 'caseDocumentGenerationDays' property not being populated

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioMetadataIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/entity/MediaEntity.java, src/main/resources/db/migration/common/V1_349__v71_add_media.is_current.sql, src/main/resources/db/migration/postgres/V1_349_1__v71_add_media.is_current.sql, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3704
=> DMP-3704 - set isCurrent flag when receiving new audio

src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionDocumentRepository.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java
DMP-3594
Set requested by field when transcription request submitted
```
[ ] Yes
[x] No
```
=> DMP-3594: Set requested by field when transcription request submitted

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/MediaControllerAdminPostMediaIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/exception/AudioApiError.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/GetAdminMediaResponseMapper.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/main/java/uk/gov/hmcts/darts/audio/validation/MediaHideOrShowValidator.java, src/main/resources/openapi/audio.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplAdminMediaSearchTest.java
=> DMP-3746: Add support for marking media for deletion

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceGivenBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceTest.java, src/main/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileZipGeneratorHelperImpl.java, src/main/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileZipGeneratorImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioTransformationService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/OutboundFileZipGeneratorHelperImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3748
PR includes some cleanup
```
[ ] Yes
[x ] No
```
=> DMP-3748 Populate empty fields in audio file download ReadMe file

src/main/resources/db/migration/postgres/V1_350_1__add_trigram_indexes.sql, src/main/resources/db/migration/postgres/V1_350_2__add_trigram_indexes.sql, src/main/resources/db/migration/postgres/V1_350_3__add_trigram_indexes.sql, src/main/resources/db/migration/postgres/V1_350_4__add_trigram_indexes.sql, src/main/resources/db/migration/postgres/V1_350_5__add_trigram_indexes.sql
=> make new indexes instead of replacing old ones

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesIntTest.java, src/integrationTest/resources/tests/arm/service/ArmBatchResponseFilesProcessorTest/InvalidResponses/UploadFile.rsp, src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArmResponseFilesProcessSingleElementImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmBatchProcessResponseFilesImpl.java
DMP-3626
- Log ARM error description in DB.
- Update Ingestion date in EOD after successful processing.
```
[ ] Yes
[x] No
```
=> dmp-3626: ARM Pull response log error in DB

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioMetadataIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetMetadataIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioService.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioTransformationService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/MediaRepository.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/MediaTestData.java
https://tools.hmcts.net/jira/browse/DMP-3705
=> DMP-3705 - only get audio that isCurrent

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetMarkedForDeletionIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/repository/ObjectAdminActionRepositoryTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/ObjectAdminActionStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/ObjectHiddenReasonStub.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/AdminMarkedForDeletionMapper.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/AdminMediaMapper.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/CourthouseMapper.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/CourtroomMapper.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/ObjectActionMapper.java, src/main/java/uk/gov/hmcts/darts/audio/service/AdminMediaService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/ObjectAdminActionRepository.java, src/main/resources/openapi/audio.yaml, src/test/java/uk/gov/hmcts/darts/audio/mapper/ObjectActionMapperTest.java
Implement `GET /admin/medias/marked-for-deletion`.
```
[ ] Yes
[x] No
```
=> DMP-2894: Implement GET /admin/medias/marked-for-deletion

infrastructure/test.tfvars, infrastructure/variables.tf
=> feat-psql-sku

infrastructure/test.tfvars
=> feat-psql-sku-version

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/InboundAnnotationTranscriptionDeleterProcessorImplTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/service/UnstructuredAnnotationTranscriptionDeleterProcessorImplTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepositoryTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/ExternalObjectDirectoryStub.java, src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java
https://tools.hmcts.net/jira/browse/DMP-3292
Correction to fetch eod that map to transcription or annotation
NOTE: Because this is common code this also fixes the same issue with https://tools.hmcts.net/jira/browse/DMP-3293
```
[ ] Yes
[x ] No
```
=> DMP-3292: Make correction to only match on either annotation or transcription

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRetentionEventDateProcessorIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArmRetentionEventDateCalculatorImpl.java
https://tools.hmcts.net/jira/browse/DMP-3779
Prevent confidence score null pointer by not updating in the event of null score.
```
[ ] Yes
[ x] No
```
=> DMP-3779 - Prevent null pointer on confidence score

src/main/java/uk/gov/hmcts/darts/common/repository/TransformedMediaRepository.java
DMP-3651
Fix Your audio table to use displayName
```
[ ] Yes
[x] No
```
=> DMP-3651: Fix Your audio table to use displayName

Jenkinsfile_CNP, src/integrationTest/java/uk/gov/hmcts/darts/common/service/RetrieveCoreObjectServiceIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/dailylist/service/DailyListProcessorTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/HearingRepository.java, src/main/java/uk/gov/hmcts/darts/common/service/impl/RetrieveCoreObjectServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-3010
=> DMP-3010 - make case numbers case-sensitive

build.gradle
=> sonar line coverage

bin/generateSingleArmILResponses.sh
DMP-3626
Added script to generate ARM IL response files
```
[ ] Yes
[ x] No
```
=> DMP-3626 Added script to generate ARM IL response files

src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationDeleteTest.java, src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationGetTest.java, src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationPostTest.java, src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationUploadServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/annotation/repository/AnnotationDocumentRepositoryIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/retention/service/ApplyRetentionCaseAssociatedObjectsProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/GenerateCaseDocumentProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBase.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/TransactionalUtil.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseRetrieval.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsPersistence.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/EntityGraphPersistence.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/AnnotationDocumentTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/AnnotationTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/CaseTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/HearingTestData.java
Re-enable annotation tests
https://tools.hmcts.net/jira/browse/DMP-3821
```
[ ] Yes
[x] No
```
=> DMP-3821: Re-enable annotation tests

src/main/java/uk/gov/hmcts/darts/common/service/CreateCoreObjectService.java, src/main/java/uk/gov/hmcts/darts/common/service/RetrieveCoreObjectService.java, src/main/java/uk/gov/hmcts/darts/common/service/impl/CreateCoreObjectServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/service/impl/RetrieveCoreObjectServiceImpl.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListUpdater.java, src/test/java/uk/gov/hmcts/darts/common/service/impl/CreateCoreObjectServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListUpdaterTest.java
DMP-3323
Fix unique constraint violations during event processing
```
[ ] Yes
[x] No
```
=> DMP-3323: Fix unique constraint violations during event processing - Part 1

src/main/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityGroupController.java, src/main/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityRoleController.java
https://tools.hmcts.net/jira/browse/DMP-3809
Second PR for DMP-3809 which addresses the issues mentioned by Hemanta in one of the ticket comments (I forgot to address those in my previous PR) 
```
[ ] Yes
[ x] No
```
=> DMP-3809 updated permissions for SuperUser user

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImplTest.java
DMP-3777
Remove the redundant hardcoding of isarchive
```
[ ] Yes
[x] No
```
=> dmp-3777: remove redundant hardcoding of isarchive

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml
https://tools.hmcts.net/jira/browse/DMP-3774
```
[ ] Yes
[ x] No
```
=> DMP-3774 disabled sending notifications in ATS_MODE

src/main/java/uk/gov/hmcts/darts/event/service/handler/base/EventHandlerBase.java
https://tools.hmcts.net/jira/browse/DMP-3873
Move recordEvent method into try block so that the courthouse not found error used for Dynatrace is logged.
```
[ ] Yes
[x ] No
```
=> DMP-3873 Courthouse not found Dynatrace fix

src/main/resources/db/migration/common/V1_374__remove_envers_constraints.sql
https://tools.hmcts.net/jira/browse/DMP-3860
=> DMP-3860 - remove column length limits from envers tables

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsPersistence.java, src/integrationTest/resources/tests/cases/CaseControllerTest/casesPostEndpoint/requestBodyForCaseWithType.json, src/main/java/uk/gov/hmcts/darts/cases/mapper/CasesMapper.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/resources/openapi/cases.yaml, src/test/java/uk/gov/hmcts/darts/cases/mapper/CasesMapperTest.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/CaseTestData.java
https://tools.hmcts.net/jira/browse/DMP-3007
=> DMP-3007 - add case Type parameter

src/integrationTest/java/uk/gov/hmcts/darts/arm/helper/UnstructuredToArmHelperIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/UnstructuredToArmBatchProcessorIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/helper/UnstructuredToArmHelper.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/UnstructuredToArmBatchProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java, src/main/resources/application-local.yaml, src/main/resources/db/migration/local/afterMigrate.sql, src/test/java/uk/gov/hmcts/darts/arm/service/UnstructuredToArmBatchProcessorTest.java, src/test/java/uk/gov/hmcts/darts/arm/service/UnstructuredToArmProcessorImplTest.java
=> Dmp 3887.unstructured to arm fix

README.md, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AutomatedTaskServiceTest.java, src/main/resources/db/migration/common/V1_375__update_automated_tasks_default_values.sql
https://tools.hmcts.net/jira/browse/DMP-3825
Updated the automated tasks cron expressions so that they are less likely to interfere with one another and added/changed the batch size
```
[ ] Yes
[x ] No
```
=> Dmp 3825 tune automated tasks

src/main/resources/db/migration/common/V1_376__disable_automated_tasks_for_go_live.sql
https://tools.hmcts.net/jira/browse/DMP-3886
Added migration to disable certain automated taks for go live
```
[ ] Yes
[x ] No
```
=> DMP-3886 Ensure relevant automated tasks are disabled/enabled at go live

src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java
https://tools.hmcts.net/jira/browse/DMP-3345
Amending the permissions of `/dailylists/run` to be `SUPER_ADMIN` only.
```
[ ] Yes
[ ] No
```
=> DMP-3345 Amending /dailylists/run to SUPER_ADMIN

src/main/java/uk/gov/hmcts/darts/common/repository/CourtroomRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/HearingRepository.java, src/main/java/uk/gov/hmcts/darts/common/service/impl/CourtroomCommonServiceImpl.java
DMP-3827
courtroom_name searches need to be case-sensitive
```
[ ] Yes
[x] No
```
=> DMP-3827: courtroom_name searches need to be case-sensitive

src/main/java/uk/gov/hmcts/darts/event/helper/DarNotifyAsyncHelper.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/DarNotifyServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-3872
=> DMP-3872 - change point where darNotify is async

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestNonAccessedCountIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/MediaRequestStub.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/MediaRequestTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/Persistable.java
=> DMP-3821: Renable remaining audio tests

src/main/java/uk/gov/hmcts/darts/util/AzureCopyUtil.java
DMP-3917
Remove access tier flag from azcopy
```
[ ] Yes
[x] No
```
=> dmp-3917: remove access tier flag from azcopy

src/main/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentBatchProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentForRetentionDateBatchProcessorImpl.java
https://tools.hmcts.net/jira/browse/DMP-3884
Added logging to show how many case documents are being generated against the batch size
```
[ ] Yes
[x ] No
```
=> DMP-3884 Add Batch logic on Automated Task - Case Document Generation

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdvancedSearchTempTest.java, src/main/java/uk/gov/hmcts/darts/cases/helper/AdvancedSearchRequestHelper.java
https://tools.hmcts.net/jira/browse/DMP-3875
=> DMP-3875 - add hearing_is_Actual criteria to advanced search

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3882
its probably doesn't need to be set on the linkAudioToHearingByEvent method, but doing it for belt and braces.
=> DMP-3882 - Set hearing_is_actual when audio is received.

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetAdminMediasIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/GetAdminMediaResponseMapper.java, src/main/resources/openapi/audio.yaml, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3903
=> DMP-3903 - add is_hidden to GET /admin/medias response

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventControllerGetEventMappingByIdTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventControllerGetEventMappingsTest.java, src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java
https://tools.hmcts.net/jira/browse/DMP-3907
- this is required when viewing event details on the portal
```
[ ] Yes
[ ] No
```
=> DMP-3907 Allowing SUPER_USER access to view event mappings

src/integrationTest/java/uk/gov/hmcts/darts/cases/repository/CaseRepositoryIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CloseOldCasesProcessorTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AutomatedTaskServiceTest.java, src/main/java/uk/gov/hmcts/darts/arm/component/AutomatedTaskProcessorFactory.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/AutomatedTaskProcessorFactoryImpl.java, src/main/java/uk/gov/hmcts/darts/cases/service/CloseOldCasesProcessor.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CloseOldCasesProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/CloseOldCasesAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImpl.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/ManualTaskService.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CloseOldCasesProcessorImplTest.java, src/test/java/uk/gov/hmcts/darts/task/runner/impl/CloseOldCasesAutomatedTaskTest.java
https://tools.hmcts.net/jira/browse/DMP-3885
Added batching to CloseOldCases automated task
```
[ ] Yes
[x ] No
```
=> Dmp 3885 add batch logic to automated task close old case

src/main/java/uk/gov/hmcts/darts/task/runner/AutoloadingAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/AbstractLockableAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/ApplyRetentionAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/ApplyRetentionCaseAssociatedObjectsAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/ArmRetentionEventDateCalculatorAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/BatchCleanupArmResponseFilesAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/CleanupArmResponseFilesAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/CleanupCurrentEventTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/CloseOldCasesAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/CloseUnfinishedTranscriptionsAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/DailyListAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/ExternalDataStoreDeleterAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/GenerateCaseDocumentAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/GenerateCaseDocumentForRetentionDateAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/InboundAnnotationTranscriptionDeleterAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/InboundAudioDeleterAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/InboundToUnstructuredAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/OutboundAudioDeleterAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/ProcessArmResponseFilesAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/ProcessDailyListAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/RemoveDuplicatedEventsAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/UnstructuredAnnotationTranscriptionDeleterAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/UnstructuredAudioDeleterAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/UnstructuredToArmAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImplTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/DMP-3933)
Refactor automated task service to use spring dependency injection
```
[ ] Yes
[X] No
```
=> DMP-3933 - (Dev Only) -> Refactor automated task service to use spring dependency injection

src/main/java/uk/gov/hmcts/darts/retention/model/CaseRetentionConfidenceReason.java, src/test/java/uk/gov/hmcts/darts/retention/model/CaseRetentionConfidenceReasonTest.java
https://tools.hmcts.net/jira/browse/DMP-3544
Added confidence reason json object
```
[ ] Yes
[ x] No
```
=> DMP-3544 RCC - Confidence Reason - JSON structure

src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTaskITest.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionStatusEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionWorkflowEntity.java, src/test/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntityTest.java, src/test/java/uk/gov/hmcts/darts/common/entity/TranscriptionWorkflowEntityTest.java
>[Jira](https://centralgovernmentcgi.atlassian.net/browse/DMP-3023)
If a transcript request is mid workflow when a case expires then the workflow will automatically be moved to closed.
```
[ ] Yes
[X] No
```
=> DMP-3023 - Close active transcript workflow when case expires

src/main/java/uk/gov/hmcts/darts/event/helper/DarNotifyAsyncHelper.java
N/A
- to prevent confusion around the success or failure of the notification
- this is only sending the request to the DARTS gateway and reporting back on that
```
[ ] Yes
[ ] No
```
=> Amending DAR notification log messages

src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImpl.java, src/main/resources/application.yaml
Removed allow-automated-tasks in favour for automated-tasks-pod
```
[ ] Yes
[X] No
```
=> Removed allow-automated-tasks in favour for automated-tasks-pod

src/main/java/uk/gov/hmcts/darts/retention/mapper/CaseRetentionConfidenceReasonMapper.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionCaseAssociatedObjectsProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionCaseAssociatedObjectsSingleCaseProcessorImpl.java, src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java, src/test/java/uk/gov/hmcts/darts/retention/mapper/CaseRetentionConfidenceReasonMapperTest.java, src/test/java/uk/gov/hmcts/darts/retention/model/CaseRetentionConfidenceReasonTest.java, src/test/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionCaseAssociatedObjectsSingleCaseProcessorImplTest.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/ExternalObjectDirectoryTestData.java
https://tools.hmcts.net/jira/browse/DMP-3536
Added code to calculate retention confidence score and reason for associated objects
```
[ ] Yes
[ x] No
```
=> Dmp 3536 calculate confidence for associated object

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventSearchControllerTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java, src/main/java/uk/gov/hmcts/darts/event/mapper/EventSearchMapper.java, src/main/java/uk/gov/hmcts/darts/event/model/EventSearchResult.java, src/main/resources/openapi/event.yaml, src/test/java/uk/gov/hmcts/darts/event/mapper/EventSearchMapperTest.java
DMP-3915
Add anonymisation details for Event search operation
```
[ ] Yes
[x] No
```
=> dmp-3915: Add Anonymisation details in Event Search operation

src/main/java/uk/gov/hmcts/darts/retention/enums/RetentionPolicyEnum.java, src/main/resources/db/migration/common/V1_380__added_additional_retention_policy_type.sql, src/main/resources/db/migration/postgres/V1_380_1__added_additional_retention_policy_type.sql
https://tools.hmcts.net/jira/browse/DMP-3947
=> DMP-3947 - add new archive retention policies

src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArmRetentionEventDateCalculatorImpl.java
https://tools.hmcts.net/jira/browse/DMP-3890
```
[ ] Yes
[x ] No
```
=>  DMP-3890: logging EOD id

src/main/java/uk/gov/hmcts/darts/common/repository/CourtLogEventRepository.java
https://tools.hmcts.net/jira/browse/DMP-3969
https://tools.hmcts.net/jira/browse/DMP-3827
=> DMP-3969/DMP-3827 - AddAudio slow due to not using index.

src/main/resources/db/reference/delete/delete_case_data.sql
N/A
- keeping the list of "prod" databases
- keeping YORK courtrooms 1, 2 and 199
- keeping SWANSEA courtrooms 31 and 32
```
[ ] Yes
[ ] No
```
=> Updating DB delete script for courthouses/courtrooms

src/main/java/uk/gov/hmcts/darts/task/runner/impl/AbstractLockableAutomatedTask.java
Update the AbstractLockableAutomatedTask.run() method to fail on a specific task.
The specific task is the `ProcessDailyList` and this is temporary and will be removed as soon as the test is verified.
```
[ ] Yes
[ ] No
[x] Potentially temporary
```
=> DMP-2666: Temporary change to automated tasks for testing of the DMP-2666 ticket

src/main/java/uk/gov/hmcts/darts/task/runner/impl/AbstractLockableAutomatedTask.java
Revert: DMP-2666: Temporary change to automated tasks for testing of the DMP-2666 ticket (#2046)
```
[ ] Yes
[x] No
```
=> Revert #2046

src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImpl.java
https://tools.hmcts.net/jira/browse/DMP-4002
Reworked log message so its clearer
```
[ ] Yes
[x ] No
```
=> DMP-4002 Reword logging in UserIdentityImpl.userHasGlobalAccess so its clear if user has guid but no email address

src/functionalTest/java/uk/gov/hmcts/darts/arm/ArmServiceFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/testutil/ArmTestUtil.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/config/ArmDataManagementConfiguration.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmBatchProcessResponseFilesImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3984
Implemented continuation token so that it iterates until batch size is met
```
[ ] Yes
[x ] No
```
=> DMP-3984 (Dev Only) Fully implement continuation token

src/integrationTest/java/uk/gov/hmcts/darts/cases/repository/CaseRepositoryIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/dailylist/controller/DailyListPostControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/dailylist/service/DailyListProcessorTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventSearchControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/AdminEventsSearchGivensBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsGetControllerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/retention/service/ApplyRetentionCaseAssociatedObjectsProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/UnstructuredToArmBatchProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBase.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/UnstructuredToArmBatchProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/DailyListProcessor.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/ProcessDailyListOnDemandTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/AutomatedOnDemandTask.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/dailylist/controller/DailyListProcessEndpointTest.java, src/test/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListProcessorImplTest.java, src/test/java/uk/gov/hmcts/darts/dailylist/service/impl/ProcessAllDailyListsTest.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/AwaitabilityUtil.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/MediaIdMatcher.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/CaseTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/HearingTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/MediaTestData.java
https://tools.hmcts.net/jira/browse/DMP-4001
Reenable the previously commented out integration tests
```
[ ] Yes
[x] No
```
=> DMP-4001: Reenable tests

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java, src/main/java/uk/gov/hmcts/darts/event/mapper/EventMapper.java, src/main/resources/openapi/event.yaml, src/test/java/uk/gov/hmcts/darts/event/mapper/EventMapperTest.java
N/A
Adding `created_at` to `GET /admin/events/{event_id}` response 
```
[ ] Yes
[ ] No
```
=> Adding "created_at" to admin get event endpoint

src/main/java/uk/gov/hmcts/darts/task/api/AutomatedTaskName.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AdminAutomatedTasksServiceImpl.java, src/test/java/uk/gov/hmcts/darts/task/service/impl/AdminAutomatedTasksServiceImplTest.java
>[Jira](https://tools.hmcts.net/jira/browse/DMP-4010)
Added support for dynamic AutomatedTask enablement based on Spring SpEL
```
[ ] Yes
[X] No
```
=> DMP-4010 - Added support for dynamic AutomatedTask enablement based on Spring SpEL

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioMetadataIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/helper/AudioAsyncHelper.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioUploadService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3963
=> DMP-3963 - add media Linked case entries to addAudio, and make async

src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-3984
Added more logs for continuation token
```
[ ] Yes
[ x] No
```
=> DMP-3984 Add more logging

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioMetadataIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java
=> fix Flakey tests

charts/darts-api/values.stg.template.yaml
Fixed issue with functional tests on master
```
[ ] Yes
[X] No
```
=> Fixed issue with functional tests on master

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioMetadataIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/AudioAsyncService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioAsyncServiceImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListUpdater.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioAsyncServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListUpdaterTest.java, src/test/resources/Tests/dailylist/DailyListUpdaterTest/handlesNoTimeMarkingNote.json
https://tools.hmcts.net/jira/browse/DMP-4023
=> DMP-4023 - dailylist - default hearing to 9am if not provided

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CloseOldCasesProcessorTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandlerTest.java, src/integrationTest/java/uk/gov/hmcts/darts/retention/controller/RetentionControllerPostRetentionIntTest.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CloseOldCasesProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StopAndCloseHandler.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImpl.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CloseOldCasesProcessorImplTest.java, src/test/java/uk/gov/hmcts/darts/retention/service/impl/RetentionPostServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4027
Updated the court case ret_conf_updated_ts field when retention is updated
```
[ ] Yes
[ x] No
```
=> DMP-4027 RCC - When 'ApplyRetention' automated task runs, update the Court Case ret_conf_updated_ts field

src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/HandleOAuthCodeIntTest.java, src/main/java/uk/gov/hmcts/darts/authentication/controller/AuthenticationController.java, src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AbstractUserController.java, src/main/java/uk/gov/hmcts/darts/authentication/dao/AzureDao.java, src/main/java/uk/gov/hmcts/darts/authentication/dao/impl/AzureDaoImpl.java, src/main/java/uk/gov/hmcts/darts/authentication/service/AuthenticationService.java, src/main/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImpl.java, src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserControllerTest.java, src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserControllerTest.java, src/test/java/uk/gov/hmcts/darts/authentication/dao/impl/AzureDaoImplTest.java, src/test/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImplTest.java
=> Adding redirect_uri query param to handleoauthcode endpoint

.github/workflows/close-pr.yml, .github/workflows/on-pr.yml, Jenkinsfile_CNP, bin/ci/db-pr-base-to-pr.sh, bin/db-stg-to-pr-base.sh, bin/db-stg-to-pr.sh, charts/darts-api/Chart.yaml, charts/darts-api/values.dev.template.yaml, src/main/resources/application-dev.yaml, src/main/resources/db/migration/dev/afterMigrate.sql
N/A
Improvements to the dev environment
- adding DARTS portal instance
- whitelist darts portal instance on internal/external ADs
- don't send logs with app insights
- template in place for DB restoring from a base schema
```
[ ] Yes
[ ] No
```
=> Dev environment improvements

Jenkinsfile_CNP, src/main/resources/application-dev.yaml
=> Restoring dev DB data from PR base schema

charts/darts-api/Chart.yaml, charts/darts-api/values.dev.template.yaml, charts/darts-api/values.stg.template.yaml
N/A
- to see if it's affecting staging pipeline deployments
```
[ ] Yes
[ ] No
```
=> Removing DARTS portal dev deployment

src/integrationTest/java/uk/gov/hmcts/darts/task/service/AdminGetAutomatedTaskServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AdminGetAutomatedTasksByIdTest.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTasksMapper.java, src/main/resources/openapi/tasks.yaml, src/test/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTasksMapperTest.java
DMP-3978
Return Batch Size in GET /automated-tasks/{task_id}
```
[ ] Yes
[x] No
```
=> DMP-3978: Return Batch Size in GET /automated-tasks/{task_id}

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImplTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java
https://tools.hmcts.net/jira/browse/DMP-4068
- using sub-queries in the select clause, rather that from
- to prevent duplicate rows appearing
- adding tests for `getTranscriptRequests` query
- adding tests for getTranscriberTranscripts query to verify it doesn't have the same problem
```
[ ] Yes
[ ] No
```
=> DMP-4068 Changes to transcriber SQL queries

charts/darts-api/Chart.yaml, charts/darts-api/values.dev.template.yaml, charts/darts-api/values.stg.template.yaml
N/A
- adding 0 replica deployment to staging in the hope it doesn't fail
```
[ ] Yes
[ ] No
```
=> Re-introducing DARTS portal deployment on dev

src/integrationTest/java/uk/gov/hmcts/darts/casedocument/service/GenerateCaseDocumentForRetentionDateBatchProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/GenerateCaseDocumentProcessorIntTest.java, src/main/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentSingleCaseProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionCaseAssociatedObjectsSingleCaseProcessorImpl.java, src/test/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentSingleCaseProcessorImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4055
Updated the case document generation to also reset retention data
```
[ ] Yes
[x ] No
```
=> DMP-4055 Retention Attributes Not Applied to Media, Annotations, Transcriptions, and Case Document

src/main/resources/db/migration/common/V1_393__update_task_names.sql
Update automated task names to align with [DMP-3807](https://tools.hmcts.net/jira/browse/DMP-3807).
Note: casing differs from the ticket to better align with exsiting records in the automated_task table.
```
[ ] Yes
[X] No
```
=> DMP-3807: Update automated task names

src/main/java/uk/gov/hmcts/darts/common/repository/CourtLogEventRepository.java
>[Jira](https://tools.hmcts.net/jira/browse/DMP-4203)
The code has been updated to simplify the query used in the `CourtLogEventRepository` interface. This change enhances the readability and efficiency of the database query used to retrieve court log events based on specific criteria.
- **Simplified Query**: The query now directly accesses the `courtroom` and `courthouse` properties of the `EventEntity`, eliminating unnecessary joins with other entities.
- **Improved Readability**: The updated query is cleaner and easier to understand, making it more maintainable for future developers.
- **Functionality Preserved**: The functionality of retrieving court log events by courthouse and courtroom within a specified time range remains unchanged.
**Does this PR introduce a breaking change?** …
=> DMP-4203: Performance - slow running sql in AddAudio

src/integrationTest/java/uk/gov/hmcts/darts/task/service/OutboundAudioDeleterProcessorTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/TransformedMediaRepository.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/MediaRequestTestData.java
>[Jira](https://tools.hmcts.net/jira/browse/DMP-4165)
As discussed in call with [~thurai.sashikumar] & [~leanne.jacobs], If a media is hidden or deleted, there shouldnt be any logic around expiring Transformed media. 
Expiring or Deleting a transformed media will be further discussed and new design/tickets will be created.
Revert the changes done under DMP-3201.
```
[ ] Yes
[X] No
```
=> DMP-4165: Revert DMP-3201

src/integrationTest/java/uk/gov/hmcts/darts/arm/client/ArmRpoClientIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArpRpoApiGetStorageAccountsIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/client/ArmRpoClient.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/StorageAccountRequest.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/StorageAccountResponse.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApi.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetRecordManagementMatterTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetStorageAccountsTest.java, src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4134
Added ARM RPO getStorageAccounts implementation
```
[ ] Yes
[x ] No
```
=> Dmp 4134 armrpo integrate get storage accounts

src/main/resources/db/migration/common/V1_405__remove_dmadmin_account.sql
https://tools.hmcts.net/jira/browse/DMP-4259
=> DMP-4259 - remove migration user

src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiAddAsyncSearchIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/repository/ArmAutomatedTaskRepositoryTest.java, src/main/java/uk/gov/hmcts/darts/arm/client/ArmRpoClient.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ArmAsyncSearchResponse.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/AddAsyncSearchRequestGenerator.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApi.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/ArmAutomatedTaskRepository.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/component/impl/AddAsyncSearchRequestGeneratorTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiAddAsyncSearchTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetProfileEntitlementsTest.java
Implement the ARM RPO addAsyncSearch service layer.
This PR includes the corresponding Feign client which will be integration tested as part of wider ticket https://tools.hmcts.net/jira/browse/DMP-4143.
```
[ ] Yes
[x] No
```
=> DMP-3616: Implement addAsyncSearch for ARM RPO

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerSearchPostTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/CourthouseRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/CourtroomRepository.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/CourthouseTestData.java
https://tools.hmcts.net/jira/browse/DMP-4267
This PR fixes an issue whereby when a user searches for a case using a courthouse and courtroom where the courthouse ID does not match the courthouse display name, then the case is not found. 
```
[ ] Yes
[x ] No
```
=> DMP-4267 Find courthouse by display name

src/integrationTest/java/uk/gov/hmcts/darts/arm/client/ArmRpoClientIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiSaveBackgroundSearchIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArpRpoApiGetStorageAccountsIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/client/ArmRpoClient.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ArmAsyncSearchResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/BaseRpoResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ExtendedProductionsByMatterResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ExtendedSearchesByMatterResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/IndexesByMatterIdResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/MasterIndexFieldByRecordClassSchemaResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ProfileEntitlementResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/RecordManagementMatterResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/SaveBackgroundSearchRequest.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/SaveBackgroundSearchResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/StorageAccountResponse.java, src/main/java/uk/gov/hmcts/darts/arm/config/ArmRpoConfigurationProperties.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiSaveBackgroundSearchTest.java
https://tools.hmcts.net/jira/browse/DMP-4137
Added functionality to call the ARM RPO SaveBackgroundSearch api
```
[ ] Yes
[ x] No
```
=> Dmp 4137 armrpo integrate save background search

src/integrationTest/java/uk/gov/hmcts/darts/audio/repository/MediaRepositoryIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/retention/service/ApplyRetentionCaseAssociatedObjectsProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsPersistence.java, src/main/java/uk/gov/hmcts/darts/common/repository/MediaRepository.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionCaseAssociatedObjectsSingleCaseProcessorImpl.java, src/test/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionCaseAssociatedObjectsSingleCaseProcessorImplTest.java
https://tools.hmcts.net/jira/browse/DMP-3998
Added handling of linked media
```
[ ] Yes
[ x] No
```
=> DMP-3998 Enhance ApplyRetentionCaseAssociatedObjects task to handle versioned media

src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiAddAsyncSearchIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiGetIndexesByMatterIdIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoGetProfileEntitlementsIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArpRpoApiGetMasterIndexFieldByRecordClassSchemaIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArpRpoApiGetRecordManagementMatterIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArpRpoApiGetStorageAccountsIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/client/ArmRpoClient.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/IndexesByMatterIdRequest.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/IndexesByMatterIdResponse.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApi.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiAddAsyncSearchTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetIndexesByMatterIdTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetMasterIndexFieldByRecordClassSchemaTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetProfileEntitlementsTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetRecordManagementMatterTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetStorageAccountsTest.java
https://tools.hmcts.net/jira/browse/DMP-4133
Added functionality to call the ARM RPO endpoint getIndexesByMatterId
```
[ ] Yes
[x ] No
```
=> DMP-4133 (Dev Only) ARM RPO - Integrate getIndexesByMatterId

src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiCreateExportBasedOnSearchResultsTableIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/client/ArmRpoClient.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ArmAsyncSearchResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/BaseRpoResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/CreateExportBasedOnSearchResultsTableRequest.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/CreateExportBasedOnSearchResultsTableResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ExtendedSearchesByMatterResponse.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/IndexesByMatterIdResponse.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiCreateExportBasedOnSearchResultsTableTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiSaveBackgroundSearchTest.java
https://tools.hmcts.net/jira/browse/DMP-4138
Created ARM RPO API call to createExportBasedOnSearchResultsTable
```
[ ] Yes
[ x] No
```
=> DMP-4138 (Dev Only) ARM RPO - Integrate createExportBasedOnSearchResultsTable

src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiRemoveProductionIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/client/ArmRpoClient.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/RemoveProductionRequest.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/RemoveProductionResponse.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiRemoveProductionTest.java
https://tools.hmcts.net/jira/browse/DMP-4142
Implemented the ARM RPO remove production API.
```
[ ] Yes
[ x] No
```
=> Dmp 4142 armrpo integrate remove production

src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiGetExtendedProductionsByMatterIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/client/ArmRpoClient.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ExtendedProductionsByMatterResponse.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/GetExtendedProductionsByMatterRequestGenerator.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApi.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/component/impl/GetExtendedProductionsByMatterRequestGeneratorTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetExtendedProductionsByMatterTest.java
DMP-4139 : Integrate Arm Rpo getExtendedProductionsByMatter endpoint
The endpoint returns ProductionId using the matterId. 
```
[ ] Yes
[x] No
```
=> DMP-4139 : Arm Rpo Integrate getExtendedProductionsByMatter

src/main/java/uk/gov/hmcts/darts/audio/service/impl/InboundAudioDeleterProcessorImpl.java
https://tools.hmcts.net/jira/browse/DMP-4241
=> DMP-4241 - fix logging

src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiDownloadProductionIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/client/ArmRpoClient.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApi.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java, src/main/java/uk/gov/hmcts/darts/common/datamanagement/component/impl/FileBasedDownloadResponseMetaData.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiDownloadProductionTest.java
https://tools.hmcts.net/jira/browse/DMP-4141
Created functionality to call ARM RPO downloadProduction API
```
[ ] Yes
[ x] No
```
=> DMP-4141 (Dev Only) ARM RPO - Integrate downloadProduction

src/main/java/uk/gov/hmcts/darts/task/api/AutomatedTaskName.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/ArmRpoExecutionDetailTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/ArmRpoStateEntityTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/ArmRpoStatusEntityTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/PersistableFactory.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/builder/TestArmRpoExecutionDetailEntity.java
https://tools.hmcts.net/jira/browse/DMP-4144
Shared test data
```
[ ] Yes
[x ] No
```
=> DMP-4144 ARM RPO - Integrate all Endpoints for ARMRPOPollAutomatedTask

docker-compose-local.yml
=> Adding darts-portal to docker-compose-local.yml

src/main/java/uk/gov/hmcts/darts/common/service/impl/DataAnonymisationServiceImpl.java
N/A
Fixing the spelling of "anonymize" to "anonymise"
```
[ ] Yes
[ ] No
```
=> Fixing anonymize spelling

src/main/resources/db/migration/common/V1_415__apply_retention_cron.sql
=> Updated apply retention cron

src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/ProcessArmRpoPendingAutomatedTaskITest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/ProcessE2EArmRpoPendingAutomatedTaskIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AdminGetAutomatedTaskServiceTest.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApi.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/ArmApiService.java, src/main/java/uk/gov/hmcts/darts/arm/service/ArmRpoService.java, src/main/java/uk/gov/hmcts/darts/arm/service/TriggerArmRpoSearchService.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmApiServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/TriggerArmRpoSearchServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/datamanagement/api/DataManagementFacadeImpl.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/ProcessE2EArmRpoPendingAutomatedTask.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiAddAsyncSearchTest.java, src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/arm/service/impl/TriggerArmRpoSearchServiceImplTest.java
Implement ProcessE2EARMRPOPending automated task.
```
[ ] Yes
[x] No
```
=> DMP-4143: Implement ProcessE2EARMRPOPending automated task

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/AbstractArmBatchProcessResponseFilesIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/model/blobs/ArmBatchResponses.java, src/main/java/uk/gov/hmcts/darts/arm/model/blobs/ArmResponseBatchData.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFiles.java, src/main/java/uk/gov/hmcts/darts/common/service/impl/FileOperationServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-3997
Added code to allow for multiple ARM IL response files
```
[ ] Yes
[x ] No
```
=> Dmp 3997 arm response dynamic invalid line files

src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/java/uk/gov/hmcts/darts/hearings/controller/HearingsController.java, src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java
https://tools.hmcts.net/jira/browse/DMP-4374
- currently, only courthouse scoped users can access transcripts
- but global access should be allowed
```
[ ] Yes
[ ] No
```
=> DMP-4374 Setting TRANSLATION_QA role as global access for transcriptions

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetAdminMediasByIdIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/AdminMediaMapper.java, src/main/resources/openapi/audio.yaml
https://tools.hmcts.net/jira/browse/DMP-4270
Added is_current to admin get media by id endpoint
```
[ ] Yes
[x ] No
```
=> DMP-4270 Add Is current to admin get medias by id endpoint

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetAdminMediasIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/mapper/GetAdminMediaResponseMapper.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImpl.java, src/main/resources/openapi/audio.yaml
https://tools.hmcts.net/jira/browse/DMP-4390
As title. The property is required for the an admin portal screen.
```
[ ] Yes
[ ] No
```
=> DMP-4390 Adding "is_current" to the GET /admin/medias endpoint response

build.gradle, config/pmd/main-ruleset.xml
Updated PMD main rules
```
[ ] Yes
[X] No
```
=> Updated PMD main rules

src/main/java/uk/gov/hmcts/darts/arm/service/impl/UnstructuredToArmBatchProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/util/AsyncUtil.java
Added additional logs / timeouts to async process
=> Added additional logs / timeouts to async process

src/main/java/uk/gov/hmcts/darts/arm/client/ArmApiClient.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArmRetentionEventDateCalculatorImpl.java
Added some temporary logs to investigate issue
=> Added some temporary logs to investigate issue

bin/generateBatchArmResponses.sh, src/integrationTest/java/uk/gov/hmcts/darts/arm/service/AbstractArmBatchProcessResponseFilesIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFiles.java
https://tools.hmcts.net/jira/browse/DMP-4256
Added more tests and updated the bash script to set the status in ARM response files. Also added code to delete the response files if they are invalid json
```
[ ] Yes
[ x] No
```
=> DMP-4256 CR and IL files are not getting deleted

src/main/java/uk/gov/hmcts/darts/task/runner/impl/AbstractLockableAutomatedTask.java
https://tools.hmcts.net/jira/browse/DMP-4219
Added logging to show the user email that started the automated task. Also removed isAutomatedTaskInBatchMode as it is not used anymore.
```
[ ] Yes
[x ] No
```
=> Dmp 4219 log automated task user

src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-4466
Added logging to help with debugging the remove production failure
```
[ ] Yes
[x ] No
```
=> DMP-4466 ARM RPO: Remove_production failing

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioMetadataIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioWithMetadataIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4388
- adding test and renaming some others
```
[ ] Yes
[ ] No
```
=> DMP-4388 Removing case list for add audio duplicate check

src/main/java/uk/gov/hmcts/darts/audit/api/AuditActivity.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionServiceImpl.java, src/main/resources/db/migration/common/V1_421__insert_hide_unhide_transcription_audit_activities.sql, src/main/resources/db/migration/common/V1_421__insert_unhide_audio_audit_activities.sql, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionServiceTest.java
https://tools.hmcts.net/jira/browse/DMP-4431
Added auditing for hiding and unhiding transcriptions. The ticket reference and comments from the hide transcription request are added to the additional data column for reference.
```
[ ] Yes
[ x] No
```
=> DMP-4431 Auditing for hiding and unhiding transcriptions

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4253
- returning distinct audios only
- renaming and tweaking the unit tests for the `AdminMediaServiceImpl` class
```
[ ] Yes
[ ] No
```
=> DMP-4253 Return distinct list of medias from GET /admin/medias

bin/dcup, docker-compose-local.yml
N/A
- removing part of `bin/dcup` script that builds local images
```
[ ] Yes
[ ] No
```
=> Using pre-built images in docker-compose-local.yml

src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImpl.java
DMp-4483 - Extra logs for ARM RPO troubleshoot
```
[ ] Yes
[x] No
```
=> DMP-4483 : Extra logs for ARM RPO troubleshoot

src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImpl.java, src/main/java/uk/gov/hmcts/darts/util/CsvFileUtil.java, src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4480
Fixed issue where the csv file was not being read correctly
```
[ ] Yes
[x ] No
```
=> DMP-4480 ARM-RPO - Objects are not marked as stored

src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImpl.java, src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4376
Modified the general log message so it doesnt look like there is an error when it can't find a valid latest execution detail to poll against
```
[ ] Yes
[x ] No
```
=> DMP-4376 Add ARM RPO logs for Dynatrace

src/integrationTest/java/uk/gov/hmcts/darts/authorisation/service/AuthorisationServiceTest.java, src/main/java/uk/gov/hmcts/darts/authorisation/service/impl/AuthorisationServiceImpl.java
DMP-4501
While fetching the user Authorisation via emailAddress, added a new criteria to check user state as ACTIVE.
```
[ ] Yes
[x] No
```
=> DMP-4501 : Additional Userstate criteria to load Authorisation

src/main/resources/db/migration/common/V1_423__populate_courthouse_legacy_details.sql
Populate courthouse_object_id and folder_path for known legacy courthouses.
Migration verified locally against data cloned from staging.
```
[ ] Yes
[X] No
```
=> DMP-4510: Populate courthouse_object_id and folder_path

src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/notification/helper/TemplateIdHelperTest.java, src/main/java/uk/gov/hmcts/darts/notification/helper/GovNotifyRequestHelper.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-4167
https://tools.hmcts.net/jira/browse/DMP-4168
https://tools.hmcts.net/jira/browse/DMP-4170
https://tools.hmcts.net/jira/browse/DMP-4171
Add courthouse to the audio notification templates
```
[ ] Yes
[ x] No
```
=> DMP-4167 Update audio notification templates with courthouse

src/integrationTest/java/uk/gov/hmcts/darts/task/service/AutomatedTaskServiceTest.java, src/main/java/uk/gov/hmcts/darts/task/config/DailyListHousekeepingAutomatedTaskConfig.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/DailyListHousekeepingAutomatedTask.java, src/test/java/uk/gov/hmcts/darts/task/runner/impl/DailyListHouseKeepingAutomatedTaskTest.java
Rename the Daily List housekeeping job
=> Rename daily list housekeeping job

src/integrationTest/java/uk/gov/hmcts/darts/arm/client/ArmTokenClientIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmApiServiceIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRetentionEventDateProcessorIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/client/ArmTokenClient.java, src/main/java/uk/gov/hmcts/darts/arm/client/config/ArmClientConfig.java, src/main/java/uk/gov/hmcts/darts/arm/client/model/ArmTokenRequest.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmApiServiceImpl.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/arm/client/ArmClientConfigTest.java, src/test/java/uk/gov/hmcts/darts/arm/service/ArmApiServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4539
Changed ARM RPO token from /api/v1/token to /auth/account/token. Also changed the request from text/plain to application/json
```
[ ] Yes
[ x] No
```
=> DMP-4539 ARM RPO - Token Endpoint changes

src/main/resources/db/migration/postgres/V1_423_DMP-4566.sql
>[Jira](https://tools.hmcts.net/jira/browse/DMP-4566)
The following courthouses need to be updated to match legacy: 
|*courthouse_object_id*|*Display name (legacy - correct)*|*Display name (modernised - incorrect)*|
|0b170758981f894d|Taunton Sitting at Worle|Taunton sitting at Worle|
|0b170758990cab24|Linc Crown Sitting at Linc Mags|Linc Crown Sitting At Mags|
|0b17075899a8e97e|Wolverhampton Sitting at Telford|Wolverhampton sitting at Telford|
|0b17075899b3c802|Worcester Sitting at Redditch JC|Worcester Sitting At Redditch JC|
|0b17075880a73969|Kingston upon Hull Combined Court Centre (including Beverley)|Kingston Upon Hull Combined Court Centre|
|0b17075880a7396d|Rolls Building Courthouse 1|Rolls Building Court House 1|
|0b17075880a7396e|Rolls Building Courthouse 2|Rolls Building Court …
=> DMP-4566: Flyway updates for migration tranche 2

src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java, src/test/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepositoryTest.java
=> Query optimisations

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAdminGetTranscriptionIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriberTranscriptsIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/given/MigratedTranscriptionSearchGivensBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/given/ModernisedTranscriptionSearchGivensBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/given/TranscriptionSearchGivensBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/service/MigratedTranscriptionSearchTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/service/ModernisedTranscriptionSearchTest.java, src/integrationTest/resources/tests/transcriptions/transcription/expectedResponse.json, src/integrationTest/resources/tests/transcriptions/transcription/expectedResponseNoCourtroom.json, src/integrationTest/resources/tests/transcriptions/transcription/expectedResponseNoHearing.json, src/integrationTest/resources/tests/transcriptions/transcription/expectedResponseNoUrgency.json, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/YourTranscriptsQueryImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/YourTranscriptsSummaryRequesterRowMapper.java, src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java, src/main/java/uk/gov/hmcts/darts/transcriptions/model/TranscriptionSearchResult.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionServiceImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionSearchQueryImpl.java, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapperTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionServiceTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java, src/test/resources/Tests/transcriptions/mapper/TranscriptionResponseMapper/expectedResponseApprovedSingleEntity.json, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/TranscriptionTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/TranscriptionWorkflowTestData.java
DMP-4131
Returning a new attribute "approved_ts" to represent Approved On timestomp.
```
[ ] Yes
[x] No
```
=> Dmp 4131 add approved on transcription

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/DetsToArmBatchProcessResponseFilesIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFiles.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchProcessResponseFilesImpl.java
DMP-4593
Added extra check to avoid LazyLoading exception during fetching of OSR object from EOD.
```
[ ] Yes
[x] No
```
=> DMP-4593 : Missing OSR is failing the ARM's Missing IU Response flow

src/main/java/uk/gov/hmcts/darts/common/datamanagement/component/impl/DataManagementAzureClientFactoryImpl.java
DMP-4602
Temp change to print the DETS SAs token. A new SAS token will be recycled after the analysis.
```
[ ] Yes
[x] No
```
=> DMP-4602 : DETS SAS token issue

src/main/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchProcessResponseFilesImpl.java
DMP-4593
Added the correct entity into the update method.
```
[ ] Yes
[x] No
```
=> DMP-4593 : Missing-Arm-Response-File

src/main/resources/db/migration/common/V1_433__initital_audit_snapshot.sql
=> Updated migration

src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java, src/integrationTest/java/uk/gov/hmcts/darts/notification/helper/TemplateIdHelperTest.java, src/main/resources/application.yaml
This ticket includes changes for the following tickets:
[DMP-4175](https://tools.hmcts.net/jira/browse/DMP-4175)
[DMP-4169](https://tools.hmcts.net/jira/browse/DMP-4169)
[DMP-4172](https://tools.hmcts.net/jira/browse/DMP-4172)
[DMP-4173](https://tools.hmcts.net/jira/browse/DMP-4173)
[DMP-4174](https://tools.hmcts.net/jira/browse/DMP-4174)
Update the content of Transcription notifications to include case number and courthouse display name.
```
[ ] Yes
[x ] No
```
=> DMP-4175 Update transcript notifications

src/functionalTest/java/uk/gov/hmcts/darts/dets/DetsDataManagementServiceTest.java, src/main/java/uk/gov/hmcts/darts/util/AzureCopyUtil.java
https://tools.hmcts.net/jira/browse/DMP-4694
Added functional test to attempt to push a non existing dets file to ARM to see what errors are thrown
```
[ ] Yes
[ x] No
```
=> DMP-4694 PUSH to ARM Fails with error INGESTION_READ_ERROR

src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionLinkedCaseEntity.java
=> Fixed tests

charts/darts-api/values.stg.template.yaml
=> More memory for staging pipeline pods

charts/darts-api/values.stg.template.yaml
=> Using dev prefix for staging pipeline memory options

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java
Added some temp logging to support defect investigations
=> Added some temp logging to support defect investigations

src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiGetExtendedProductionsByMatterIntTest.java
https://tools.hmcts.net/jira/browse/DMP-4613
Integration tests for DMP-4613
```
[ ] Yes
[ x] No
```
=> DMP-4613-IntegrationTests

build.gradle, src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java, src/main/java/uk/gov/hmcts/darts/cases/helper/AdvancedSearchRequestHelperPaginated.java, src/main/java/uk/gov/hmcts/darts/cases/mapper/AdvancedSearchResponseMapper.java, src/main/java/uk/gov/hmcts/darts/cases/model/AdvancedSearchRequestPaginated.java, src/main/java/uk/gov/hmcts/darts/cases/model/GetCasesSearchRequestPaginated.java, src/main/java/uk/gov/hmcts/darts/cases/service/CaseService.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/util/paginated/IsPageable.java, src/main/java/uk/gov/hmcts/darts/common/util/paginated/PaginatedList.java, src/main/java/uk/gov/hmcts/darts/common/util/paginated/PaginationUtil.java, src/main/java/uk/gov/hmcts/darts/common/util/paginated/SortMethod.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java
>[Jira](https://tools.hmcts.net/jira/browse/DMP-4757)
Note, this is a Proof of convcept PR so no tests. 
The diff reflects updates to a Java project involving enhancements to pagination functionalities in various classes, particularly focusing on support for paginated search requests. Key areas of modification include the `build.gradle` file for dependency management, updates to existing controllers and services to accommodate pagination features, and the introduction of new classes to handle paginated search requests.
- **Dependency Addition**: The `build.gradle` file now includes `com.querydsl:querydsl-core` and its JPA integration for advanced query capabilities.
- **Controller Enhancements**:
- A new endpoint `/cases/paginatedSearch` has been added in `CaseController` to handle …
=> DMP-4757: Pagination of advanced search

build.gradle, src/main/java/uk/gov/hmcts/darts/common/config/security/SecurityConfig.java, src/main/java/uk/gov/hmcts/darts/common/controller/KeepAliveTestController.java
https://tools.hmcts.net/jira/browse/DMP-4758
Test for keep alive signal to workaround 30s request timeout for long searches.
```
[ ] Yes
[ ] No
```
=> Keep alive test controller

src/main/java/uk/gov/hmcts/darts/common/config/security/SecurityConfig.java, src/main/java/uk/gov/hmcts/darts/common/controller/KeepAliveTestController.java
=> DMP-4758 keep alive poc - stream

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/DetsToArmBatchProcessResponseFilesIntTest.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchProcessResponseFilesImpl.java, src/test/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchProcessResponseFilesImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4726
Added code to set file_size_ingest_to_arm on object record state
```
[ ] Yes
[ x] No
```
=> DMP-4726 DetsToArm - Update OSR field file_size_ingest_to_arm

src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java
https://tools.hmcts.net/jira/browse/DMP-4117
**No functional changes**
Following a review of native SQL queries, I have amended some SQL formatting and added clarity to a comment.
```
[ ] Yes
[ ] No
```
=> SQL formatting updates and clarity added to comment

src/integrationTest/java/uk/gov/hmcts/darts/cases/repository/CaseRepositoryIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AutomatedTaskServiceTest.java, src/main/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentBatchProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java, src/test/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentBatchProcessorImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4743
Changed the job to get the batched ids instead of the batched objects
```
[ ] Yes
[x ] No
```
=> DMP-4743 Improve automated task - GenerateCaseDocument

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/given/MigratedTranscriptionSearchGivensBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/given/ModernisedTranscriptionSearchGivensBuilder.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/TranscriptionTestData.java
https://tools.hmcts.net/jira/browse/DMP-4771
```
[ ] Yes
[ ] No
```
=> DMP-4771 Only return current transcription records on admin search

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepositoryTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/InboundAudioDeleterProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionsProcessorImpl.java
https://tools.hmcts.net/jira/browse/DMP-4742
Changed code when it gets the batched data it gets just the ids not the full object.
```
[ ] Yes
[x ] No
```
=> DMP-4742 Improve automated task - CloseOldUnfinishedTranscriptions

src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java
https://tools.hmcts.net/jira/browse/DMP-4604
Actually allow the RCJ appeals user to download the audio.
```
[ ] Yes
[ ] No
```
=> DMP-4604 Allowing RCJ appeals user to download transformed media

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/DarStartHandlerTest.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/DarNotifyServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-3187
Send DAR PC notification for closed cases
```
[ ] Yes
[ x] No
```
=> DMP-3187 Send DAR PC notification for closed cases

src/integrationTest/java/uk/gov/hmcts/darts/casedocument/service/GenerateCaseDocumentForRetentionDateBatchProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/casedocument/service/GenerateCaseDocumentProcessorIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/cases/repository/CaseRepositoryIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/service/AutomatedTaskServiceTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java
https://tools.hmcts.net/jira/browse/DMP-4724
Added additional criteria to check if case retention record has COMPLETE status
```
[ ] Yes
[ x] No
```
=> Dmp 4724 update case document generation logic

src/test/java/uk/gov/hmcts/darts/cases/mapper/EventMapperTest.java, src/test/java/uk/gov/hmcts/darts/common/datamanagement/api/DataManagementFacadeImplTest.java, src/test/java/uk/gov/hmcts/darts/event/mapper/EventMapperTest.java
https://tools.hmcts.net/jira/browse/DMP-4633
Started to resolve sonar issues
```
[ ] Yes
[ x] No
```
=> DMP-4633 Review and resolve sonar issues with the master branch

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/given/MigratedTranscriptionSearchGivensBuilder.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/service/MigratedTranscriptionSearchTest.java, src/main/java/uk/gov/hmcts/darts/arm/mapper/impl/TranscriptionArchiveRecordMapperImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java
https://tools.hmcts.net/jira/browse/DMP-4784
- link to courthouse from court_case instead of via the courtroom linked to the transcription
```
[ ] Yes
[ ] No
```
=> DMP-4784 Migrated transcription search fix

src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmApiServiceImpl.java, src/test/java/uk/gov/hmcts/darts/arm/service/ArmApiServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4788
Fixed isuue with passing null retention score to update metadata
```
[ ] Yes
[x ] No
```
=> DMP-4788 UpdateMetadata Fails Due to Missing Retention Score

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepositoryTest.java, src/main/java/uk/gov/hmcts/darts/arm/helper/DataStoreToArmHelper.java, src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java, src/test/java/uk/gov/hmcts/darts/arm/helper/DataStoreToArmHelperTest.java
https://tools.hmcts.net/jira/browse/DMP-4117
- it was only used within tests
```
[ ] Yes
[ ] No
```
=> DMP-4117 Removing findFileSize query and usages

src/main/java/uk/gov/hmcts/darts/event/service/impl/DarNotifyServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-4801
- ensuring the case numbers are specified even if they are closed
- fixing log statement event_id/courthouse values
```
[ ] Yes
[ ] No
```
=> DMP-4801 Fixing DAR notification for closed cases

infrastructure/main.tf
=> postgres-params

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java
=> Removed temp log

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAdminGetTranscriptionIntTest.java, src/main/java/uk/gov/hmcts/darts/cases/mapper/HearingEntityToCaseHearing.java, src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java, src/main/java/uk/gov/hmcts/darts/hearings/mapper/GetHearingResponseMapper.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionServiceImpl.java, src/test/java/uk/gov/hmcts/darts/cases/mapper/HearingEntityToCaseHearingTest.java, src/test/java/uk/gov/hmcts/darts/hearings/mapper/GetHearingResponseMapperTest.java
https://tools.hmcts.net/jira/browse/DMP-4809
- checking transcription.is_current
- only counting current transcriptions
**Assessing use of transcription.is_current**
- within TranscriptionRepository queries
- fixing user transcriptions
```
[ ] Yes
[ ] No
```
=> DMP-4809 Correcting hearing transcription count

charts/darts-api/Chart.yaml
N/A
- some versions are becoming deprecated soon
```
[ ] Yes
[ ] No
```
=> Updating helm charts

src/main/java/uk/gov/hmcts/darts/common/repository/ExternalLocationTypeRepository.java, src/main/java/uk/gov/hmcts/darts/common/repository/ObjectRecordStatusRepository.java
=> Removed cache for ORS and ELT

.idea/codeStyles/Project.xml
Intellij code style update to conform with newer version 2024.3.4 CE
```
[ ] Yes
[x ] No
```
=>  Intellij code style update to conform with newer version 2024.3.4 CE

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFilesIntTest.java, src/main/java/uk/gov/hmcts/darts/admin/test/TestSupportController.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/StubbedArmRpoDownloadProductionImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/CreateExportBasedOnSearchResultsTableServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFiles.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/UnstructuredToArmBatchProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/audio/auditing/HibernateEventListenerRegistryConfiguration.java, src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java, src/main/java/uk/gov/hmcts/darts/common/util/CourtValidationUtils.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/EventMappingServiceImpl.java, src/main/java/uk/gov/hmcts/darts/event/service/impl/EventSearchServiceImpl.java, src/main/java/uk/gov/hmcts/darts/task/config/AsyncTaskConfig.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/AbstractLockableAutomatedTask.java, src/test/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesImplTest.java, src/test/java/uk/gov/hmcts/darts/arm/service/UnstructuredToArmBatchProcessorTest.java, src/test/java/uk/gov/hmcts/darts/datamanagement/service/InboundToUnstructuredProcessorImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4635
Added PMD fixes
```
[ ] Yes
[x ] No
```
=> Dmp 4635 fix pmd issues3

src/integrationTest/java/uk/gov/hmcts/darts/arm/client/ArmTokenClientIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBaseWithWiremock.java
Updated IntegrationBaseWithWiremock to use a Dynamic Startup Delay
=> Updated IntegrationBaseWithWiremock to use a Dynamic Startup Delay

src/test/java/uk/gov/hmcts/darts/annotation/service/impl/AnnotationDataManagementTest.java, src/test/java/uk/gov/hmcts/darts/annotation/service/impl/AnnotationUploadTest.java, src/test/java/uk/gov/hmcts/darts/annotation/validators/HearingExistsValidatorTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/CreateExportBasedOnSearchResultsTableCheckServiceTest.java, src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/CreateExportBasedOnSearchResultsTableServiceTest.java, src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/audio/component/impl/RemoveAdminActionComponentTest.java, src/test/java/uk/gov/hmcts/darts/authentication/component/impl/SimpleInMemorySessionCacheImplTest.java, src/test/java/uk/gov/hmcts/darts/courthouse/validation/CourthousePatchValidatorTest.java, src/test/java/uk/gov/hmcts/darts/datamanagement/service/DataManagementServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/task/service/impl/AdminAutomatedTasksServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserEmailValidatorTest.java
https://tools.hmcts.net/jira/browse/DMP-4633
Fixed sonar complaint - Refactor the code of the lambda to have only one invocation possibly throwing a runtime exception.
```
[ ] Yes
[x ] No
```
=> Dmp 4633 resolve sonar issues5

charts/darts-api/Chart.yaml, charts/darts-api/values.dev.template.yaml, charts/darts-api/values.stg.template.yaml, charts/darts-api/values.yaml, src/main/java/uk/gov/hmcts/darts/datamanagement/config/DataManagementConfiguration.java, src/main/java/uk/gov/hmcts/darts/util/AzureCopyUtil.java, src/main/resources/application-local.yaml, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/util/AzureCopyUtilTest.java
https://tools.hmcts.net/jira/browse/DMP-4873
Modified the azcopy command to reduce the size of the log files generated and reduce the size of the console output.
```
[ ] Yes
[ x] No
```
=> Dmp 4873 performance testing investigate azcopy command line parameter options

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetMarkedForDeletionIntTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImpl.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4870
https://tools.hmcts.net/jira/browse/DMP-4871
- return array including distinct comments only
- only return current media
```
[ ] Yes
[ ] No
```
=> DMP-4870-DMP-4871 Fixing for audio marked for deletion endpoint

src/main/java/uk/gov/hmcts/darts/util/AzureCopyUtil.java
https://tools.hmcts.net/jira/browse/DMP-4873
Added temporary log message to confirm the command line parameters are as expected
```
[ ] Yes
[ x] No
```
=> DMP-4873-AddAzcopyCommandLineParameterLog

src/main/resources/db/migration/postgres/V1_466__insert_legacy_courthouse_burnley_cc_sitting_at_burnley_mc.sql
https://tools.hmcts.net/jira/browse/DMP-4906
Added legacy courthouse Burnley CC Sitting at Burnley MC and associated security groups
```
[ ] Yes
[x ] No
```
=> DMP-4906 New Courthouse (Burnley CC Sitting at Burnley MC) to be added to modernised DARTS

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/MediaControllerPostAdminMediasSearchIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/AudioLinkingAutomatedTaskITest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/MediaStub.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/MediaStubComposable.java, src/main/java/uk/gov/hmcts/darts/audio/helper/PostAdminMediasSearchHelper.java
https://tools.hmcts.net/jira/browse/DMP-4236
Admin search for media should only return current media
```
[ ] Yes
[x ] No
```
=> DMP-4236 Admin search for media should only return current media

src/main/resources/db/reference/modernised_darts_indexes.sql
=> v13 of modernised indexes, to remove 7 duplicates

build.gradle, src/integrationTest/java/uk/gov/hmcts/darts/common/repository/EventRepositoryTest.java, src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/AudioLinkingAutomatedTaskIntTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/AudioLinkingAutomatedTask.java, src/test/java/uk/gov/hmcts/darts/task/runner/impl/AudioLinkingAutomatedTaskTest.java
https://tools.hmcts.net/jira/browse/DMP-4892
Added code to not process events that link to handheld courtrooms
```
[ ] Yes
[x ] No
```
=> Dmp 4892 exclude handheld audio courtrooms from audio linking job

src/main/java/uk/gov/hmcts/darts/cases/util/RequestValidator.java, src/test/java/uk/gov/hmcts/darts/cases/util/RequestValidatorTest.java
https://tools.hmcts.net/jira/browse/DMP-4748
The `courthouseIds` parameter was missing from the "no search criteria" check, adding it.
```
[ ] Yes
[ ] No
```
=> DMP-4748 Case search - adding courthouseIds to no criteria check

src/main/resources/db/migration/common/V1_468__drop_object_state_record_indexes.sql
https://tools.hmcts.net/jira/browse/DMP-4935
Removed indexes:
- osr_id_clip_md5_doc_tx_dets (id_clip,md5_doc_transfer_to_dets) 
- osr_md5_doc_tx_dets
- osr_content_object_id
- osr_flag_file_transfer_to_dets
```
[ ] Yes
[ x] No
```
=> DMP-4935 refine indexing on object_state_record

src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/darts/task/runner/impl/AudioLinkingAutomatedTaskTest.java
https://tools.hmcts.net/jira/browse/DMP-4940
Added courtroom 99 to list of handhelp courtrooms
```
[ ] Yes
[x ] No
```
=> DMP-4940 Add courtroom 99 to list of handheld courtrooms

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetAdminMediaVersionsByIdIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImplTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsLegacyIntTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/YourTranscriptsQueryImpl.java
https://tools.hmcts.net/jira/browse/DMP-4953
Modified the your transcipts request to return the first requested date so if the admin puts a transcript back to requested, it only shows 1 result and the first requested date time
```
[ ] Yes
[x ] No
```
=> DMP-4953 Your transcript screen can show the same transcript multiple times

src/functionalTest/java/uk/gov/hmcts/darts/FunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/arm/ArmServiceFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/audio/AudioFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/cases/CasesFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/dailylist/DailylistFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/datamanagement/DataManagementServiceFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/dets/DetsDataManagementServiceTest.java, src/functionalTest/java/uk/gov/hmcts/darts/events/CourtlogsFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/events/EventMapperFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/darts/events/PostEventsFunctionalTest.java
https://tools.hmcts.net/jira/browse/DMP-4805
Added functional test to verify blob is deleted when addAudioMetadata fails
```
[ ] Yes
[x ] No
```
=> DMP-4805 DEV ONLY: Add functional tests to verify blob is deleted on failure for addAudio

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/EventRepositoryTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/AudioLinkingAutomatedTask.java, src/test/java/uk/gov/hmcts/darts/task/runner/impl/AudioLinkingAutomatedTaskTest.java
https://tools.hmcts.net/jira/browse/DMP-4892
https://tools.hmcts.net/jira/browse/DMP-4989 (BUG)
- checking courtroom names, not IDs
```
[ ] Yes
[ ] No
```
=> DMP-4892 DMP-4989 Fixing handheld audio courtroom check for audio linking

src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/AssociatedObjectDataExpiryDeletionAutomatedTaskITest.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/AssociatedObjectDataExpiryDeletionAutomatedTask.java
https://tools.hmcts.net/jira/browse/DMP-4759
Moved code into inner class so that @Transactional is effective
```
[ ] Yes
[x ] No
```
=> DMP-4759 Improve AssociatedObjectDataExpiryDeletionAutomatedTask

src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFiles.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRetentionEventDateProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/BatchCleanupArmResponseFilesServiceCommon.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchPushProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/UnstructuredAnnotationTranscriptionDeleterProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/InboundAudioDeleterProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/UnstructuredAudioDeleterProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CloseOldCasesProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpl.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundTranscriptionAnnotationDeleterProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/log/api/LogApi.java, src/main/java/uk/gov/hmcts/darts/log/api/impl/LogApiImpl.java, src/main/java/uk/gov/hmcts/darts/log/service/AutomatedTaskLoggerService.java, src/main/java/uk/gov/hmcts/darts/log/service/impl/AutomatedTaskLoggerServiceImpl.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionCaseAssociatedObjectsProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/AbstractLockableAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/AssociatedObjectDataExpiryDeletionAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/ExternalDataStoreDeleterAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/ProcessArmRpoPendingAutomatedTask.java, src/main/java/uk/gov/hmcts/darts/task/service/impl/ManualDeletionProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionsProcessorImpl.java, src/test/java/uk/gov/hmcts/darts/log/service/impl/AutomatedTaskLoggerServiceTest.java
https://tools.hmcts.net/jira/browse/DMP-4911
Added a generic message to log the batch size when the task is started but also added a log for each task when it gets data so there is a log for how many were being processed against for the batch size
```
[ ] Yes
[x ] No
```
=> DMP-4911 Include batch size into automated tasks logs

src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTaskIntTest.java, src/main/java/uk/gov/hmcts/darts/cases/service/CaseExpiryDeleter.java, src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseExpiryDeleterImpl.java, src/main/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTask.java, src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseExpiryDeleterImplTest.java, src/test/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTaskTest.java
https://tools.hmcts.net/jira/browse/DMP-4760
Moved run code into an inner class so that the @Transactional is effective
```
[ ] Yes
[x ] No
```
=> DMP-4760 Improve CaseExpiryDeletionAutomatedTask

src/integrationTest/java/uk/gov/hmcts/darts/arm/component/StubbedArmRpoDownloadProductionIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRpoServiceIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepositoryTest.java, src/main/java/uk/gov/hmcts/darts/arm/component/impl/StubbedArmRpoDownloadProductionImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/AddAsyncSearchServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/CreateExportBasedOnSearchResultsTableServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/DownloadProductionServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetExtendedProductionsByMatterServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetExtendedSearchesByMatterServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetIndexesByMatterIdServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetMasterIndexFieldByRecordClassSchemaServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetProductionOutputFilesServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetProfileEntitlementsServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetRecordManagementMatterServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetStorageAccountsServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/RemoveProductionServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/SaveBackgroundSearchServiceImpl.java, src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java, src/test/java/uk/gov/hmcts/darts/arm/component/impl/StubbedArmRpoDownloadProductionImplTest.java, src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImplTest.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/builder/TestExternalObjectDirectoryEntity.java
https://tools.hmcts.net/jira/browse/DMP-5000
Changed the ARM reconciliation to use the input upload timestamp instead of data ingestion so its inline with the date times used by ARM not the date times we process the data. Also changed ARM RPO logging from debug to info to aid production.
```
[ ] Yes
[ x] No
```
=> DMP-5000 ARM Reconciliation Amendment

infrastructure/prod.tfvars
=> DMP-5001 increase cores on darts-api

src/main/resources/application.yaml
Updated file size request limits to support larger then 1MB
=> Updated file size request limits

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/EventRepositoryTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java
https://tools.hmcts.net/jira/browse/DMP-4985
Removed redundant code and fixed tests
```
[ ] Yes
[x ] No
```
=> DMP-4985 (Dev only) Tech Debt: Several methods in EventRepository are exclusively used in integration tests. These should be reviewed / removed

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImplIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImplTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/component/impl/YourTranscriptsQueryImplIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriberTranscriptsIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsLegacyIntTest.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/YourTranscriptsQueryImpl.java, src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java, src/main/java/uk/gov/hmcts/darts/transcriptions/util/TranscriptionUtil.java, src/test/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchPushProcessorImplTest.java
https://tools.hmcts.net/jira/browse/DMP-4900
Changed code to return the first approved on date not the last
```
[ ] Yes
[x ] No
```
=> DMP-4900 Change the Approved on date on various screens so that it displays the first value for this field

charts/darts-api/Chart.yaml, charts/darts-api/values.yaml
Notification schedule in chart is overriding the intended schedule set in application.yaml. This PR removes it from the chart. 
```
[ ] Yes
[ x] No
```
=> Remove notification schedule from chart

src/test/java/uk/gov/hmcts/darts/arm/mapper/impl/CaseArchiveRecordMapperImplTest.java
=> Fixed sonar

src/main/java/uk/gov/hmcts/darts/audio/mapper/GetAdminMediaResponseMapper.java, src/test/java/uk/gov/hmcts/darts/audio/mapper/GetAdminMediaResponseMapperTest.java
Fix NPE when no current version of audio exists
```
[ ] Yes
[ x] No
```
=> DMP-3397 Handle audio versions when no current version exists

src/main/java/uk/gov/hmcts/darts/common/entity/MediaEntity.java, src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java, src/main/java/uk/gov/hmcts/darts/util/DataUtil.java, src/test/java/uk/gov/hmcts/darts/util/DataUtilTest.java
Updated order by so hearings get ordered by createdDateTime, then hearingDate then id
=> Order by update

src/main/resources/application.yaml
=> Allow max handheld audio files to be overriden in flux

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsPersistence.java, src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsLegacyIntTest.java
https://tools.hmcts.net/jira/browse/DMP-4963
Added tests for legacy Your transcriptions' requests
```
[ ] Yes
[ x] No
```
=> DMP-4963 (DEV ONLY) Add 'Your transcriptions' tests for migrated data

src/main/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImpl.java
DMP-5078
Changing logs from debug to info in ATS flow
```
[ ] Yes
[x] No
```
=> DMP-5078 : Changing logs from debug to info in ATS flow

build.gradle
https://tools.hmcts.net/jira/browse/DMP-5055
```
[ ] Yes
[ ] No
```
=> DMP-5055 Fixing openApi spec publishing

src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/GetSecurityGroupIntTest.java, src/main/java/uk/gov/hmcts/darts/common/enums/SecurityRoleEnum.java, src/main/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityGroupController.java
https://tools.hmcts.net/jira/browse/DMP-5064
Authorisation change for `SecurityGroupController`
```
[ ] Yes
[ ] No
```
=> DMP-5064 Allowing SUPER_USER to get security group by id

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/MediaRequestRepositoryIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/common/repository/MediaRequestRepositoryTest.java, src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java, src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java, src/main/java/uk/gov/hmcts/darts/common/repository/MediaRequestRepository.java, src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java
Updated transaction logic for Keda Pods
=> Updated transaction logic for Keda Pods

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetEventByCaseIdTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandlerTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java
https://tools.hmcts.net/jira/browse/DMP-4962
Non-current events should not be included in the case events endpoint
```
[ ] Yes
[x ] No
```
=> DMP-5106 Exclude non-current events from case events endpoint

src/main/resources/application.yaml
Use an environment variable to override the audio linking threshold by environment
```
[ ] Yes
[x ] No
```
=> Audio linking threshold env variable

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/MediaRepositoryIntTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/MediaRepository.java
https://tools.hmcts.net/jira/browse/DMP-3378
Fixed issue where duplicate data was being returned
```
[ ] Yes
[ x] No
```
=> DMP-3378 Get audios for case in admin portal

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf, src/functionalTest/java/uk/gov/hmcts/darts/datamanagement/DataManagementServiceFunctionalTest.java
=> up max connections in prod

infrastructure/import.tf
https://tools.hmcts.net/jira/browse/DTSPO-25926
Added import block for 'darts-api-test' PostgreSQL server
```
[ ] Yes
[X] No
```
=> Added import block for 'darts-api-test' PostgreSQL server

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAttachTranscriptIntTest.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-5147
- to match the file/content types used on legacy
```
[ ] Yes
[ ] No
```
=> DMP-5147 Adding more transcript document allowed file/content types

.github/renovate.json
=> Revert "Temporarily disable automerge of Renovate"

src/integrationTest/java/uk/gov/hmcts/darts/noderegistration/controller/NodeRegistrationControllerGetNodeRegistrationDevicesTest.java, src/integrationTest/java/uk/gov/hmcts/darts/noderegistration/controller/NodeRegistrationControllerPostRegisterDevicesTest.java, src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsPersistence.java, src/main/java/uk/gov/hmcts/darts/common/entity/NodeRegisterEntity.java, src/main/java/uk/gov/hmcts/darts/noderegistration/controller/NodeRegistrationController.java, src/main/java/uk/gov/hmcts/darts/noderegistration/service/NodeRegistrationService.java, src/main/java/uk/gov/hmcts/darts/noderegistration/service/impl/NodeRegistrationServiceImpl.java, src/main/resources/openapi/audiorequests.yaml, src/main/resources/openapi/hearings.yaml, src/main/resources/openapi/noderegistration.yaml, src/main/resources/openapi/transcriptions.yaml, src/test/java/uk/gov/hmcts/darts/noderegistration/service/impl/NodeRegistrationServiceImplTest.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/NodeRegisterTestData.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/PersistableFactory.java, src/testCommon/java/uk/gov/hmcts/darts/test/common/data/builder/TestNodeRegisterEntity.java
https://tools.hmcts.net/jira/browse/DMP-3393
Create a new endpoint for super admins to get details about node registrations
```
[ ] Yes
[ x] No
```
=> DMP-3393 Get node registrations endpoint

src/integrationTest/java/uk/gov/hmcts/darts/noderegistration/controller/NodeRegistrationControllerGetNodeRegistrationDevicesTest.java
N/A
Fixed flakey test
```
[ ] Yes
[x ] No
```
=> Flakey Test

infrastructure/providers.tf
Increment azure/azapi version in tf
=> Increment azure/azapi version in tf

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandlerTest.java, src/main/java/uk/gov/hmcts/darts/retention/service/impl/CloseCaseWithRetentionServiceImpl.java
https://tools.hmcts.net/jira/browse/DMP-5175
```
[ ] Yes
[x ] No
```
=> DMP-5175 Update case closed details after manual override

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerPostEventsTest.java, src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StandardEventHandlerTest.java, src/integrationTest/resources/application-intTest.yaml, src/main/java/uk/gov/hmcts/darts/event/config/EventConfig.java, src/main/java/uk/gov/hmcts/darts/event/service/handler/StandardEventHandler.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DMP-5174
Updated the standard event handler to save the case retention details for configured events
```
[ ] Yes
[x ] No
```
=> DMP-5174 Update sentencing events for standard handler

src/main/java/uk/gov/hmcts/darts/audio/helper/UnstructuredDataHelper.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/DataManagementServiceImpl.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorImpl.java, src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorSingleElementImpl.java, src/test/java/uk/gov/hmcts/darts/datamanagement/service/DataManagementServiceImplTest.java, src/test/java/uk/gov/hmcts/darts/datamanagement/service/InboundToUnstructuredProcessorImplTest.java
=> Revert "DMP-5199 InboundToUnstructuredAutomatedTask - Rethrow Interrupted Exception"

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/UserAccountRepositoryIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostUserIntTest.java, src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerIntTest.java, src/main/java/uk/gov/hmcts/darts/common/repository/UserAccountRepository.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserManagementServiceImpl.java, src/main/java/uk/gov/hmcts/darts/usermanagement/service/validation/UserEmailValidator.java, src/test/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserEmailValidatorTest.java
https://tools.hmcts.net/jira/browse/DMP-3819
Add change so that it disallows duplicate email addresses regardless of whether they are active or not
```
[ ] Yes
[x ] No
```
=> DMP-3819 Update POST /admin/users to disallow duplicate email address
