build.gradle
src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/HandleOAuthCodeIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/LoginOrRefreshIntTest.java
src/integrationTest/resources/application-intTest.yaml

This PR is part 2 of 2 related to DMP-114, containing a happy-path integration test for handle-oauth-code functionality.
Unhappy path tests are out of scope until an error response schema is defined.
```
[ ] Yes
[x] No
```

DMP-114: Integration test for handle-oauth-code

---

Jenkinsfile_CNP
build.gradle

- using the before tasks in the Jenkinsfile did not work due to DB secrets not being available
```
[ ] Yes
[x] No
```

DMP-140 flyway clean differently

---

src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/LogoutIntTest.java
src/main/java/uk/gov/hmcts/darts/authentication/component/UriProvider.java
src/main/java/uk/gov/hmcts/darts/authentication/component/impl/UriProviderImpl.java
src/main/java/uk/gov/hmcts/darts/authentication/config/AuthenticationConfiguration.java
src/main/java/uk/gov/hmcts/darts/authentication/controller/AuthenticationController.java
src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserController.java
src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserController.java
src/main/java/uk/gov/hmcts/darts/authentication/exception/AuthenticationException.java
src/main/java/uk/gov/hmcts/darts/authentication/service/AuthenticationService.java
src/main/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/authentication/component/impl/UriProviderImplTest.java
src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserControllerTest.java
src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserControllerTest.java
src/test/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImplTest.java

logout endpoint implementation, allowing for the first phase of logout to be initiated by Portal:
Azure AD B2C config also updated to reflect the frontend redirect url: `https://darts-portal.staging.platform.hmcts.net/auth/logout-callback`
```
[ ] Yes
[x] No
```

DMP-496: Implement logout endpoint (external users)

---

src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/InvalidateSessionIntTest.java
src/main/java/uk/gov/hmcts/darts/authentication/component/SessionCache.java
src/main/java/uk/gov/hmcts/darts/authentication/component/impl/SimpleInMemorySessionCacheImpl.java
src/main/java/uk/gov/hmcts/darts/authentication/controller/AuthenticationController.java
src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserController.java
src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserController.java
src/main/java/uk/gov/hmcts/darts/authentication/service/AuthenticationService.java
src/main/java/uk/gov/hmcts/darts/authentication/service/SessionService.java
src/main/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/authentication/service/impl/SessionServiceImpl.java
src/test/java/uk/gov/hmcts/darts/authentication/component/impl/SimpleInMemorySessionCacheImplTest.java
src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserControllerTest.java
src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserControllerTest.java
src/test/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImplTest.java

invalidate-session endpoint implementation, allowing for the second phase of logout to be initiated by Portal:
```
[ ] Yes
[x] No
```

Implement invalidate-session endpoint (external users)

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
README.md
build.gradle
charts/darts-api/Chart.yaml
charts/darts-api/values.yaml
docker-compose-local.yml
src/functionalTest/java/uk/gov/hmcts/darts/datamanagement/DataManagementServiceTest.java
src/main/java/uk/gov/hmcts/darts/datamanagement/config/DataManagementConfiguration.java
src/main/java/uk/gov/hmcts/darts/datamanagement/dao/DataManagementDao.java
src/main/java/uk/gov/hmcts/darts/datamanagement/dao/impl/DataManagementDaoImpl.java
src/main/java/uk/gov/hmcts/darts/datamanagement/service/DataManagementService.java
src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/DataManagementServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/datamanagement/dao/DataManagementDaoImplTest.java
src/test/java/uk/gov/hmcts/darts/datamanagement/service/DataManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-405 
Introduced a data management service that initially has two methods. One to save binary data to blob storage for a passed in container name which returns the stored unique id and a get method to fetch binary data for a particular container name and blob id.
The connection string is fetched from the key vault and passed in the services constructor.
Local this will need the Azurite emulator. The read me file has been updated with instructions.
```
[ ] Yes
[ x] No
```

DMP-405 initial data management service to save and get binary blob data

---

src/main/resources/application-dev.yaml
src/main/resources/application-local.yaml
src/main/resources/application.yaml

Spring configuration for the `dev` and `local` profiles currently duplicates config that already exists in `application.yaml`, leading to unncessary complexity and maintainence overhead.
Further, `application.yaml` itself contains duplicated values between properties (generally common elements such as azure hostnames for auth).
This PR removes the duplicate config that exists between profiles, and refactors `application.yaml` to reduce duplication of values by introducing Spring expressions.
```
[ ] Yes
[x] No
```

DMP-531: Tidy up config, remove repetition of properties across profiles

---

src/main/java/uk/gov/hmcts/darts/common/entity/AnnotationEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/AuditEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/CaseEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/CourthouseEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/CourtroomEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/DailyListEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/EventEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/EventTypeEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/ExternalObjectDirectoryEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/HearingEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/HearingMediaEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/MediaEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/ReportEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/ReportingRestrictionsEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionCommentEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java
src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java

Part 1 of DMP-153: The toString method generated by Lombok doesn't play nicely when using bi-directional relationships between entities.  Replaced with Getter and Setter annotations as thats all we currently need.  If we need more lombok functionality in the future we can add specific annotations as required.
```
[ ] Yes
[ ] No
```

Removing data annotation and replacing with getter/setter.

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/service/TransientObjectDirectoryServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/util/AudioTestDataUtil.java
src/integrationTest/java/uk/gov/hmcts/darts/common/service/TransientObjectDirectoryServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java
src/integrationTest/resources/db/migration/V1_9999__integrationTestData.sql
src/main/java/uk/gov/hmcts/darts/audio/entity/MediaRequestEntity.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/entity/ExternalLocationTypeEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/ExternalLocationTypeEnum.java
src/main/java/uk/gov/hmcts/darts/common/entity/ExternalObjectDirectoryEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/MediaEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/TransientObjectDirectoryEntity.java
src/main/java/uk/gov/hmcts/darts/common/repository/ExternalLocationTypeRepository.java
src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java
src/main/java/uk/gov/hmcts/darts/common/service/impl/TransientObjectDirectoryServiceImpl.java
src/main/resources/db/migration/V1_12__object_directory_schema_data.sql
src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-548
Update object directory schema data (v29) to add external_location_type table and transfer_attempts columns
* Also remove integrationTest dependency on V1_9999__integrationTestData.sql
```
[ ] Yes
[x] No
```

DMP-548 Update object directory schema data (v29) to add external_location_type table and transfer_attempts columns

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerCourtLogsTest.java
src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java
src/main/resources/openapi/events.yaml
src/main/resources/openapi/problem.yaml

[624](https://tools.hmcts.net/jira/browse/DMP-624)
Openapi changes required for [DMP-462](https://tools.hmcts.net/jira/browse/DMP-462) (POST /courtlogs), and initial no-op implementation for `@Controller` layer.

DMP-624: Openapi additions for events POST /courtlogs

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceProcessAudioRequestGivenBuilder.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceProcessAudioRequestTest.java
src/main/java/uk/gov/hmcts/darts/audio/entity/MediaRequestEntity.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/UserAccountRepository.java
src/main/java/uk/gov/hmcts/darts/datamanagement/api/DataManagementApi.java
src/main/java/uk/gov/hmcts/darts/datamanagement/api/impl/DataManagementApiImpl.java
src/main/java/uk/gov/hmcts/darts/notification/api/NotificationApi.java
src/main/java/uk/gov/hmcts/darts/notification/api/impl/NotificationApiImpl.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java

Schedule a success or failure notification upon success/failure of audio processing.
This change also takes the opporunity to fix direct access of datamanagement classes from the audio feature, in favour of going through a new api interface in the datamanagement feature.
Finally, complexity of `AudioTransformationServiceImpl` has reached a stage where refactoring would be beneficial. For now, PMD/Checkstyle warnings are suppressed, and ticket DMP-715 is created to later tackle this refactoring.
```
[ ] Yes
[x] No
```

DMP-549: Schedule notification when audio processing is complete

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceProcessAudioRequestTest.java
src/integrationTest/java/uk/gov/hmcts/darts/notification/service/NotificationServiceTest.java
src/main/java/uk/gov/hmcts/darts/notification/entity/NotificationEntity.java
src/main/java/uk/gov/hmcts/darts/notification/repository/NotificationRepository.java
src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java

Update the `NotificationEntity.status` field to utilise existing enum `NotificationStatus`. The benefit is a more expressive entity, and elimination of string conversion at various points in the codebase.
This addresses review comment https://github.com/hmcts/darts-api/pull/301#discussion_r1282984091.
```
[ ] Yes
[x] No
```

Refactor NotificationEntity to utilise NotificationStatus enum

---

src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/LoginOrRefreshIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/LogoutIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/ResetPasswordIntTest.java
src/main/java/uk/gov/hmcts/darts/authentication/component/UriProvider.java
src/main/java/uk/gov/hmcts/darts/authentication/component/impl/UriProviderImpl.java
src/main/java/uk/gov/hmcts/darts/authentication/controller/AuthenticationController.java
src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserController.java
src/main/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserController.java
src/main/java/uk/gov/hmcts/darts/authentication/service/AuthenticationService.java
src/main/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/config/security/SecurityConfig.java
src/test/java/uk/gov/hmcts/darts/authentication/component/impl/UriProviderImplTest.java
src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserControllerTest.java
src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserControllerTest.java
src/test/java/uk/gov/hmcts/darts/authentication/service/impl/AuthenticationServiceImplTest.java

N/A
- including login, logout and reset-password
- this is so that any darts-portal instance is able to authenticate with the staging API, e.g. for local development
```
[ ] Yes
[x] No
```

Optionally override redirect URI in authentication flows

---

docker-compose-local.yml

Enable postgres query logging (by the database server) for local development. This is useful to see exactly which queries are being executed against the database for debugging purposes.
```
[ ] Yes
[x] No
```

Enable postgres query logging for local development

---

ModernisedDarts.postman_collection.json
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetMetadataIntTest.java
src/main/java/uk/gov/hmcts/darts/audio/component/AudioResponseMapper.java
src/main/java/uk/gov/hmcts/darts/audio/component/impl/AudioResponseMapperImpl.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java
src/main/resources/openapi/audio.yaml
src/test/java/uk/gov/hmcts/darts/audio/component/impl/AudioResponseMapperImplTest.java

Implement an endpoint to get all media metadata associated with the provided hearingId.
```
[ ] Yes
[x] No
```

DMP-755: Implement get audio metadata API endpoint

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseByIdTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseHearingsTest.java
src/main/java/uk/gov/hmcts/darts/cases/exception/CaseApiError.java
src/main/java/uk/gov/hmcts/darts/cases/mapper/HearingEntityToCaseHearing.java
src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java

https://tools.hmcts.net/jira/browse/DMP-753
updated CaseApiError.java with another Enum for Hearing data not found. added error handling within service class for an empty array from repository and throws a DartsAPIException
also updated tests to reflect changes - these pass
```
[ ] Yes
[ x] No
```

DMP-753_Add_error_response_to_GET_case_hearings_endpoint

---

config/owasp/suppressions.xml

Latest Release: pgJDBC v42.6.0 17 March 2023
- https://www.cve.org/CVERecord?id=CVE-2020-21469
An issue was discovered in PostgreSQL 12.2 allows attackers to cause a denial of service via repeatedly sending
SIGHUP signals.
```
[ ] Yes
[x] No
```

CVE-2020-21469 - temporary suppression

---

src/main/resources/db/migration/common/V1_206__update_media_request_expiry_ts.sql

[DMP-759](https://tools.hmcts.net/jira/browse/DMP-759)
FIX darts-api/job/master/331 ERROR: column "created_by" of relation "media_request" contains null values
```
[ ] Yes
[x] No
```

BUGFIX media_request created_by / last_modified_by columns

---

src/main/java/uk/gov/hmcts/darts/audio/component/OutboundFileProcessor.java
src/main/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/AudioOperationService.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/service/impl/FileOperationServiceImpl.java
src/test/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImplTest.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioOperationServiceImplTest.java

These changes fix two feature-breaking bugs with the preview audio flow:
- Update `AudioServiceImpl.preview()` to call `AudioOperationService.reEncode()` with a directory name as the `workspaceDir` rather than a full absolute path. This directory is also explicitly created, as this is the expectation of the `ffmpeg` executable.
- Update `FileOperationService.saveFileToTempWorkspace()` to create a subdirectory within the temp workspace directory.
For both items above, the directory name is randomised on each call to ensure each request has a clean/empty location in which to write any output files. This avoids potential naming conflicts with existing files in the directory.
In genreal, method signatures are updated to favour use of `Path` rather than `String` to avoid future ambiguity …

BUGFIX (DMP-829): Fix path usage for audio operations

---

src/integrationTest/java/uk/gov/hmcts/darts/dailylist/service/DailyListServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/DailyListTestData.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DailyListStub.java
src/main/java/uk/gov/hmcts/darts/common/entity/DailyListEntity.java
src/main/java/uk/gov/hmcts/darts/dailylist/mapper/DailyListMapper.java
src/main/java/uk/gov/hmcts/darts/dailylist/repository/DailyListRepository.java
src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpl.java
src/main/resources/db/migration/common/V1_213__dailylist_job_status_not_null.sql
src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java
src/test/java/uk/gov/hmcts/darts/dailylist/service/DailyListProcessorImplTest.java

https://tools.hmcts.net/jira/browse/DMP-962
When an xml is only sent to the daily list post endpoint then we should set the status to NEW for that xml. When the processor handles the daily list it will fail and set the status to FAIL.

DMP-962 - When the daillylist is created, the status of the Dailylist in the database is null which is not expected.

---

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/AuthorisationStub.java
src/main/resources/db/migration/common/V1_216_3__update_transcription_schema_v49.sql
src/main/resources/db/migration/postgres/V1_216_2__update_transcription_schema_v49.sql

[DMP-958](https://tools.hmcts.net/jira/browse/DMP-958)
Update PL/pgSQL function darts.tra_trw_sync_fnc() line 3 at SQL statement to fix ERROR: relation "transcription" does not exist on staging
* Also add Foreign-key constraints and not null columns
```
[ ] Yes
[x] No
```

DMP-958 BUGFIX Update PL/pgSQL function darts.tra_trw_sync_fnc

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioRequestIntTest.java
src/main/java/uk/gov/hmcts/darts/audio/component/impl/AudioResponseMapperImpl.java
src/main/resources/openapi/audio.yaml
src/test/java/uk/gov/hmcts/darts/audio/component/impl/AudioResponseMapperImplTest.java

- Add new field `case_number`, mapping from the case number of the associated case
- Change value mapped to `case_id`, was the case number, now the case id of the associated case
```
[ ] Yes
[x] No
```

DMP-1161: Return caseId and caseNumber in addAudio response

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerGetYourAudioIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/AudioTestData.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java
src/main/java/uk/gov/hmcts/darts/audio/component/impl/AudioRequestSummaryMapperImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioRequestSummaryResult.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java
src/main/resources/openapi/audiorequests.yaml

- Add field `last_accessed_ts` to the `GET /audio-requests` response. The data is obtained from the `last_accessed_ts` field of the `media_request` record.
```
[ ] Yes
[x] No
```

DMP-1177: Return last_accessed_ts in audio requests response

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsGivenBuilder.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java
src/main/java/uk/gov/hmcts/darts/Application.java
src/main/java/uk/gov/hmcts/darts/audio/api/AudioInternalApi.java
src/main/java/uk/gov/hmcts/darts/audio/api/impl/AudioInternalApiImpl.java
src/main/java/uk/gov/hmcts/darts/audio/repository/MediaRequestRepository.java
src/main/java/uk/gov/hmcts/darts/audio/service/AudioTransformationService.java
src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java

Allow `processAudioRequest()` to be invoked by KEDA for the oldest `OPEN` media_request upon application startup when the `ATS_MODE` env var is assigned.
```
[ ] Yes
[x] No
```

dmp-1090 | feat | Keda work

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java
src/main/java/uk/gov/hmcts/darts/audio/entity/MediaRequestEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/HearingEntity.java

This fix resolves `LazyInitialisationException` thrown at multiple points through the `processAudioRequest` flow.
```
[ ] Yes
[x] No
```

DMP-1090: Resolve LazyInitialisationException for processAudioRequest

---

src/main/java/uk/gov/hmcts/darts/common/entity/HearingEntity.java

The eager load between hearing and eventList is unnecessary, reverting this change from prior https://github.com/hmcts/darts-api/pull/536.
```
[ ] Yes
[x] No
```

DMP-1090: Remove redundant eager load

---

ModernisedDarts.postman_collection.json
src/main/java/uk/gov/hmcts/darts/cases/helper/AdvancedSearchRequestHelper.java
src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java

increase search performance by modifying the main search query to only bring back a list of caseIds, instead of a list of CourtCaseEntities, as when we were bringing back the entities, hibernate was going and fetching judges, prosecutors etc, which was not required for the functionality.

increase advanced search performance

---

docker-compose-local.yml

To ensure local development is representative of test environments, the postgres version used for local development should match the same version as deployed in those environments.
As such, pinning to 14.8.
```
[ ] Yes
[x] No
```

Pin postgres version to match test environments

---

build.gradle
charts/darts-api/Chart.yaml
charts/darts-api/values.dev.template.yaml
charts/darts-api/values.yaml
docker-compose-local.yml
src/integrationTest/java/uk/gov/hmcts/darts/common/service/bankholidays/BankHolidayServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBase.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationPerClassBase.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/wiremock/BankHolidayApiStub.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/wiremock/DartsGatewayStub.java
src/integrationTest/resources/application-intTest.yaml
src/main/java/uk/gov/hmcts/darts/Application.java
src/main/java/uk/gov/hmcts/darts/admin/test/TestSupportController.java
src/main/java/uk/gov/hmcts/darts/common/config/BankHolidayCacheConfig.java
src/main/java/uk/gov/hmcts/darts/common/config/RedisConnectionConfig.java
src/main/java/uk/gov/hmcts/darts/common/config/SimpleCacheConfig.java
src/main/java/uk/gov/hmcts/darts/common/service/bankholidays/BankHolidays.java
src/main/java/uk/gov/hmcts/darts/common/service/bankholidays/BankHolidaysApi.java
src/main/java/uk/gov/hmcts/darts/common/service/bankholidays/BankHolidaysService.java
src/main/java/uk/gov/hmcts/darts/common/service/bankholidays/Division.java
src/main/java/uk/gov/hmcts/darts/common/service/bankholidays/Event.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/common/config/RedisConnectionConfigTest.java

Added caching support with connections to Redis by default.  A simple in memory cache is also configured using the profile `in-memory-cache` if required for running the application without access to a Redis instance.  The Redis connection configuration required some low level configuration due to an issue with Netty, Lettuce's (Redis Client Lib) underlying http client with loading a functioning DNS resolver.  Basic cache usage has been implemented for retrieving and caching of bank holidays.  This may change as use case are implemented.  
A testing support endpoint has been added to verify the cache is working in staging. 
Redis has been added to the docker compose config for local testing.
```
[ ] Yes
[ ] No
```

DMP 1193: Redis cache config & bank holiday caching 

---

README.md
src/functionalTest/java/uk/gov/hmcts/darts/hearings/HearingsGetEventsFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsGetControllerTest.java
src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsGetEventsControllerTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/EventStub.java
src/main/java/uk/gov/hmcts/darts/common/entity/HearingEntity.java
src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java
src/main/java/uk/gov/hmcts/darts/hearings/controller/HearingsController.java
src/main/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImpl.java
src/main/resources/openapi/hearings.yaml
src/test/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-1232
Added the auth code to the hearing endpoint and had to change the way the events were retrieved due to the lazy loading not working.
```
[ ] Yes
[x ] No
```

Dmp 1232 add controller layer authorisation to hearing endpoints

---

charts/darts-api/values.dev.template.yaml
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerPreview2IntTest.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java
src/main/resources/openapi/audio.yaml

N/A
Introducing a second audio preview endpoint (/preview2) which returns the file in bytes and allows for a range header to be specified.
I'd like to try this on the portal to see if it makes any difference to the streaming issues we've been having.
```
[] Yes
[x] No
```

Adding `/preview2` audio preview endpoint

---

src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/casesSearchGetEndpointOneObjectReturned.json
src/integrationTest/resources/tests/cases/CaseControllerGetCaseTranscriptsTest/casesSearchGetEndpointTwoObjectsReturned.json
src/main/java/uk/gov/hmcts/darts/cases/mapper/TranscriptionMapper.java
src/main/java/uk/gov/hmcts/darts/hearings/mapper/TranscriptionMapper.java
src/main/resources/openapi/cases.yaml
src/main/resources/openapi/hearings.yaml
src/test/java/uk/gov/hmcts/darts/cases/mapper/TranscriptionMapperTest.java
src/test/java/uk/gov/hmcts/darts/hearings/mapper/TranscriptionMapperTest.java

https://tools.hmcts.net/jira/browse/DMP-1525
There are 2 Get transcriptions endpoint which returns the data using CaseId (for Case screen) and Hearing Id (for hearing screen)
The 'requested_on' parameter in cases.yaml and hearings.yaml have been updated to date-time. 
–  generated file on Transcript.java model for both hearings and cases updated from LocalDate to OffsetDateTime return types
–  the map method in TranscriptionMapper. java for both hearings and cases return requestedOn as OffsetDateTime.
All associated java and json integration test files updated from LocalDate to OffsetDateTime return types for both hearings and cases.
```
[ ] Yes
[x ] No
```

DMP-1525 DateTime Issue in Get Transcription endpoint

---

src/functionalTest/java/uk/gov/hmcts/darts/FunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/UserManagementFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchUserIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostUserIntTest.java
src/main/java/uk/gov/hmcts/darts/admin/test/TestSupportController.java
src/main/java/uk/gov/hmcts/darts/authorisation/api/AuthorisationApi.java
src/main/java/uk/gov/hmcts/darts/authorisation/api/impl/AuthorisationApiImpl.java
src/main/java/uk/gov/hmcts/darts/usermanagement/controller/UserController.java
src/main/java/uk/gov/hmcts/darts/usermanagement/exception/UserManagementError.java
src/main/java/uk/gov/hmcts/darts/usermanagement/mapper/impl/UserAccountMapper.java
src/main/java/uk/gov/hmcts/darts/usermanagement/service/UserManagementService.java
src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserManagementServiceImpl.java
src/main/resources/openapi/usermanagement.yaml

Implement POST (create) and PATCH (modify) user operations.
Note the implementation does not apply any auth restrictions to these endpoints, this will be handled in a future task.
```
[ ] Yes
[x] No
```

DMP-1043/DMP-1049: Implement create and modify user account

---

config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java

Updating functional to test to reflect notification template change
```
[ ] Yes
[x] No
```

Updated transcription rejection notification template.

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java
src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java

https://tools.hmcts.net/jira/browse/DMP-1660
Refactor the audio request processed logic in an attempt to stop Hibernate throwing a lazy loading exception when trying to send the notification when audio request has been processed. 
```
[ ] Yes
[x ] No
```

DMP-1660 Refactor audio request processed logic

---

src/main/resources/openapi/transcriptions.yaml

[DMP-1382](https://tools.hmcts.net/jira/browse/DMP-1382)
Introduced maxLength in Swagger YAML for both "comment" and "workflow_comment" to limit to 2000 characters. 400 will be returned if character limit is exceeded
```
[ ] Yes
[X] No
```

DMP-1382 - Add 2000 character restriction to transcriptions OpenAPI spec

---

src/integrationTest/java/uk/gov/hmcts/darts/authorisation/service/AuthorisationServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchUserIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostUserIntTest.java
src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/UserAccountRepository.java
src/main/java/uk/gov/hmcts/darts/usermanagement/exception/UserManagementError.java
src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserManagementServiceImpl.java
src/main/java/uk/gov/hmcts/darts/usermanagement/service/validation/DuplicateEmailValidator.java
src/main/java/uk/gov/hmcts/darts/usermanagement/service/validation/UserAccountExistsValidator.java
src/test/java/uk/gov/hmcts/darts/usermanagement/service/impl/DuplicateEmailValidatorTest.java
src/test/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserAccountExistsValidatorTest.java

Added validation on creating users with same email address that takes into account existing user state
```
[ ] Yes
[x] No
```

DMP-1635 added validation on creating users with same email 

---

.github/workflows/ci.yml

NA
After upgrading to version 9 of the dependency check tool, which was a breaking change (documented [here](https://github.com/jeremylong/DependencyCheck#900-upgrade-notice)), the CI tool does not work with the checker. However, the dependencies are already checked as part of the Jenkins pipeline and so it is not needed in the CI run so this PR removes that check. 
```
[ ] Yes
[ x] No
```

Remove dependency check from ci

---

src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityGroupFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/UserManagementFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/AdminUserStub.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchUserIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostSecurityGroupIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostUserIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerGetUsersIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerSearchIntTest.java
src/main/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityGroupController.java
src/main/java/uk/gov/hmcts/darts/usermanagement/controller/UserController.java
src/main/resources/db/migration/local/V1_249_1__global_test_user_admin.sql

Restrict admin endpoints to users with the `ADMIN` role and update integration tests.
Assign the `darts_global_test_user` the `ADMIN` role to facilitate functional tests.
```
[ ] Yes
[x] No
```

DMP-1658: Apply authorisation to admin endpoints

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerPreviewIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerDeleteAudioRequestIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerDeleteTransformedMediaIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerPlaybackIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerTransMediaUpdateLastAccessedTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerUpdateLastAccessedTest.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java
src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java
src/main/java/uk/gov/hmcts/darts/common/enums/SecurityRoleEnum.java
src/main/java/uk/gov/hmcts/darts/hearings/controller/HearingsController.java
src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java
src/main/resources/db/migration/common/V1_251__rename_roles.sql
src/main/resources/db/reference/modernised_darts_standing_data.sql
src/test/java/uk/gov/hmcts/darts/authorisation/component/impl/AnyEntityIdControllerAuthorisationImplTest.java
src/test/java/uk/gov/hmcts/darts/authorisation/component/impl/CaseIdControllerAuthorisationImplTest.java
src/test/java/uk/gov/hmcts/darts/authorisation/component/impl/HearingIdControllerAuthorisationImplTest.java
src/test/java/uk/gov/hmcts/darts/authorisation/component/impl/MediaIdControllerAuthorisationImplTest.java
src/test/java/uk/gov/hmcts/darts/authorisation/component/impl/MediaRequestIdControllerAuthorisationImplTest.java
src/test/java/uk/gov/hmcts/darts/authorisation/component/impl/TranscriptionIdControllerAuthorisationImplTest.java

There are two main changes as part of this PR, the remaining changes are refactoring noise.
- Add flyway migraiton to rename the security_role LANGUAGE_SHOP to TRANSLATION_QA.
- Update `src/main/java/uk/gov/hmcts/darts/common/enums/SecurityRoleEnum.java` to reflect the updated attribute name.
```
[ ] Yes
[x] No
```

DMP-1749: Change security role LANGUAGE_SHOP to TRANSLATION_QA

---

infrastructure/providers.tf
src/functionalTest/java/uk/gov/hmcts/darts/dailylist/DailylistFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/controller/DailyListEntityTest.java
src/main/java/uk/gov/hmcts/darts/dailylist/controller/DailyListController.java
src/main/resources/openapi/dailylist.yaml
src/test/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpSaveDailyListTest.java

https://tools.hmcts.net/jira/browse/DMP-1854
The gateway feign library can not work with the json_document header i.e. it does not marshall the json, instead it uses the object string. This likely relates to the fact that headers do not have a specific content type within HTTP.
```
[ ] Yes
[x ] No
```

Dmp 1854 correctly implement add daily list json transfer api

---

src/main/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/audio/config/AudioConfigurationProperties.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java
src/main/java/uk/gov/hmcts/darts/audio/enums/AudioRequestOutputFormat.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImplTest.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/datamanagement/service/InboundToUnstructuredProcessorImplTest.java

[DMP-1724](https://tools.hmcts.net/jira/browse/DMP-1724)
* Update OutboundFileProcessorImpl#processAudioForDownload to remove concatenateByChannel and update session descriminator * Also sort ATS Media by start_ts, channel
* Fix transformed_media output_filename e.g. T20231009-1_04_Jan_2024_1.zip
* Fix config for InboundToUnstructuredProcessor media validation * allowed-media-formats: "mpeg2"
```
[ ] Yes
[x] No
```

DMP-1724 Change the ATS Download logic

---

README.md
bin/secrets-stg.sh
docker-compose-local.yml

N/A
- adding script to help export required secrets from Azure, using the CLI
- running azurite by default in the docker-compose
- removing the need to separately get the account key, it's public anyway
```
[ ] Yes
[X] No
```

Secrets and local blob storage improvements

---

Jenkinsfile_CNP
Jenkinsfile_nightly
Jenkinsfile_parameterized
README.md
charts/darts-api/Chart.yaml
charts/darts-api/values.dev.template.yaml
charts/darts-api/values.yaml
docker-compose-local.yml
src/functionalTest/resources/application-functionalTest.yaml
src/main/java/uk/gov/hmcts/darts/arm/api/impl/ArmDataManagementApiImpl.java
src/main/java/uk/gov/hmcts/darts/arm/config/ArmDataManagementConfiguration.java
src/main/java/uk/gov/hmcts/darts/arm/dao/impl/ArmDataManagementDaoImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/arm/dao/ArmDataManagementDaoImplTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/ArmServiceImplTest.java

A reincarnation of https://github.com/hmcts/darts-api/pull/868, with minor updates to correct functional tests.
Overall this change updates the Azure blob client code to accept a SAS token as part of the connection string.
The associated token held in keyvault (darts-stg) has also been updated, with a token expiry date extending into 2025. No additions have been made to the darts-demo keyvault as ARM will be integrated differently in such higher environments.
```
[ ] Yes
[X] No
```

DMP-1853: SAS Tokens for Auth

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerAddAudioRequestIntTest.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java
src/main/java/uk/gov/hmcts/darts/audio/exception/AudioRequestsApiError.java

https://tools.hmcts.net/jira/browse/DMP-1632
- we should be returning the standard problem object
- not doing this causes issues with the DARTS portal's ability to detect errors successfully
```
[ ] Yes
[x] No
```

DMP-1632 Fixing error for duplicate audio requests

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetMetadataIntTest.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java
src/main/java/uk/gov/hmcts/darts/audio/service/AudioService.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/MediaRepository.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImplTest.java

[DMP-2044](https://tools.hmcts.net/jira/browse/DMP-2044)
GET /audio/hearings/{hearing_id}/audios
* Channel 1 Media metadata for provided hearing
```
[ ] Yes
[x] No
```

DMP-2044 Update getAudioMetadata: only fetch media from channel 1

---

src/functionalTest/java/uk/gov/hmcts/darts/notification/service/GovNotifyServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/component/impl/AudioRequestBeingProcessedFromArchiveQueryImplIntTest.java
src/main/java/uk/gov/hmcts/darts/audio/component/AudioRequestBeingProcessedFromArchiveQuery.java
src/main/java/uk/gov/hmcts/darts/audio/component/impl/AudioRequestBeingProcessedFromArchiveQueryImpl.java
src/main/java/uk/gov/hmcts/darts/audio/component/impl/AudioRequestBeingProcessedFromArchiveQueryResultRowMapper.java
src/main/java/uk/gov/hmcts/darts/audio/model/AudioRequestBeingProcessedFromArchiveQueryResult.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java
src/main/java/uk/gov/hmcts/darts/notification/api/NotificationApi.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplTest.java

[DMP-1470](https://tools.hmcts.net/jira/browse/DMP-1470)
Added a new query (`AudioRequestBeingProcessedFromArchiveQuery`) to help us check whether the filtered hearing media for the audio request has external_object_directory entries for unstructured (Deleted) and arm (Stored), needed to send the new notification: Audio Request Being Processed From Archive
```
[ ] Yes
[x] No
```

DMP-1470 New email template: Audio Request Being Processed From Archive

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerCourtLogsTest.java
src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StandardEventHandlerTest.java
src/main/java/uk/gov/hmcts/darts/event/component/impl/DartsEventMapperImpl.java
src/main/java/uk/gov/hmcts/darts/event/service/handler/base/EventHandlerBase.java
src/main/resources/openapi/event.yaml
src/test/java/uk/gov/hmcts/darts/event/component/impl/DartsEventMapperImplTest.java

Setting whether an event is a log entry from the mid-tier
```
[ ] Yes
[x] No
```

DMP-2069: Setting whether an event is a log entry from the mid-tier

---

src/main/java/uk/gov/hmcts/darts/cases/mapper/CasesMapper.java
src/main/resources/openapi/cases.yaml
src/test/resources/Tests/cases/CasesMapperTest/testMapToSingleCaseWithReportingRestriction/expectedResponse.json

Removing redundant api field
```
[ ] Yes
[x] No
```

DMP-1729: Removing redundant api field

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmResponseFilesProcessorIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/api/ArmDataManagementApi.java
src/main/java/uk/gov/hmcts/darts/arm/api/impl/ArmDataManagementApiImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmResponseFilesProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmServiceImpl.java
src/test/java/uk/gov/hmcts/darts/arm/api/impl/ArmDataManagementApiImplTest.java

https://tools.hmcts.net/jira/browse/DMP-1737
Fixed issue whereby the list blobs returns the blob name and path so setting path for get was unneccesary
```
[ ] Yes
[ x] No
```

DMP-1737-ARM-PullResponseFiles

---

build.gradle
charts/darts-api/Chart.yaml
charts/darts-api/values.dev.template.yaml
charts/darts-api/values.yaml
docker-compose-local.yml
src/integrationTest/java/uk/gov/hmcts/darts/arm/client/ArmClientIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/client/ArmClientConfig.java
src/main/java/uk/gov/hmcts/darts/arm/client/ArmTokenClient.java
src/main/java/uk/gov/hmcts/darts/arm/client/config/ArmClientConfig.java
src/main/java/uk/gov/hmcts/darts/arm/client/model/ArmTokenRequest.java
src/main/java/uk/gov/hmcts/darts/arm/client/model/ArmTokenResponse.java
src/main/resources/application-local.yaml
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/arm/client/ArmClientConfigTest.java

Implement API client to obtain an access token for ARM.
KeyVault entries for `ArmTokenBaseUrl` have been added in Azure for `stg` and `demo`.
Associated wiremock stub is located here: https://github.com/hmcts/darts-stub-services/pull/71
```
[ ] Yes
[x] No
```

DMP-2151: Implement ArmTokenClient

---

Dockerfile

Reverts hmcts/darts-api#994
It didn't work, reverting the change.

Revert "Temp use of distroless-debug base image"

---

src/main/resources/db/migration/common/V1_268__update_outbound_deleter_automated_task_updated.sql

https://tools.hmcts.net/jira/browse/DMP-2194
Original criteria of deleting items accessed on the weekend has been changed as the job will now run on Wednesday 1 am instead of Tuesday 10 pm. This means that items will not be deleted on Tuesday but on Wednesday as 48 hours will not have passed since last access.

DMP-2194 - When "last_accessed_ts" or "created_ts" is set on the date for Saturday or Sunday, it does not get picked up by automated job on Tuesday.

---

src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchUserIntTest.java
src/main/resources/openapi/usermanagement.yaml

Regex for username field of user search is overly-restrictive at this time. A separate excerise will review all applied openapi constraints and tighen/loosen as necessary, with steer from migrated legacy data.
```
[ ] Yes
[x] No
```

Remove overly restrictive regex constraint from usermanagement openapi

---

src/main/java/uk/gov/hmcts/darts/common/sse/SentServerEventsHeartBeatEmitter.java
src/test/java/uk/gov/hmcts/darts/common/sse/SentServerEventsHeartBeatEmitterTest.java

Sse preview was not working for multiple calls as the latch used internally was not being reset.

latch was not being reset when new heartbeats were created.

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/DartsEventNullHandlerTest.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/EventDispatcherImpl.java
src/main/java/uk/gov/hmcts/darts/log/api/LogApi.java
src/main/java/uk/gov/hmcts/darts/log/api/impl/LogApiImpl.java
src/main/java/uk/gov/hmcts/darts/log/enums/EventSource.java
src/main/java/uk/gov/hmcts/darts/log/service/EventLoggerService.java
src/main/java/uk/gov/hmcts/darts/log/service/impl/EventLoggerServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/event/service/impl/EventDispatcherImplTest.java
src/test/java/uk/gov/hmcts/darts/log/service/impl/EventLoggerServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-2005
This might appear over-engineered for a log entry, however doing this has some advantages:
1. these logs are driving a business requirement, so we can fully unit test them
2. we can keep all the logs for Dynatrace in one package
Change include
- including poll checks
- adding check values to config to allow easy overriding via flux
- adding new log package to keep logging in a central place
- exposing via internal "api" package
- unit testing log entries as these are business requirements
- unit testing that the log service is called when an event is received

DMP-2005 Adding event received log entry for Dynatrace

---

src/integrationTest/java/uk/gov/hmcts/darts/task/service/OutboundAudioDeleterProcessorTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TransformedMediaStub.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TransientObjectDirectoryStub.java
src/main/java/uk/gov/hmcts/darts/audio/service/OutboundAudioDeleterProcessorSingleElement.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorSingleElementImpl.java
src/main/java/uk/gov/hmcts/darts/common/entity/TransientObjectDirectoryEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/base/CreatedModifiedBaseEntity.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorImplTest.java

…d operation iteration to improve job performance
https://tools.hmcts.net/jira/browse/DMP-2259
Additional changes:
- removed `@Transactional` from integration tests to prevent false negatives (test passing when instead it should have failed due to a bug in the production code). Integration tests would be better not be `@Transactional` to have the test running in a setting that replicates Production
- changed some JPA one-to-one entity associations to be eagerly fetched (default) rather than lazy. Lazy loading is recommended for *-to-many associations, but lazy loading one-to-one complicates working with entities and should be enabled only **after** measuring performance and if justified by a relevant perf improvement. To avoids premature optimisations.
**Does this PR introduce a breaking …

 DMP-2259 Move @Transactional to single iteration of OutboundAudioDeleter automated task

---

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerRequestTranscriptionIntTest.java
src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionStatusEntity.java
src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java
src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/DuplicateRequestDetector.java
src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/DuplicateRequestDetectorTest.java

[TODO](https://tools.hmcts.net/jira/browse/DMP-2277)
- don't match on closed or rejected transcriptions
- also checking requests without start/end times
- only returning `duplicate_transcription_id` when a matching record is completed
```
[ ] Yes
[x] No
```

DMP-2277 Fixing request transcription duplicate checking logic

---

src/functionalTest/java/uk/gov/hmcts/darts/FunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/darts/courthouses/CourthousesFunctionalTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/controller/CourthouseApiTest.java
src/main/java/uk/gov/hmcts/darts/common/entity/CourthouseEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/RegionEntity.java
src/main/java/uk/gov/hmcts/darts/courthouse/controller/CourthousesController.java
src/main/java/uk/gov/hmcts/darts/courthouse/mapper/AdminCourthouseToCourthouseEntityMapper.java
src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseService.java
src/main/java/uk/gov/hmcts/darts/courthouse/service/CourthouseServiceImpl.java
src/main/resources/openapi/courthouse.yaml
src/test/java/uk/gov/hmcts/darts/courthouse/service/CourthouseServiceImplTest.java

This PR relates to 2 jira tickets:
1. https://tools.hmcts.net/jira/browse/DMP-2282
2. https://tools.hmcts.net/jira/browse/DMP-2296
Implement this relation in both CourthouseEntity and RegionEntity as a many-to-many Set, such that the association is navigable from both directions.
Change the path of `GET /courthouses/{courthouse_id}` to `GET /admin/courthouses/{courthouse_id}`, and update the API response schema to include `region_id` and `security_group_ids` fields as below. Authorisation should also be added to ensure only users with ADMIN role can call this endpoint.
Response
{
"id": 0,
"courthouse_name": "string",
"display_name": "string",
"region_id": 0 \\ NEW,
"security_group_ids": [ 1, 2 ] \\ NEW
"created_date_time": "2024-02-09T14:26:31.118Z",
"last_modified_date_time": …

Origin/dmp 2282 implement get  admin courthouses courthouse

---

src/integrationTest/java/uk/gov/hmcts/darts/notification/service/NotificationServiceTest.java
src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java

When a notification has an invalid email address, we should still store that notification in a failed state in the database. Gov Notify has it's own inbuilt invalid email address feature out of the box. Without this change, there is a risk that notifications would be lost with no chance of recovery. This change would allow a DB admin to change an email address stored against a failed scheduled notification and resend if the need ever arose. 
```
[ ] Yes
[ x] No
```

Schedule notifications to invalid addresses in database

---

src/main/java/uk/gov/hmcts/darts/dets/api/impl/DetsDataManagementApiImpl.java

[DMP-656](https://tools.hmcts.net/jira/browse/DMP-656)
Add missing `@Service` annotation needed to support DETS BlobContainerDownloadable.
Referring to https://github.com/hmcts/darts-api/blob/master/src/main/java/uk/gov/hmcts/darts/common/datamanagement/api/DataManagementFacadeImpl.java#L20
```
[ ] Yes
[x] No
```

DMP-656 Add missing @Service annotation needed to support DETS BlobContainerDownloadable

---

docker-compose-local.yml

Removing default dar pc notification url.  The url will now come only from the node_register table.
```
[ ] Yes
[x] No
```

Removing default dar pc notification url

---

src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java
src/test/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntityTest.java

https://tools.hmcts.net/jira/browse/DMP-2157
This has been discussed with Sashi and the many-to-many between transcription and both cases and hearings was added to future-proof a potential requirement to link transcriptions to multiple cases/hearings. This isn't part of the heritage solution and isn't expected in the modernised one at this time.
When fetching the case related to any transcription the preferred route is to go via the hearing, using the "hearing_transcription_ae" table. If there isn't a link via hearing we check the direct link to case, via the "case_transcription_ae" table.
In both scenarios it's possible, but not expected, to get links to multiple cases. It has been decided that we should use only the first entry in the association tables until such a time as the …

DMP-2157 Handling multiple cases for transcriptions

---

src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationPostTest.java
src/integrationTest/java/uk/gov/hmcts/darts/annotation/AnnotationUploadServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArchiveRecordServiceIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/AnnotationStub.java
src/main/java/uk/gov/hmcts/darts/annotation/builders/AnnotationMapper.java
src/main/java/uk/gov/hmcts/darts/annotation/persistence/AnnotationPersistenceService.java
src/main/java/uk/gov/hmcts/darts/annotation/service/impl/AnnotationUploadServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/UnstructuredToArmProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/common/entity/AnnotationDocumentEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/AnnotationEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/ExternalObjectDirectoryEntity.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/annotation/service/impl/AnnotationUploadTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/UnstructuredToArmProcessorImplTest.java

https://tools.hmcts.net/jira/browse/DMP-2490
https://tools.hmcts.net/jira/browse/DMP-2488
https://tools.hmcts.net/jira/browse/DMP-2500
Removed persist and merge from annotation document and external object directory as it was causing issues when saving the annotation document to the eod and having the correct hearing attached
```
[ ] Yes
[ x] No
```

Dmp 2488 annotation document entity persist and merge

---

src/main/java/uk/gov/hmcts/darts/common/repository/SecurityGroupRepository.java
src/main/java/uk/gov/hmcts/darts/courthouse/exception/CourthouseApiError.java
src/main/java/uk/gov/hmcts/darts/courthouse/validation/CourthousePatchValidator.java
src/test/java/uk/gov/hmcts/darts/courthouse/validation/CourthousePatchValidatorTest.java

Fixing response codes when security groups and regions are not found
```
[ ] Yes
[x] No
```

DMP-2339: Fixing response codes when security groups and regions are not found

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/MediaRequestRepository.java

https://tools.hmcts.net/jira/browse/DMP-2262
- KEDA can skip a request because audio is not ready
- when the status is set back to OPEN the last modified date will be set
- then find OPEN requests by last modified date
- this means that specific request will be at the "back of the queue"
- this prevents multiple requests with audio that is not ready from hogging the KEDA jobs
```
[ ] Yes
[ ] No
```

DMP-2262 ATS KEDA re-process ordering fix

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerSearchPostTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdvancedSearchTest.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchUserIntTest.java
src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java
src/main/java/uk/gov/hmcts/darts/cases/exception/AdvancedSearchNoResultsException.java
src/main/java/uk/gov/hmcts/darts/cases/helper/AdvancedSearchRequestHelper.java
src/main/java/uk/gov/hmcts/darts/cases/model/GetCasesSearchRequest.java
src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java
src/main/java/uk/gov/hmcts/darts/cases/util/RequestValidator.java
src/main/java/uk/gov/hmcts/darts/common/repository/CourthouseRepository.java
src/main/java/uk/gov/hmcts/darts/common/repository/CourtroomRepository.java
src/main/resources/openapi/cases.yaml
src/test/java/uk/gov/hmcts/darts/cases/util/RequestValidatorTest.java

https://tools.hmcts.net/jira/browse/DMP-2582
- results limited to 501
- allowed the requestor to send in the courthouseId or courtroomId (in case we want to enhance the screen to allow it to send these in directly, due to a dropdown)
- i have created a request complexity calculator that takes a few things into account to decide whether enough criteria has been given, e.g. a judge name of 2 characters or less is not considered complex enough, and so would need to be combined with other items to be considered, please see code here https://github.com/hmcts/darts-api/pull/1268/files#diff-196111a004439aa49c440cc62372f141475407729c7a0abbc62a77d17a451e2aR33
- i have also changed the query to get the courthouseId or courtroomId up front, to get around the issue with the postgres optimiser not …

DMP-2582 - increase advanced search performance

---

src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchUserIntTest.java
src/main/java/uk/gov/hmcts/darts/dailylist/validation/DailyListPostValidator.java
src/test/java/uk/gov/hmcts/darts/dailylist/validation/DailyListPostValidatorTest.java

https://tools.hmcts.net/jira/browse/DMP-2609
Enabling message_id validation.  Fixing unrelated test. 
```
[ ] Yes
[x] No
```

DMP-2609: Enabling message_id validation

---

src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/UserControllerGetUsersIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/service/UserQueryTest.java
src/main/java/uk/gov/hmcts/darts/common/repository/UserAccountRepository.java
src/main/java/uk/gov/hmcts/darts/usermanagement/component/UserManagementQuery.java
src/main/java/uk/gov/hmcts/darts/usermanagement/component/impl/UserManagementQueryImpl.java
src/main/java/uk/gov/hmcts/darts/usermanagement/component/impl/UserQuerySpecifications.java
src/main/java/uk/gov/hmcts/darts/usermanagement/controller/UserController.java
src/main/java/uk/gov/hmcts/darts/usermanagement/service/UserManagementService.java
src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserManagementServiceImpl.java
src/main/resources/openapi/usermanagement.yaml
src/test/java/uk/gov/hmcts/darts/usermanagement/service/impl/usermanagement/service/UserManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-2661
- Filtering GET /admin/user by user_ids. 
- Rewrote the query using JPA specifications improve readability and to reduce the boiler plate of directly creating using CriteriaBuilders
- Removed courthouse_id from api as no longer needed. 
```
[ ] Yes
[x] No
```

DMP-2661: Filtering GET /admin/user by user_ids

---

src/functionalTest/java/uk/gov/hmcts/darts/usermanagement/SecurityGroupFunctionalTest.java

DMP-2660-security-groups-include-userids-fix
Fix functional test.
https://tools.hmcts.net/jira/browse/DMP-2660
```
[ ] Yes
[ x] No
```

DMP-2660-security-groups-include-userids-fix

---

src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/HandleOAuthCodeIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/authorisation/service/AuthorisationServiceTest.java
src/main/java/uk/gov/hmcts/darts/authorisation/model/UserState.java
src/main/java/uk/gov/hmcts/darts/authorisation/model/UserStateRole.java
src/main/java/uk/gov/hmcts/darts/authorisation/service/impl/AuthorisationServiceImpl.java
src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationCommonControllerTest.java
src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationExternalUserControllerTest.java
src/test/java/uk/gov/hmcts/darts/authentication/controller/impl/AuthenticationInternalUserControllerTest.java
src/test/java/uk/gov/hmcts/darts/authorisation/model/UserStateRoleTest.java
src/test/java/uk/gov/hmcts/darts/authorisation/model/UserStateTest.java

https://tools.hmcts.net/jira/browse/DMP-2750
- renaming the `Role` class to `UserStateRole`
- this was incorrectly using another model class named Role which is created by OpenAPI
```
[ ] Yes
[x] No
```

DMP-2750 Fixing swagger schema for /userstate endpoint

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArchiveRecordFileGeneratorImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmBatchProcessResponseFilesImpl.java

https://tools.hmcts.net/jira/browse/DMP-2898
Added logging of manifest file which is currently a temporary fix and added loggin of ARM response files
```
[ ] Yes
[x ] No
```

DMP-2898 Add logging of ARM manifest contents

---

src/functionalTest/java/uk/gov/hmcts/darts/retention/RetentionPolicyTypeFunctionalTest.java

Generalised a test assertion to eliminate reliance on response ordering.
```
[ ] Yes
[x] No
```

Fix indeterminate assertion

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/service/MediaRequestServiceTest.java
src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java

N/A
- only update media request status to COMPLETED once all generated files have been saved to storage
```
[ ] Yes
[x] No
```

ATS status update fix

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseMapperTest.java
src/integrationTest/java/uk/gov/hmcts/darts/hearings/service/GetHearingResponseMapperIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/data/EventTestData.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/EventStub.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/service/TranscriptionReportingRestrictionsMapperTest.java
src/main/java/uk/gov/hmcts/darts/audio/component/impl/AnnotationXmlGeneratorImpl.java
src/main/java/uk/gov/hmcts/darts/common/entity/EventEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/HearingReportingRestrictionsEntity.java
src/main/java/uk/gov/hmcts/darts/common/repository/CourtLogEventRepository.java
src/main/java/uk/gov/hmcts/darts/event/service/handler/base/EventHandlerBase.java
src/main/resources/db/migration/common/V1_296__fix_event_name_in_hearing_reporting_restrictions_view.sql
src/test/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileZipGeneratorImplTest.java
src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java

https://tools.hmcts.net/jira/browse/DMP-791
- amending "hearing_reporting_restrictions" view to include event_name from event_handler table
- fixing tests to use event name from associated event handler
```
[ ] Yes
[ ] No
```

DMP-791 Removing usages of event.event_name column

---

src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java

https://tools.hmcts.net/jira/browse/DMP-3033
Fixing sql query for transcriptions without courtrooms or court cases.
```
[ ] Yes
[x] No
```

DMP-3033: Fixing sql query for transcriptions without courtrooms or court cases.

---

README.md
bin/secrets-stg.sh
charts/darts-api/Chart.yaml
charts/darts-api/values.dev.template.yaml
charts/darts-api/values.yaml
src/main/resources/application.yaml

As part of DMP-3014 https://github.com/hmcts/darts-api/pull/1407/files we have removed ARM_URL from being populated by a secret. 
In this PR I'm doing some cleanup that I've missed to do in the previous PR

 DMP-3014 further cleanup after removing ARM_URL secret

---

charts/darts-api/Chart.yaml
charts/darts-api/values.stg.template.yaml
charts/darts-api/values.yaml

The `master` pipeline staging deployment needs the env vars defined in the chart for deploying a temporary `staging` pod, those are not picked up from flux so added `ARM_URL`

 DMP-3014 configure env var ARM_URL

---

charts/darts-api/Chart.yaml
charts/darts-api/values.dev.template.yaml
charts/darts-api/values.stg.template.yaml
charts/darts-api/values.yaml

https://tools.hmcts.net/jira/browse/DMP-2571
- also updating some misconfigured DARTS gateway URLs
```
[ ] Yes
[ ] No
```

DMP-2571 Updating usages of DARTS stub services to HTTP

---

src/main/java/uk/gov/hmcts/darts/usermanagement/validator/UserDeactivateNotLastInSuperAdminGroupValidator.java

N/A
Fixing sonar issue - https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&resolved=false&id=uk.gov.hmcts.reform%3Adarts-api&open=AY9x83p6FGrg1oQGen_P
The SUPER_ADMIN security group should always exists, throw an error if for some reason it doesn't
```
[ ] Yes
[x] No
```

Fixing sonar issue

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventControllerGetEventMappingByIdTest.java
src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/EventMappingServiceImpl.java
src/test/java/uk/gov/hmcts/darts/event/service/impl/EventMappingServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-3114
The has_events field returned by the GET /admin/event-mappings/id endpoint is now populated, based on whether there are any events linked to this event handler. 
```
[ ] Yes
[ x] No
```

DMP-3114 Populate has_events field for the GET /admin/event-mappings/id endpoint

---

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriptionWorkflowsIntTest.java
src/integrationTest/resources/tests/transcriptions/transcription_workflow/expectedAllWorkflowResponse.json
src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionCommentRepository.java
src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java
src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
src/main/resources/openapi/transcriptions.yaml
src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceGetWorkflowsTest.java

https://tools.hmcts.net/jira/browse/DMP-3051
Migrated comments are associated to a transcription but not associated to a transcription workflow. This change updates the `GET /admin/transcription-workflows` endpoint to return also these type of comments, which are currently ignored.
Because we didn't want to change the response schema, these new comments have been "hacked" into the existing response structure. This has been discussed with and approved by @davet1985 
Darts Portal handling of the endpoint response has been analysed with Dave and we believe it should not break when receiving the new data (migrated comments) returned by the endpoint
```
[ ] Yes
[x] No
```

DMP-3051 Updated /admin/transcription-workflows endpoint to return migrated comments

---

src/main/resources/db/migration/postgres/V1_0_0__create_schema.sql

Adding migration comments back in, broke the checksum in master
```
[ ] Yes
[x] No
```

Adding migration comments back in, broke the checksum in master

---

src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArmRetentionEventDateCalculatorImpl.java

https://tools.hmcts.net/jira/browse/DMP-3196
Added null check for EOD event date that is null first time around
```
[ ] Yes
[ x] No
```

DMP-3196 ARM event date calculation automated task is not updating the metadata

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DMP-2765
- using `GRACEFUL_SHUTDOWN_TIMEOUT` env var
```
[ ] Yes
[x] No
```

DMP-2765 Allowing spring graceful shutdown timeout to be configured

---

src/main/java/uk/gov/hmcts/darts/cases/mapper/CasesMapper.java
src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java

Remove seconds from the getCases response to match legacy.
Note, there are already tests to cover this scenario but the scheduled time was set to zero seconds. If the test data is changed to anything other than zero, it breaks the test as it starts using the seconds in the response. Therefore, the test data was changed to prove that this change has worked.

DMP-3217 Remove seconds from the getCases response

---

src/main/resources/db/migration/common/V1_311__remove_sorting_from_view.sql

https://tools.hmcts.net/jira/browse/DMP-3192
Removing sorting from view hearing_reporting_restrictions
```
[ ] Yes
[x] No
```

DMP-3192: Removing sorting from view hearing_reporting_restrictions

---

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAdminPostTranscriptionIntTest.java
src/main/resources/openapi/transcriptions.yaml

Rename endpoint to pluaralise the resource name, aligning with other APIs.
Note: FE already expects the pluralised resouce name.
```
[] Yes
[x] No
```

DMP:3346: Pluralise transcription hide endpoint

---

src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PostSecurityGroupIntTest.java
src/main/java/uk/gov/hmcts/darts/usermanagement/mapper/impl/SecurityGroupMapper.java

Set interpreter flag true when creating security groups with TRANSLATION_QA role via the Admin API.
```
[ ] Yes
[x] No
```

DMP-3276: Set interpreter flag true when creating TRANSLATION_QA groups

---

src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java

N/A
Returning 500 when an audio preview error occurs, instead of 404
```
[ ] Yes
[ ] No
```

Audio preview error response

---

src/testCommon/java/uk/gov/hmcts/darts/test/common/AwaitabilityUtil.java

`StopAndCloseHandlerTest.givenDarStopAndCloseEventReceivedAndHearingDoesNotExist_thenNotifyDarUpdateAndNotifyDarStopRecording` sometime fails on `dartsGateway.verifyReceivedNotificationType(3);`   it seems to be only finding the previous notification type 2.  The `await()` function can be given an alias so this PR just a stab in the dark to see if providing an alias fixes the issue.
```
[ ] Yes
[x] No
```

Attempting to fix flakey test

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetAnnotationsIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/retention/controller/RetentionControllerGetByCaseIdTest.java
src/main/java/uk/gov/hmcts/darts/annotation/controller/AnnotationController.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java
src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java
src/main/java/uk/gov/hmcts/darts/hearings/controller/HearingsController.java
src/main/java/uk/gov/hmcts/darts/retention/controller/RetentionController.java
src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java

[DMP-3305](https://tools.hmcts.net/jira/browse/DMP-3305)
Part 2 of DMP-3305, covering only addition of the `DARTS` role to various controller methods. The steer is the `DARTS` role should be added to all controller methods that already have `SUPER_ADMIN`, with the exclusion of admin-only endpoints (`/admin/...`).
Ref https://github.com/hmcts/darts-api/pull/1617 for Part 1, already merged.
```
[ ] Yes
[x] No
```

DMP-3305: Add DARTS role to controller methods

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerPreviewIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/repository/TransformedMediaRepositoryTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioPreviewTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/repository/HearingRepositoryIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/repository/TranscriptionDocumentTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBase.java
src/main/java/uk/gov/hmcts/darts/common/config/AsyncEventsConfig.java

1. Tests have been temporarily disabled that rely on redis & postgres containers while a bug is fixed in the pipeline. 
2. An attempt has been made to fix flaky tests. These tests fire in DartsEvents that result in multiple DAR notifications being sent asynchronously.  These events seem to be intermittently sent/received.  The config for the executors that process sending these notifications is a very basic one that creates a new Thread for every event. This is inefficient and not in-line with other hmcts projects.  As threads are requested/managed from the underlying platform this could account for the inability to reproduce this locally.
```
[ ] Yes
[x] No
```

Temp disable tests which user redis/postgres / attempted flakey DAR notify test fix

---

src/integrationTest/resources/tests/transcriptions/transcription/expectedResponse.json
src/integrationTest/resources/tests/transcriptions/transcription/expectedResponseNoCourtroom.json
src/integrationTest/resources/tests/transcriptions/transcription/expectedResponseNoHearing.json
src/integrationTest/resources/tests/transcriptions/transcription/expectedResponseNoUrgency.json
src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java
src/main/resources/openapi/transcriptions.yaml
src/test/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapperTest.java

https://tools.hmcts.net/jira/browse/DMP-3406
Adding `hide_request_from_requestor` to get transcription by ID response, it's required for the screen changes.
```
[ ] Yes
[ ] No
```

DMP-3406 Adding `hide_request_from_requestor` to get transcription by ID response

---

src/integrationTest/java/uk/gov/hmcts/darts/notification/service/NotificationServiceTest.java
src/main/java/uk/gov/hmcts/darts/audio/helper/TransformedMediaHelper.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java
src/main/java/uk/gov/hmcts/darts/notification/dto/SaveNotificationToDbRequest.java
src/main/java/uk/gov/hmcts/darts/notification/service/impl/NotificationServiceImpl.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-3027
[Do not schedule notifications for inactive users](https://github.com/hmcts/darts-api/commit/2175e4361c45517cc96d13030fad9f64d7849f12) 
- only check when user accounts are specified
- if email addresses are used no check for active accounts will happen
- minor test refactor
[Amending usages of SaveNotificationToDbRequest](https://github.com/hmcts/darts-api/commit/2baf5ba1656b8cbb922004e742d3b49a19c799a6) 
- to use "userAccountsToEmail" wherever possible
- to ensure that the active account check will be used
[Adding some JavaDoc to SaveNotificationToDbRequest](https://github.com/hmcts/darts-api/commit/fa0434e763e19215f674962ebfb5991cdd2245a4) 
- to make it clear that "userAccountsToEmail" should be used whenever possible
**Does this PR introduce …

DMP-3027 Schedule notifications for active users only

---

src/main/java/uk/gov/hmcts/darts/authorisation/controller/AuthorisationController.java
src/main/java/uk/gov/hmcts/darts/authorisation/controller/impl/AuthorisationControllerImpl.java
src/test/java/uk/gov/hmcts/darts/authorisation/controller/impl/AuthorisationControllerTest.java

https://tools.hmcts.net/jira/browse/DMP-2723
- renaming and moving class from authentication package into authorisation package
```
[ ] Yes
[ ] No
```

DMP-2723 GET /userstate to return 403 for users without an email address

---

src/main/java/uk/gov/hmcts/darts/audio/exception/AudioRequestsApiError.java

Small change to correct the title displayed in the API response for an `AUDIO_REQUESTS_102` error.
```
[ ] Yes
[x] No
```

DMP-3388: Correct the title for error AUDIO_REQUESTS_102

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventSearchControllerTest.java
src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/AdminEventSearchTest.java
src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java
src/main/java/uk/gov/hmcts/darts/event/service/EventSearchService.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/EventSearchServiceImpl.java
src/main/resources/openapi/event.yaml

Align the POST /admin/events/search response with the [LLD](https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1739306630#AdminPortalLLDRetentionManagement-PATCH/admin/retention-policy-types/{id}) by eliminating the top-level "events" attribute.
```
[ ] Yes
[X] No
```

DMP-3174: Align POST /admin/events/search response with LLD

---

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/AdminEventSearchTest.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/EventSearchServiceImpl.java

Fixing event search when the courthouse id array is empty in the request 
https://tools.hmcts.net/jira/browse/DMP-3649
```
[ ] Yes
[x] No
```

DMP-3649: Fixing event search 

---

src/main/java/uk/gov/hmcts/darts/audio/helper/TransformedMediaHelper.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-3613
Changed the media request start date time from UTC as stored in the DB to local time (BST) for the notification templates.
```
[ ] Yes
[x ] No
```

DMP-3613 Timestamp an hour out on e-mail notification

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdvancedSearchTest.java
src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java
src/test/java/uk/gov/hmcts/darts/cases/mapper/CasesMapperTest.java
src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java
src/test/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImplTest.java
src/testCommon/java/uk/gov/hmcts/darts/test/common/data/HearingTestData.java

https://tools.hmcts.net/jira/browse/DMP-3303
Hide isHearingActual false cases from darts portal in search results and on hearings on case screen
```
[ ] Yes
[ x] No
```

DMP-3303 Hide isHearingActual false cases from darts portal

---

src/functionalTest/java/uk/gov/hmcts/darts/datamanagement/DataManagementServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/service/TransientObjectDirectoryServiceTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DataManagementServiceStubImpl.java
src/main/java/uk/gov/hmcts/darts/audio/helper/TransformedMediaHelper.java
src/main/java/uk/gov/hmcts/darts/audio/helper/UnstructuredDataHelper.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentSingleCaseProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/common/service/TransientObjectDirectoryService.java
src/main/java/uk/gov/hmcts/darts/common/service/impl/TransientObjectDirectoryServiceImpl.java
src/main/java/uk/gov/hmcts/darts/datamanagement/api/DataManagementApi.java
src/main/java/uk/gov/hmcts/darts/datamanagement/api/impl/DataManagementApiImpl.java
src/main/java/uk/gov/hmcts/darts/datamanagement/model/BlobClientUploadResponse.java
src/main/java/uk/gov/hmcts/darts/datamanagement/model/BlobClientUploadResponseImpl.java
src/main/java/uk/gov/hmcts/darts/datamanagement/service/DataManagementService.java
src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/DataManagementServiceImpl.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/casedocument/service/impl/GenerateCaseDocumentSingleCaseProcessorImplTest.java
src/test/java/uk/gov/hmcts/darts/common/datamanagement/api/DataManagementFacadeImplTest.java
src/test/java/uk/gov/hmcts/darts/datamanagement/model/BlobClientUploadResponseImplTest.java
src/test/java/uk/gov/hmcts/darts/datamanagement/service/DataManagementServiceImplTest.java

The root cause of this bug is an out of memory condition that occurs during ATS processing when transferring the processed audio file to outbound storage. This is due to usage of `BinaryData.fromStream()`, which reads the entire stream into memory.
`master` branch was locally profiled whilst ATS was processing a media file. For convenience, a low memory ceiling of 250MB (`-Xmx250m`) was set such that large objects on the heap would cause the application to OOM.
At the far right of the chart, the application fails with `java.lang.OutOfMemoryError: Java heap space` at the moment `BinaryData.fromStream()` is invoked, and the associated `media_request` remains "stuck" with `request_status==PROCESSING`.
`dmp-3614-ats-large-file-fix` was then profiled with the same memory constraint.
The …

DMP-3614: Utilise io streams for file upload to outbound storage for ATS

---

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriptionWorkflowsIntTest.java
src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceGetWorkflowsTest.java

https://tools.hmcts.net/jira/browse/DMP-3632
Fix for when a transcription contains no workflows and an admin tries to load the transcription. 
Looking at the code, this should never actually happen on prod as a transcription will always have a workflow. However, on the lower environments, it appears there are some test transcriptions without workflows. 
```
[ ] Yes
[ x] No
```

DMP-3632 Fix index out of bounds error on empty transcription workflows

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerAddAudioRequestIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java
src/main/resources/openapi/audiorequests.yaml
src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplTest.java

DMP-1036
Replace hearingRepository.getReferenceById with service call
```
[ ] Yes
[x] No
```

DMP-1036: replace hearingRepository.getReferenceById with service call

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DMP-3494
Modified the annotation document max file to 20MB in bytes
```
[ ] Yes
[x ] No
```

DMP-3494 Uploading Large Annotation Documents Fails with 'There is a Problem with the Service' Error

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceGivenBuilder.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerAdminSearchTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseHearingsTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerSearchPostTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdminSearchTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdvancedSearchTest.java
src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsGetControllerTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseComposable.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java
src/main/java/uk/gov/hmcts/darts/common/entity/HearingEntity.java
src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListUpdater.java
src/test/java/uk/gov/hmcts/darts/cases/mapper/AdvancedSearchResponseMapperTest.java
src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java
src/testCommon/java/uk/gov/hmcts/darts/test/common/data/HearingTestData.java

https://tools.hmcts.net/jira/browse/DMP-3303
There was an issue with the 'is_hearing_actual' logic introduced whereby judges were being returned from hearings where the flag is set to false on the advanced search. 
To fix this, put an extra check in the HearingEntity, when not created from Daily List. 
```
[ ] Yes
[ ] No
```

DMP-3303 Hide judges when hearing is actual false

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerDownloadIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerPlaybackIntTest.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java
src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/datamanagement/component/impl/FileBasedDownloadResponseMetaData.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-3398
This PR is a first attempt to fix DMP-3398. As of now the endpoint does not set a "Content-length" header resulting in the server using chunked transfer encoding to transmit the data to the user.
It seems that specifying "Content-Length" is always preferable when downloading binary files like in our case compared to chunked encoding. See [here](https://stackoverflow.com/questions/2419281/content-length-header-versus-chunked-encoding) for example.
I'm not sure whether this change would improve the download speed and fix the issue, since it's not possible to reproduce this issue locally. But this seems to me a good improvement anyway.
```
[ ] Yes
[ x] No
```

DMP-3398 changed audio requests download endpoint to return "Content-length" header

---

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/SecurityGroupStub.java
src/integrationTest/java/uk/gov/hmcts/darts/usermanagement/controller/PatchSecurityGroupIntTest.java
src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/SecurityGroupServiceImpl.java

Bugfix per DMP-3674.
NOTE: This PR replaces https://github.com/hmcts/darts-api/pull/1819, which was failing to correctly report the Jenkins build status.

DMP-3674: Fix PATCH /admin/security-groups/<id> to correctly remove unassigned courthouses

---

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStubComposable.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriberTranscriptsIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriptionTest.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsIntTest.java
src/main/java/uk/gov/hmcts/darts/common/mapper/TranscriptionMapper.java
src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java
src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/YourTranscriptsQueryImpl.java
src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/darts/cases/mapper/TranscriptionMapperTest.java
src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java
src/test/java/uk/gov/hmcts/darts/hearings/mapper/TranscriptionMapperTest.java

https://tools.hmcts.net/jira/browse/DMP-3623
Transcriptions that are being migrated could have multiple records for the same transcription request. Only the latest should have an is_current = true value. Therefore, we only want to display this record on DARTS portal. 
```
[ ] Yes
[ x] No
```

DMP-3623 Only display transcriptions where is_current = true

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceGivenBuilder.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioTransformationServiceHandleKedaInvocationForMediaRequestsGivenBuilder.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/TransactionalUtil.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/CaseDocumentStub.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseRetrieval.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsPersistence.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/EntityGraphPersistence.java
src/main/java/uk/gov/hmcts/darts/admin/test/TestSupportController.java
src/main/java/uk/gov/hmcts/darts/annotation/persistence/AnnotationPersistenceService.java
src/main/java/uk/gov/hmcts/darts/audio/helper/TransformedMediaHelper.java
src/main/java/uk/gov/hmcts/darts/audio/helper/UnstructuredDataHelper.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audit/service/impl/AuditServiceImpl.java
src/main/java/uk/gov/hmcts/darts/cases/mapper/CasesMapper.java
src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/CaseManagementRetentionRepository.java
src/main/java/uk/gov/hmcts/darts/common/repository/CaseRetentionRepository.java
src/main/java/uk/gov/hmcts/darts/courthouse/service/impl/CourthouseServiceImpl.java
src/main/java/uk/gov/hmcts/darts/courthouse/service/impl/CourthouseUpdateMapperImpl.java
src/main/java/uk/gov/hmcts/darts/courthouse/validation/CourthousePatchValidator.java
src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListServiceImpl.java
src/main/java/uk/gov/hmcts/darts/dailylist/service/impl/DailyListUpdater.java
src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/InboundToUnstructuredProcessorSingleElementImpl.java
src/main/java/uk/gov/hmcts/darts/event/service/EventPersistenceService.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/RemoveDuplicateEventsProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/hearings/mapper/GetHearingResponseMapper.java
src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/SecurityGroupServiceImpl.java
src/main/java/uk/gov/hmcts/darts/usermanagement/service/impl/UserManagementServiceImpl.java

DMP-3323: 
Standardise to use springboot Transactional. The project was using mix of Java EE Transactional annotation and Springboot Transactional annotation. This PR makes consistent use for Sprintboot Transactional.
```
[ ] Yes
[x] No
```

DMP-3323: Standardise to use springboot Transactional

---

src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java
src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java

https://tools.hmcts.net/jira/browse/DMP-3809
Changes:
- Transformed Media - Search for transformed media: allowed -> added SuperUser to global access roles for `AudioRequestsController.searchForTransformedMedia`
- Transformed Media - View transformed:  allowed -> added SuperUser to global access roles for `AudioController.adminGetTransformedMedia`
- Transcripts - Manually move a request through workflow stages -> added SuperUser to global access roles for `TranscriptionController.updateTranscriptionAdmin`
The above are all `/admin` endpoints.
All other permissions seem correct to me
```
[ ] Yes
[x ] No
```

DMP-3809 updated permissions for SuperUser user

---

charts/darts-api/Chart.yaml
charts/darts-api/values.stg.template.yaml
charts/darts-api/values.yaml
src/integrationTest/java/uk/gov/hmcts/darts/arm/client/ArmTokenClientIntTest.java
src/main/resources/application.yaml

During QA it it sometimes important to see the full details of http requests and responses Darts is making to external services, e.g. ARM. 
This PR configures Feign clients to log headers, body, and metadata for both requests and responses, and replaces an existing config that is not working.
For now we will enable full logging only on Demo:
https://github.com/hmcts/sds-flux-config/pull/5343
Note:
we have [this ticket](https://tools.hmcts.net/jira/browse/DMP-3854) to remove this setting before we go to Prod to avoid sensitive data leak in logs:
as part of that ticket we can consider having different configs depending on the environments, so that full logging is enabled on Staging (which would help QA) but disabled on Prod
Example:
[
](url)
**Does this PR introduce a breaking change?** …

 NO_JIRA: log Darts feign clients requests/responses full details on Demo

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/service/CaseServiceAdvancedSearchTempTest.java
src/main/java/uk/gov/hmcts/darts/cases/helper/AdvancedSearchRequestHelper.java

https://tools.hmcts.net/jira/browse/DMP-3862
- it was not checking for hearing_is_actual set to true
- added failing test before fixing
- added test is in a temp class, due to the integration test disabling
```
[ ] Yes
[ ] No
```

DMP-3862 Fixing case search returning hearings for incorrect dates

---

src/main/java/uk/gov/hmcts/darts/audio/helper/UnstructuredDataHelper.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/datamanagement/api/DataManagementFacadeImpl.java
src/test/java/uk/gov/hmcts/darts/common/datamanagement/api/DataManagementFacadeImplTest.java

https://tools.hmcts.net/jira/browse/DMP-3773
Ticket was to change JOBS_LIST to be thread safe, but it looked like the logic was effectively meaning that the job to asynchronously copy a file to the unstructured datastore was holding up the response of the service anyway, so may as well be synchronous, so its been decided to remove the list.

DMP-3773 - remove jobs_list

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java
src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java

https://tools.hmcts.net/jira/browse/DMP-3907
Adding `SUPER_USER` to `/admin/events/:eventId` endpoint.
```
[ ] Yes
[ ] No
```

DMP-3907 Allowing SUPER_USER access to view event details

---

src/integrationTest/java/uk/gov/hmcts/darts/task/service/UnstructuredToArmBatchProcessorIntTest.java

https://tools.hmcts.net/jira/browse/DMP-3899
Added test to read the manifest file and check the contents does not contain the failed eod records
```
[ ] Yes
[x ] No
```

DMP-3899 Objects that fail to push to ARM should not have entries in the Manifest File when processed in BATCH Mode

---

src/main/java/uk/gov/hmcts/darts/cases/mapper/AdvancedSearchResponseMapper.java
src/test/resources/Tests/cases/AdvancedSearchResponseMapperTest/fourWithTwoSameCase/expectedResponse.json
src/test/resources/Tests/cases/AdvancedSearchResponseMapperTest/twoSameCase/expectedResponse.json

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/DMP-3908)
When a case contains multiple hearings, and only one of the hearing_is_actual flags is set to true and all of the others are set to false, these results are stripped out of the advanced search results, displaying just one hearing. However, the judges  fields are displaying the label 'Multiple'. It should only display the judge(s) for the hearing that is actual. 
 
!image (35).png|width=361,height=202,thumbnail!
Example case on demo with this issue is 'S20240187'.
 
```
[ ] Yes
[X] No
```

DMP-3908 - Judges and Defendants showing 'multiple' when case has hearing_is_actual flag set to false

---

src/main/java/uk/gov/hmcts/darts/util/AzureCopyUtil.java

DMP-3922
Reverting the changes for removal of access tier in azcopy
```
[ ] Yes
[x] No
```

dmp-3922: revert remove access tier flag from azcopy

---

src/main/java/uk/gov/hmcts/darts/task/runner/impl/AbstractLockableAutomatedTask.java
src/main/java/uk/gov/hmcts/darts/task/service/impl/LockServiceImpl.java
src/test/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/task/service/impl/LockServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-3909

DMP-3909 - extend shedlock timeout and add logging if breached.

---

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/EventRepositoryTest.java
src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/CleanupCurrentFlagEventProcessorImpl.java

https://tools.hmcts.net/jira/browse/DMP-3892
Updated getCurrentEventIdsToBeProcessed() to exclude processed event_ids that have multiple current eve_ids but are associated to different hearings
```
[ ] Yes
[X] No
```

Updated getCurrentEventIdsToBeProcessed() to exclude duplicate event_ids with unique hearing ids

---

src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTaskITest.java
src/main/java/uk/gov/hmcts/darts/common/entity/CourtCaseEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/DefenceEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/DefendantEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/EventEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/HearingEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/ProsecutorEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionCommentEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntity.java
src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java
src/main/java/uk/gov/hmcts/darts/task/api/AutomatedTaskName.java
src/main/java/uk/gov/hmcts/darts/task/runner/CanAnonymized.java
src/main/java/uk/gov/hmcts/darts/task/runner/impl/AbstractLockableAutomatedTask.java
src/main/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTask.java
src/main/java/uk/gov/hmcts/darts/task/service/impl/AdminAutomatedTasksServiceImpl.java
src/test/java/uk/gov/hmcts/darts/common/entity/CourtCaseEntityTest.java
src/test/java/uk/gov/hmcts/darts/common/entity/DefenceEntityTest.java
src/test/java/uk/gov/hmcts/darts/common/entity/DefendantEntityTest.java
src/test/java/uk/gov/hmcts/darts/common/entity/EventEntityTest.java
src/test/java/uk/gov/hmcts/darts/common/entity/HearingEntityTest.java
src/test/java/uk/gov/hmcts/darts/common/entity/ProsecutorEntityTest.java
src/test/java/uk/gov/hmcts/darts/common/entity/TranscriptionCommentEntityTest.java
src/test/java/uk/gov/hmcts/darts/common/entity/TranscriptionEntityTest.java
src/test/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTaskTest.java
src/test/java/uk/gov/hmcts/darts/task/service/impl/AdminAutomatedTasksServiceImplTest.java
src/testCommon/java/uk/gov/hmcts/darts/test/common/TestUtils.java

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/DMP-3923)
The expiry deletion automated task, named "CaseExpiryDeletion" and added by DMP-2543, is configured within the database automated_tasks table. In addition, there is a feature flag within application.yaml driven by an env var set in flux, named CASE_EXPIRY_DELETION_ENABLED
If the task is not enabled then we need to prevent it from being the subject of the following automated tasks endpoints, as follows:
- GET /admin/automated-tasks - do not include the "CaseExpiryDeletion" task in the response
- GET /admin/automated-tasks/\{task_id} - return 404 (AUTOMATED_TASK_NOT_FOUND)
- PATCH /admin/automated-tasks/\{task_id} - return 404 (AUTOMATED_TASK_NOT_FOUND)
- POST /admin/automated-tasks/\{task_id}/run - return 404 …

DMP-3923 - Hide CaseExpiryDeletion task if disabled by feature flag

---

src/main/java/uk/gov/hmcts/darts/common/entity/CourtCaseEntity.java

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/DMP-2559)
h3. Background:
The client has requested that we have a Dynatrace dashboard tile that proves that the Deletion Service is working. Outputs should show the number of cases expired in the selected timeframe.
h3. Technical:
When a case has been expired successfully, write the following log statement at INFO level:
{noformat}
"Case expired: cas_id={cas_id}, case_number={case_number}"{noformat}
Dynamic data:
||field||value||
|cas_id|Case id for the case that has been deleted |
|case_number|Case number for the case that has been deleted|
Please add the log entry in a service under the [log package|https://github.com/hmcts/darts-api/tree/master/src/main/java/uk/gov/hmcts/darts/log], exposing the service method via the "api" …

DMP-2559 - Write to log when a case is deleted due to expiry for Dynatrace purposes

---

src/integrationTest/resources/tests/retention/expectedResponse.json
src/main/resources/db/migration/common/V1_379__added_additional_retention_policy_type.sql

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/DMP-3947)
As agreed with HMCTS on 16/09/2024 in the review of Retention Migration Transformation spec, the following records need to be created in the *darts.retention_policy_type* table to allow migration to work.
This will be a flyway change and required to be deployed to both Application and Data Migration DBs.
 
|*policy_name*|*display_name*|*fixed_policy_key*|*duration*|
|DARTS Archive Permanent Retention|Archive Permanent|-3|30Y0M0D|
|DARTS Archive Standard Retention|Archive Standard|-4|7Y0M0D|
 
 
```
[ ] Yes
[X] No
```

DMP-3947 - Add 2 new Archive Retention Policies

---

src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java
src/main/java/uk/gov/hmcts/darts/hearings/controller/HearingsController.java
src/main/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionController.java

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/DMP-3942)
Translation QA should be able to view and download transcripts. 
Although the original requirement was for them to not be able to see the transcripts, they were set up in Legacy to see them and therefore we have to ensure it is like for like.
Translation QA *cannot* request transcripts
*Technical details*
The authorisation needs to be amended on the following endpoints to allow the TRANSLATION_QA role
* /cases/:caseId/transcripts
* /hearings/:hearingId/transcripts
* /transcriptions/:transcriptionId
* /transcriptions/:transcriptionId/document
Once the change has been made, please verify on the DARTS portal, with a translation QA user, that this allows access to transcriptions and transcription documents at case and hearing …

DMP-3942 - Translation QA should be able to view and download transcripts

---

src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/TranscriptionStub.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImplTest.java
src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java

https://tools.hmcts.net/jira/browse/DMP-3955
- if multiple APPROVED or WITH_TRANSCRIBER workflow records exist for a transcription it was being counted more than once
- amending the SQL query to take this into account
- using the same approach as the query which drives the data in the tabs
```
[ ] Yes
[ ] No
```

DMP-3955 Fixing transcriber transcripts count endpoint

---

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandlerTest.java

https://tools.hmcts.net/jira/browse/DMP-3867
- re-enabling all tests in `StopAndCloseHandlerTest` class
- adding a test to set up an existing case retention without a linked case_management_retention
- running "apply retention" to check the case retention records are handled correctly
```
[ ] Yes
[ ] No
```

DMP-3867 Investigation and testing for case retention without CMR record

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTaskITest.java
src/main/java/uk/gov/hmcts/darts/common/service/DataAnonymisationService.java
src/main/java/uk/gov/hmcts/darts/common/service/DataAnonymisationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTask.java
src/test/java/uk/gov/hmcts/darts/common/service/impl/DataAnonymisationServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTaskTest.java

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/DMP-3959)
When the case expiry job kicks in, the is_anonymised flags should be set on the events and transcription comments linked to a case. 
```
[ ] Yes
[X] No
```

DMP-3959 - Set is_anonymised on events and transcription comments when case expiry job runs

---

src/integrationTest/java/uk/gov/hmcts/darts/task/service/OutboundAudioDeleterProcessorTest.java
src/main/java/uk/gov/hmcts/darts/common/repository/TransformedMediaRepository.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-3201)
See the [Task automation LLD|https://tools.hmcts.net/confluence/pages/viewpage.action?pageId=1689786831#TaskautomationLLD-Markaudiotobedeletedinoutbounddatastore(andmoverequesttoexpired)] for more information.
Enhance the "OutboundAudioDeleter" automated task to expire transformed media which has it's related media set to is_hidden or is_deleted.
As well as expiring transformed media which has not been accessed within the configured number of days (default 2), the task should also check for media which has is_hidden or is_deleted set to true. This can be determined using the route via media_request and hearing to media, filtering by the media request start and end times. If any of the matching media has either flag set the the the …

DMP-3201 - Expire transformed media when original audio is hidden

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/repository/MediaRequestRepositoryIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/repository/MediaRequestRepositoryTest.java
src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandlerTest.java
src/main/java/uk/gov/hmcts/darts/audio/config/AudioTransformationServiceProperties.java
src/main/java/uk/gov/hmcts/darts/audio/service/MediaRequestService.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/MediaRequestRepository.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-3966
Added a list to ensure that if a media request that has audio only in inbound can be ignored and not hold up the processing of other requests.
added a check to make sure it doesn't loop forever.
Added a time check to try to avoid a scenario where the pod has been running for 30m and gets killed by keda, and leaves a media_request stuck in "PROCESSING".

DMP-3966 - allow ATS to go into a loop if multiple requests to process.

---

src/main/java/uk/gov/hmcts/darts/cases/mapper/AdvancedSearchResponseMapper.java
src/test/resources/Tests/cases/AdvancedSearchResponseMapperTest/fourWithTwoSameCase/expectedResponse.json
src/test/resources/Tests/cases/AdvancedSearchResponseMapperTest/twoSameCase/expectedResponse.json

Reverts hmcts/darts-api#1963 following design changes.
See https://tools.hmcts.net/jira/browse/DMP-3908 for more details

DMP-3908 - Revert "DMP-3908 - Judges showing 'multiple' when case has hearing_is_actual flag set to false"

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerAdminSearchTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseByIdTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerSearchPostTest.java
src/integrationTest/resources/tests/cases/CaseControllerAdminSearchTest/testOkIsAnonymised/expectedResponse.json

>[Jira](https://centralgovernmentcgi.atlassian.net/browse/DMP-3874)
The following PR covers tickets DMP-2911, DMP-2912 and DMP-3633:
* https://github.com/hmcts/darts-api/pull/1928
That change added fields `is_data_anonymised` and `data_anonymised_at` to the following endpoints:
* GET /cases/{case_id}
* POST /cases/search
* POST /admin/cases/search
However at the time of writing, the following related controller-level integration tests were disabled, so could not be updated to reflect the new endpoint behaviour:
* CaseControllerGetCaseByIdTest
* CaseControllerSearchPostTest
* CaseControllerAdminSearchTest
This task is to update these integration tests appropriately to reflect presence of the new response fields per the ACs listed on DMP-2911, DMP-2912 and DMP-3633.
Renablement of the above …

DMP-3874 - Update cases int tests to include anonymisation fields in API responses

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmBatchProcessResponseFilesImpl.java

https://tools.hmcts.net/jira/browse/DMP-3988
Added code to delete the response files CR, UF and or IL if there is no EOD found but they have been found in pairs
```
[ ] Yes
[x ] No
```

DMP-3988 Delete ARM's Response file when EOD is no longer available in DARTS

---

src/main/java/uk/gov/hmcts/darts/task/runner/impl/AbstractLockableAutomatedTask.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4011)
A transactional annotation should always be added to lower level i.e in the block of code which is expected to be transactional.
As of now a Transactional annotation has been added to AbstractLockableAutomatedTask.run which can have performance issue. 
Also due to one single use case failure the entire transaction is rolled back.
 
```
[ ] Yes
[X] No
```

DMP-4011 - Remove Transactional from AbstractLockableAutomatedTask

---

src/main/java/uk/gov/hmcts/darts/task/api/AutomatedTaskName.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-3994)
The manual deletion automated task, named "ManualDeletion" and added by DMP-2925, is configured within the database automated_tasks table. In addition, there is a feature flag within application.yaml driven by an env var set in flux, named MANUAL_DELETION_ENABLED
If the task is not enabled then we need to prevent it from being the subject of the following automated tasks endpoints, as follows:
-  GET /admin/automated-tasks - do not include the "ManualDeletion" task in the response
-  GET /admin/automated-tasks/\{task_id} - return 404 (AUTOMATED_TASK_NOT_FOUND)
-  PATCH /admin/automated-tasks/\{task_id} - return 404 (AUTOMATED_TASK_NOT_FOUND)
-  POST /admin/automated-tasks/\{task_id}/run - return 404 (AUTOMATED_TASK_NOT_FOUND)
This will …

DMP-3994 - Hide ManualDeletion task if disabled by feature flag

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmResponseFilesProcessorIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArmResponseFilesProcessSingleElementImpl.java
src/test/java/uk/gov/hmcts/darts/arm/component/impl/ArmResponseFilesProcessSingleElementImplTest.java

Improving performance by loading EOD statuses once on bean creation rather than every time the task processes an object.
This will reduce the number of SELECTs to the DB
```
[ ] Yes
[ x] No
```

NO-JIRA: performance fix around loading of eod statuses from DB

---

README.md
src/main/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileZipGeneratorHelperImpl.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/OutboundFileZipGeneratorHelperImplTest.java

DMP-4067
The Viq header was not getting updated if no TRIM was performed. Due to this the processed audio contained the Viqheader of original raw audio.
```
[ ] Yes
[x] No
```

dmp-4067: Viq Header not inserted if TRIM is not performed

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java
src/main/java/uk/gov/hmcts/darts/common/exception/DartsApiException.java
src/main/java/uk/gov/hmcts/darts/common/service/DataAnonymisationService.java
src/main/java/uk/gov/hmcts/darts/common/service/impl/DataAnonymisationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java
src/main/java/uk/gov/hmcts/darts/event/service/EventService.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/EventServiceImpl.java
src/main/resources/openapi/event.yaml
src/test/java/uk/gov/hmcts/darts/common/service/impl/DataAnonymisationServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/event/service/impl/EventServiceImplTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-3996)
This Git diff introduces new functionality for event obfuscation in the DARTS application. It adds tests for obfuscating event texts, updates existing service interfaces, and modifies the controller to include new API endpoints for this feature. Additionally, it implements error handling for scenarios when events are not found.
- **New Tests Added**: 
- `adminObfuscateEveByIdsSingle`: Tests obfuscation of a single event.
- `adminObfuscateEveByIdsMultiple`: Tests obfuscation of multiple events.
- `adminObfuscateEveByIdsNotFound`: Tests API response when trying to obfuscate a non-existent event.
- `adminObfuscateEveByIdsNotSuperAdmin`: Ensures that non-super admin users cannot obfuscate events.
- **New Methods in Service Interface**:
- …

DMP-3996 - Manual obfuscation of event text endpoint

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetEventByCaseIdTest.java
src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsGetEventsControllerTest.java
src/main/java/uk/gov/hmcts/darts/cases/mapper/EventMapper.java
src/main/java/uk/gov/hmcts/darts/hearings/mapper/GetEventsResponseMapper.java
src/main/resources/openapi/cases.yaml
src/main/resources/openapi/hearings.yaml
src/test/java/uk/gov/hmcts/darts/cases/mapper/EventMapperTest.java
src/test/java/uk/gov/hmcts/darts/hearings/mapper/GetEventsResponseMapperTest.java
src/test/resources/Tests/cases/CaseServiceTest/testGetEventsByCase/expectedResponse.json
src/test/resources/Tests/cases/CasesMapperTest/testMapToEvents/expectedResponseAnonymised.json
src/test/resources/Tests/cases/CasesMapperTest/testVersionedEvents/expectedResponseForVersionedEvents.json
src/test/resources/Tests/cases/CasesMapperTest/testVersionedEvents/expectedResponseForVersionedEventsWithGroupedEventsIsCurrentSet.json
src/test/resources/Tests/cases/CasesMapperTest/testVersionedEvents/expectedResponseForZeroIdVersionedEvents.json

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4024)
This Git diff introduces changes across several files, primarily focusing on the addition of an `is_data_anonymised` field to event-related data structures, tests, and OpenAPI specifications. It also includes minor refactoring and adjustments to formatting.
- **Added `is_data_anonymised` Field**:
- New field added to JSON responses in `CaseControllerGetEventByCaseIdTest` and `HearingsGetEventsControllerTest`.
- Reflected in OpenAPI specifications for cases and hearings.
- **Event Mapping Updates**:
- The `EventMapper` and `GetEventsResponseMapper` classes have been updated to set the new `is_data_anonymised` property based on the corresponding entity's value.
- **Test Cases Enhancements**:
- New test cases in `EventMapperTest` and …

DMP-4024: Update endpoints to GET events to add is_data_anonymised

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/validation/MediaHideOrShowValidator.java
src/main/java/uk/gov/hmcts/darts/common/exception/CommonApiError.java
src/main/java/uk/gov/hmcts/darts/common/exception/DartsApiException.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/EventServiceImpl.java
src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionServiceImpl.java
src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
src/main/java/uk/gov/hmcts/darts/transcriptions/validator/TranscriptionDocumentHideOrShowValidator.java
src/main/resources/openapi/common.yaml
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/audio/validation/MediaHideOrShowValidatorTest.java
src/test/java/uk/gov/hmcts/darts/event/service/impl/EventServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionServiceTest.java
src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/transcriptions/validator/TranscriptionDocumentHideOrShowValidatorTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-3996)
This update focuses on improving the error handling in the software by replacing specific error types with a more generalized `CommonApiError`. This makes the code cleaner and more consistent across different parts of the system. 
- **Error Type Replacement**: 
- The term `DartsApiException.DartsApiErrorCommon` was replaced with `CommonApiError` in various files.
- **New Error Definitions**: 
- Two new common error types were added: `FEATURE_FLAG_NOT_ENABLED` and `NOT_FOUND`, providing clearer messaging for certain error conditions.
- **Improved Consistency**: 
- The changes ensure that all parts of the codebase consistently use the new common errors, enhancing maintainability.
- **Updates Across Multiple Files**: 
- The changes were …

DMP-3996: Common Error Codes

---

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerRequestTranscriptionIntTest.java
src/main/java/uk/gov/hmcts/darts/authorisation/api/AuthorisationApi.java
src/main/java/uk/gov/hmcts/darts/authorisation/api/impl/AuthorisationApiImpl.java
src/main/java/uk/gov/hmcts/darts/authorisation/service/AuthorisationService.java
src/main/java/uk/gov/hmcts/darts/authorisation/service/impl/AuthorisationServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/UserAccountRepository.java
src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionNotifications.java
src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionNotificationsTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4088)
The recent updates in the code involve modifications to how user accounts with specific roles are retrieved from courthouses. The changes allow for the exclusion of certain users when fetching this information, enhancing the functionality of the authorisation process.
- **Method Update**: The method `getUsersWithRoleAtCourthouse` now accepts an additional parameter to exclude specific users from the results.
- **Interface Changes**: The interfaces for both `AuthorisationApi` and `AuthorisationService` have been updated to include the new exclusion functionality.
- **Implementation Adjustments**: The implementation classes reflect the changes made in the interfaces, ensuring consistency.
- **Database Query Update**: The repository …

DMP-4088: Requester receiving approval email for their own requests

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerDownloadIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBase.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationTestConfiguration.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/PostgresIntegrationBase.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/ArmServiceStubImpl.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DataManagementServiceStubImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java
src/main/java/uk/gov/hmcts/darts/common/datamanagement/component/impl/FileBasedDownloadResponseMetaData.java
src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/DataManagementServiceImpl.java

[[N/A](https://tools.hmcts.net/jira/browse/DMP-3830)](https://tools.hmcts.net/jira/browse/DMP-3830)
An extension to the PR https://github.com/hmcts/darts-api/pull/2170. This PR includes an integration test for blob download and temp file removal
```
[ ] Yes
[x ] No
```

DMP-3830 - Add integration test for blob temp file download

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerDownloadIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBase.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationTestConfiguration.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/PostgresIntegrationBase.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/ArmServiceStubImpl.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DataManagementServiceStubImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsController.java
src/main/java/uk/gov/hmcts/darts/common/datamanagement/component/impl/FileBasedDownloadResponseMetaData.java
src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/DataManagementServiceImpl.java

https://tools.hmcts.net/jira/browse/DMP-3830
Some fixes for DMP-3830 noticed during a (very late) code-review before starting the QA of the ticket
Fixes:
- fixed temp file used in `GET /audio-requests/download` endpoint not being cleaned-up 
- fixed potential memory leak caused by wrapped input stream not being closed by `FileInputStreamWrapper`
I was not able to add straightforward tests for the fixes above, all the scenarios above are not easily testable as it stands unfortunately
```
[ ] Yes
[ x] No
```

 DMP-3830 fixes to the new auto-cleanup mechanism

---

src/functionalTest/java/uk/gov/hmcts/darts/cases/CasesFunctionalTest.java
src/functionalTest/java/uk/gov/hmcts/darts/events/PostEventsFunctionalTest.java
src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1OkJsonAndXml/expectedResponse.json
src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1OkJsonAndXml/expectedResponse2.json
src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1_duplicate_ok/expectedResponse.json
src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1_ok/expectedResponse.json
src/main/java/uk/gov/hmcts/darts/admin/test/TestSupportController.java
src/main/java/uk/gov/hmcts/darts/common/entity/DailyListEntity.java
src/main/resources/db/migration/common/V1_399__v72_1.sql

Apply v71.1 datamodel updates per https://github.com/hmcts/darts-api/pull/2201.
Due to the addition of new foreign keys `event_linked_case_court_case_fk` and `event_linked_case_event_fk`, a datafix is included to remove any `event_linked_case` records that point to non-existing cases or events:
```sql
DELETE FROM event_linked_case
WHERE cas_id IN (
SELECT elc.cas_id
FROM event_linked_case elc
LEFT JOIN court_case cc ON elc.cas_id = cc.cas_id
WHERE cc.cas_id IS NULL
);
DELETE FROM event_linked_case
WHERE eve_id IN (
SELECT elc.eve_id
FROM event_linked_case elc
LEFT JOIN event eve ON elc.eve_id = eve.eve_id
WHERE eve.eve_id IS NULL
);
```
The problematic data exists in staging due to the functional tests not cleaning up the `event_linked_case` table after deleting cases/events during test …

DMP-4184: Apply v72.1 datamodel updates

---

Jenkinsfile_CNP
README.md
bin/ci/pr-labels.sh
bin/ci/process-pr-labels.sh
charts-dev-overrides/README.md
charts-dev-overrides/enable_darts_portal/Chart.yaml
charts-dev-overrides/enable_darts_portal/values.dev.template.yaml
charts/darts-api/Chart.yaml
charts/darts-api/values.dev.template.yaml
charts/darts-api/values.stg.template.yaml

N/A
Enabled a DARTS portal dev deployment by adding the "enable_darts_portal" label.
Including support for a `enable_darts_fullstack` label, which can deploy all other DARTS services alongside the API.
This works by overriding the `values.dev.template.yaml` and `Chart.yaml` files as required to deploy the DARTS portal as well as the API.
As this doesn't required any committed changes to the main charts directory, it shouldn't cause any issues with helm releases in other environments.
```
[ ] Yes
[ ] No
```

Optional DARTS portal deployment on dev

---

src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/MediaLinkedCaseRepository.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioUploadServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4156
This branch is from the branch for DMP-3986, which contains changes required by this ticket. See related PR:
https://github.com/hmcts/darts-api/pull/2215
Note: there's already an existing integration test that is verifying the new functionality: `AudioControllerAddAudioMetadataIntTest.addAudioMetadataDifferentCases()`.
```
[ ] Yes
[x ] No
```

DMP-4156: Enhance add audio duplicate checking to use media_linked_case source

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoGetProfileEntitlementsIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/client/ArmRpoClient.java
src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ProfileEntitlementResponse.java
src/main/java/uk/gov/hmcts/darts/arm/exception/ArmRpoException.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApi.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java
src/main/resources/application-local.yaml
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetProfileEntitlementsTest.java

Implement the ARM RPO getProfileEntitlements service layer.
This PR includes the corresponding Feign client which will be integration tested as part of wider ticket https://tools.hmcts.net/jira/browse/DMP-4143.
```
[ ] Yes
[x] No
```

DMP-4135: Implement getProfileEntitlements for ARM RPO

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiGetProductionOutputFilesIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/client/ArmRpoClient.java
src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ProductionOutputFilesRequest.java
src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ProductionOutputFilesResponse.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetProductionOutputFilesTest.java

Implement the ARM RPO getProductionOutputFiles service layer.
This PR includes the corresponding Feign client which will be integration tested as part of wider ticket https://tools.hmcts.net/jira/browse/DMP-4143.
```
[ ] Yes
[x] No
```

DMP-4140: Implement getProductionOutputFiles for ARM RPO

---

README.md
docker-compose-local.yml
src/integrationTest/java/uk/gov/hmcts/darts/testutils/PostgresIntegrationBase.java

https://tools.hmcts.net/jira/browse/DMP-3964
Using postgres v16 in the local docker build.
When using the new version you might need to remove your docker volume. Stop the postgres image and then use the following commands
```
docker volume ls
docker volume rm <darts api db volume>
```
Then you should be able to start the DB using docker once again.
```
[ ] Yes
[ ] No
```

DMP-3964 Using postgres v16 in docker

---

charts/darts-api/Chart.yaml
charts/darts-api/values.yaml

NOJIRA
Default the `darts-portal` chart to disabled to ensure no pods are created on environments other than dev.
```
[ ] Yes
[ ] No
```

Default darts-portal chart to not enabled

---

src/main/java/uk/gov/hmcts/darts/task/runner/impl/AudioLinkingAutomatedTask.java
src/test/java/uk/gov/hmcts/darts/task/runner/impl/AudioLinkingAutomatedTaskTest.java

No jira
When the performance testing was carried out on the audio linking job, it was difficult to work out which audio had been linked through which event. The logs have been improved to make it clearer what has happened. 
```
[ ] Yes
[ x] No
```

Improve logs for audio linking job

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/AbstractBatchCleanupArmResponseFilesServiceIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/DartsBatchCleanupArmResponseFilesServiceIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/DetsBatchCleanupArmResponseFilesServiceIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/helper/ArmResponseFileHelper.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/BatchCleanupArmResponseFilesServiceCommon.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/DartsBatchCleanupArmResponseFilesServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/DetsBatchCleanupArmResponseFilesServiceImpl.java
src/main/java/uk/gov/hmcts/darts/task/api/AutomatedTaskName.java
src/main/java/uk/gov/hmcts/darts/task/config/DartsBatchCleanupArmResponseFilesAutomatedTaskConfig.java
src/main/java/uk/gov/hmcts/darts/task/config/DetsBatchCleanupArmResponseFilesAutomatedTaskConfig.java
src/main/java/uk/gov/hmcts/darts/task/runner/impl/BatchCleanupArmResponseFilesAutomatedTask.java
src/main/java/uk/gov/hmcts/darts/task/runner/impl/DetsCleanupArmResponseFilesAutomatedTask.java
src/main/resources/application.yaml
src/main/resources/db/migration/common/V1_413__DETSCleanupArmResponseFiles_automated_task.sql
src/test/java/uk/gov/hmcts/darts/arm/service/impl/AbstractBatchCleanupArmResponseFilesServiceCommonTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/DartsBatchCleanupArmResponseFilesServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/DetsBatchCleanupArmResponseFilesServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/task/runner/impl/BatchCleanupArmResponseFilesAutomatedTaskTest.java
src/test/java/uk/gov/hmcts/darts/task/runner/impl/DetsCleanupArmResponseFilesAutomatedTaskTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-3485)
Once ARM produces the response files, DETS-ARM pull response automated job will start pulling the response files and process it.
As soon as the files associated with a transaction are processed, DARTS should delete the corresponding response files from ARM's response folder.
Along with Synchronous deletion an automated job will also be required to make sure any deletion which is missed during Synchronous deletion are handled in a asynchronous way. The purpose of the job is to clean up data from  ARM response folders Asynchronously.
* Create flyway script for new automated task
** Task name : DETSCleanupArmResponseFiles
** Batchsize : 4000
** Cron : Runs daily at 23:27
** Make sure the job is disabled
* Create Automated job in darts-api …

DMP-3485: Automated task for Deletion from ARM's response folder

---

src/main/java/uk/gov/hmcts/darts/datamanagement/service/impl/DataManagementServiceImpl.java
src/test/java/uk/gov/hmcts/darts/datamanagement/service/DataManagementServiceImplTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-2402)
This Git diff introduces enhancements to the `DataManagementServiceImpl.java` file by improving the checksum retrieval logic for blobs stored in Azure. Additionally, it updates the corresponding test cases in `DataManagementServiceImplTest.java` to verify the new functionality.
- **New Imports**: Added import for `BlobProperties` and `StringUtils`.
- **Checksum Retrieval Logic**: 
- The checksum retrieval now first checks the blob's properties for `ContentMd5`.
- If `ContentMd5` is `null` or empty, it checks the blob's metadata for a "checksum" entry.
- If a valid checksum is found in metadata, it is returned; otherwise, an exception is thrown.
- **New Test Case**: 
- A new test method …

DMP-2402: Upload audio to azure directly from DARTS Proxy

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/DetsToArmBatchProcessResponseFilesIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchProcessResponseFilesImpl.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4315)
In DETS to ARM pull process, once the response files are processed and the checksum validation is successful, the record in EOD is marked as 'ARM_RPO_PENDING' alongwith deleting the object from DETS location as well. 
We will have to remove the DETS deletion logic from the current process. The DETS Deletion logic will be put into a new ticket which will delete the DETS object asynchronously.
 
+*Steps:*+
Remove the following logic from DETS to ARM Pull Response logic:
* {color:#172b4d}Fetch the corresponding DETS record from EOD using the ARM record. Key would be med_id or trd_id. {color}
* {color:#172b4d}delete the object from  DETS storage using the EDO entity retrieved in previous step{color}
* {color:#172b4d}delete the record from …

DMP-4315: Remove synchronous DETS Cleanup logic

---

charts/darts-api/values.dev.template.yaml
charts/darts-api/values.stg.template.yaml
src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java
src/integrationTest/resources/application-intTest.yaml
src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java
src/main/resources/application-local.yaml
src/main/resources/application.yaml

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4251)
*Add feature flag*
If this flag has not already been created, add the new config to DARTS API application.yaml, to act as a feature flag for event obfuscation
{code:java}
darts:
event-obfuscation:
enabled: ${EVENT_OBFUSCATION_ENABLED:false} {code}
Check the env var "EVENT_OBFUSCATION_ENABLED" exists in flux for the darts-api service staging environment, set to true. Ensure it is not set or set to false for all other environments.
The feature should also be enabled on the dev and staging pipeline deployments, in order to facilitate testing.
*Hide endpoint*
The _POST /admin/events/obfuscate_ endpoint should be hidden if the feature is not enabled. Any requests should received a 501 not implemented response.
h3. *Acceptance Criteria*
*AC1 …

DMP-4251: Introduce and use event obfuscation feature flag

---

src/main/java/uk/gov/hmcts/darts/common/config/security/SecurityConfig.java
src/main/resources/db/migration/common/V1_418__functional_test_user.sql

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4273)
**Note: Code was tested manually due to complexities in automated internal JWT checks with gracefully handled exceptions.
This follows the existing pattern for this class (Which current does not have any dedicated automated tests associated to it relying on API integration tests for this verification)**
We are seeing a large number of BadJwtExceptions on the staging environment.
This is impacting defect investigation and cluttering up the logs.
!image-2024-11-07-13-01-32-683.png|width=496,height=184!
{code:java}
org.springframework.security.oauth2.jwt.BadJwtException: An error occurred while attempting to decode the Jwt: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
at …

DMP-4273: A large number of BadJwtExceptions are being thrown on staging

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetAdminMediasByIdIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseHearingsTest.java
src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsControllerGetTranscriptsTest.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriptionTest.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImpl.java
src/main/java/uk/gov/hmcts/darts/cases/mapper/HearingEntityToCaseHearing.java
src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionDocumentRepository.java
src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java
src/main/java/uk/gov/hmcts/darts/hearings/service/impl/HearingsServiceImpl.java
src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionDownloader.java
src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/darts/cases/mapper/HearingEntityToCaseHearingTest.java
src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionDownloaderTest.java
src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4304
This PR fixes the following issues
- Audio file detail still visible to admin after the file is deleted by manual deletion job
- Transcription request for deleted document is still visible on the user portal
**Changes**
[Prevent viewing deleted audio files](https://github.com/hmcts/darts-api/commit/7f283524f338492dc8913e33a0ac34c6f8fdbd66)
[Fix for preventing viewing of transcription requests with deleted documents](https://github.com/hmcts/darts-api/commit/8a679a511dd909313087914ed2283b7accbef062) 
- document is not fetched by default once deleted due to the SQLRestriction
- override this with a custom query to detect hidden documents, even when deleted
- if any are found, the transcription request should not be viewable
- extending this fix …

DMP-4304 Fixing hidden/deleted audio and transcripts still accessible

---

src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/ProcessE2EArmRpoPendingAutomatedTaskIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/TriggerArmRpoSearchServiceImpl.java
src/main/java/uk/gov/hmcts/darts/log/api/LogApi.java
src/main/java/uk/gov/hmcts/darts/log/api/impl/LogApiImpl.java
src/main/java/uk/gov/hmcts/darts/log/service/ArmLoggerService.java
src/main/java/uk/gov/hmcts/darts/log/service/impl/ArmLoggerServiceImpl.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/TriggerArmRpoSearchServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/log/service/impl/ArmLoggerServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4376
Added dynatrace logging for ARM RPO Search and Polling
```
[ ] Yes
[ x] No
```

DMP-4376 Add ARM RPO logs for Dynatrace

---

src/main/java/uk/gov/hmcts/darts/arm/helper/ArmResponseFileHelper.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmMissingResponseCleanupImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/BatchCleanupArmResponseFilesServiceCommon.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/DartsBatchCleanupArmResponseFilesServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/DetsBatchCleanupArmResponseFilesServiceImpl.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/AbstractBatchCleanupArmResponseFilesServiceCommonTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmMissingResponseCleanupImplTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/DartsBatchCleanupArmResponseFilesServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/DetsBatchCleanupArmResponseFilesServiceImplTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4461)
Introduces several updates primarily focused on refining logging practices within the codebase. Key changes include adjustments to the logging prefix, modifications to the constructor parameters, and consistent application of the new logging prefix in various logging statements.
- **Logging Prefix Update**: 
- A new variable  `loggingPrefix` was added to replace instances where `manifestFilePrefix`  was used for log prefixs.
- **Constructor Modifications**: 
- Constructors in several classes have been updated to accept an additional `loggingPrefix` parameter, streamlining the logging process.
- **Log Statement Changes**: 
- Numerous logging statements have been adjusted to utilize the new `loggingPrefix` for consistency and clarity.
- …

DMP-4461: ArmMissingResponseFile Task not processing any EOD records

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiCreateExportBasedOnSearchResultsTableIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiGetExtendedSearchesByMatterIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRpoPollServiceIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ExtendedSearchesByMatterResponse.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApi.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImpl.java
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiCreateExportBasedOnSearchResultsTableTest.java
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetExtendedSearchesByMatterTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4462
Fixed issue where the wrong production value was being passed in. Changed it to get the production name from the getExtendedSearchesByMatter which is then passed to createExportBasedOnSearchResultsTable.
```
[ ] Yes
[ x] No
```

DMP-4462 ARM RPO createExportBasedOnSearchResultsTable failing

---

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/CleanupCurrentFlagEventProcessorImplTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/EventStub.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/CleanupCurrentFlagEventProcessorImpl.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DMP-4351
Legacy events should remain with the is_current flag set to the same status as they were migrated as. This change skips events where the original created date is earlier than the modernised go live date. 
```
[ ] Yes
[ x] No
```

DMP-4351 Do not change is_current status on legacy events

---

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/EventRepositoryTest.java
src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java

https://tools.hmcts.net/jira/browse/DMP-4269
When message id or event id is null, we want to skip the duplicate tidy up logic, otherwise we could end up incorrectly deleting events.
```
[ ] Yes
[ x] No
```

DMP-4269 Skip deleting duplicate events when criteria is null

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/helper/DataStoreToArmHelperIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/AbstractArmBatchProcessResponseFilesIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmApiServiceIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRpoPollServiceIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/DetsToArmBatchPushProcessorIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFiles.java

https://tools.hmcts.net/jira/browse/DMP-4445
Removed saving the response files to temporary space as its no longer required
```
[ ] Yes
[ x] No
```

DMP-4445 ARM Pull response file - Remove saving response files to Tempworkspace

---

src/main/java/uk/gov/hmcts/darts/arm/model/record/armresponse/ArmResponseInputUploadFileRecord.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFiles.java
src/test/java/uk/gov/hmcts/darts/arm/model/record/armresponse/ArmResponseInputUploadFileRecordTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesImplTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4487)
Moved the json parser to use LocalDateTime instead of OffsetDateTime as the provided json does not contain an offset
```
[ ] Yes
[X] No
```

DMP-4487: The IU file is not getting processed by the ProcessARMResponse job

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/AbstractArmBatchProcessResponseFilesIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFiles.java
src/test/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4492
The current ARM Missing response use case doesn't consider if all the response files are missing. As of now it only covers if partial response files are present. Added logic to cover for this usecase as well.
Also the error status in the code was wrong so updated it to ARM_MISSING_RESPONSE.
```
[ ] Yes
[x] No
```

DMP-4492 : ARM Missing Response files bug fix

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerPreviewIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/service/AudioPreviewTest.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java
src/main/java/uk/gov/hmcts/darts/audio/exception/AudioApiError.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioPreviewServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/validation/MediaIdValidator.java
src/main/resources/openapi/audio.yaml
src/test/java/uk/gov/hmcts/darts/audio/validation/MediaIdValidatorTest.java
src/testCommon/java/uk/gov/hmcts/darts/test/common/data/MediaTestData.java

https://tools.hmcts.net/jira/browse/DMP-4386
On audio preview, if the audio start and end date is equal (or the start date is after the end date) then throw a 422 error. 
```
[ ] Yes
[ x] No
```

DMP-4386 Handle zero second audio on preview

---

src/main/java/uk/gov/hmcts/darts/task/runner/impl/AssociatedObjectDataExpiryDeletionAutomatedTask.java
src/main/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTask.java

The CaseExpiryDeletionAutomatedTask automated tasks did not have the Transactional annotation in the right place, and could result in data ending up in a stuck state if a pod could exited whilst the task was running. This PR fixes this. 
```
[ ] Yes
[ x] No
```

Fix transactional on CaseExpiryDeletionAutomatedTask

---

src/main/resources/openapi/cases.yaml

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4370)
This Git Diff modifies the `cases.yaml` file in the OpenAPI specification. It primarily focuses on adjusting the `maxLength` constraints for several string fields.
- **Removed `maxLength` constraint**:
- `courthouse`: maxLength removed (was 255).
- **Updated `maxLength` constraints**:
- `courtroom`: changed from 255 to 64.
- `judge_name`: changed from 255 to 2000.
- `defendant_name`: changed from 255 to 2000.
- `event_text_contains`: changed from 255 to 2000. 
These changes allow for more flexible data input for certain fields while removing restrictions on others.
```
[ ] Yes
[X] No
```

DMP-4370: Amend case search validation

---

build.gradle

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4455)
This Git diff reflects a change in the `build.gradle` file, specifically in the SonarQube configuration section. The modification involves the removal of an exclusion pattern from the `sonar.coverage.exclusions` property.
- **File Changed**: `build.gradle`
- **Modification**: 
- Removed `**/darts/**` from the `sonar.coverage.exclusions` property.
- **Remaining Exclusions**: 
- `**/entity/*`
- `**/dto/*`
- `**/AzureCopyUtil.java`
- `**/TestSupportController.java`
- **Other Properties**: No changes were made to other SonarQube properties in the section.
```
[ ] Yes
[X] No
```

DMP-4455: DEV ONLY: Sonar no longer reporting DARTS API code coverage

---

src/main/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImpl.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioTransformationServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4385
Updated the ATS filtering to filter out audio files that have less than a second start and end time, start or end time is null or start time is after end time
```
[ ] Yes
[x ] No
```

DMP-4385 Filter out 0 second audios from ATS processing

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/DetsToArmBatchPushProcessorIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchPushProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java
src/main/java/uk/gov/hmcts/darts/common/util/EodHelper.java
src/main/java/uk/gov/hmcts/darts/task/config/DetsToArmPushAutomatedTaskConfig.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/arm/service/UnstructuredToArmBatchProcessorTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchPushProcessorImplTest.java
src/test/java/uk/gov/hmcts/darts/common/service/impl/EodHelperMocks.java
src/test/java/uk/gov/hmcts/darts/util/LogUtil.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4499)
This commit introduces several enhancements to the `DetsToArmBatchPushProcessorImpl` class, particularly focusing on improving the batch processing of DETS records to ARM. Key changes include the introduction of asynchronous processing and the configuration for the number of threads used in batch processing.
- **Asynchronous Processing**: 
- The `processDetsToArm` method now utilizes `Callable` to process batches asynchronously, improving performance.
- An `AtomicInteger` is used to track batch counts in a thread-safe manner.
- **Configuration Changes**:
- A new configuration class `DetsToArmPushAutomatedTaskConfig` has been added to specify the number of threads for processing.
- The `application.yaml` file has been updated to set the …

DMP-4499: Performance Testing - Automated Tasks - DetsToArm - SELECT darts takes 4.5 minutes

---

bin/generateBatchArmResponses.sh
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/AbstractArmBatchProcessResponseFilesIntTest.java
src/integrationTest/resources/tests/arm/service/ArmBatchResponseFilesProcessorTest/ValidResponses/InputUploadFile.rsp
src/main/java/uk/gov/hmcts/darts/arm/config/ArmDataManagementConfiguration.java
src/main/java/uk/gov/hmcts/darts/arm/model/record/armresponse/ArmResponseInputUploadFileRecord.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFiles.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/arm/service/ArmBatchProcessResponseFilesImplTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchProcessResponseFilesImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4571
Changed the way the ARM Input Upload response file is parsed so it is a string in the json object which is then then formatted into an offsetdatetime
```
[ ] Yes
[ x] No
```

DMP-4571 Reading of IU File failure

---

src/main/resources/db/migration/common/V1_426__assign_region_to_burnley_mags.sql
src/main/resources/db/migration/common/V1_427__unset_object_id_for_moj_language_shop.sql

Flyway changes to courthouse_region_ae and security_group.
Migrations verified against clean local DB and a locally-cloned staging DB.
Note no changes are required for the following ticket requirement, as the `dm_group_s_object_id` value is already correct:
```
Update the dm_group_s_object_id to "1217075880002900" for the group_name of "moj_appeal_court_users"
```

DMP-4577: Flyway changes to courthouse_region_ae and security_group

---

src/integrationTest/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImplTest.java
src/main/java/uk/gov/hmcts/darts/authorisation/component/UserIdentity.java
src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImpl.java
src/main/java/uk/gov/hmcts/darts/common/config/security/SecurityConfig.java
src/main/java/uk/gov/hmcts/darts/common/entity/listener/UserAuditListener.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4381)
This Git diff introduces new functionality to the `UserIdentity` component to handle user account retrieval more effectively. It adds methods for optional user account retrieval and includes corresponding unit tests to verify their behavior. The changes enhance the existing user identity handling by implementing a more robust approach to querying user accounts based on JWT tokens.
- **New Method in UserIdentity Interface**: 
- `Optional<UserAccountEntity> getUserAccountOptional(Jwt jwt);` is added to retrieve a user account optionally.
- **Implementation in UserIdentityImpl**:
- Refactored `getUserAccount` to utilize `getUserAccountOptional`, throwing an exception if no account is found.
- Added logic to `getUserAccountOptional` to …

DMP-4381: Automatically update createdBy and lastModifiedBy when persisting entities to the database

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/AbstractArmBatchProcessResponseFilesIntTest.java
src/integrationTest/resources/tests/arm/service/ArmBatchResponseFilesProcessorTest/InvalidResponses/InputUploadFile.rsp
src/main/java/uk/gov/hmcts/darts/arm/model/record/armresponse/ArmResponseInputUploadFileRecord.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFiles.java

https://tools.hmcts.net/jira/browse/DMP-4471
When the IU file cannot be parsed, the manifest files status is set to ARM_RESPONSE_PROCESSING_FAILED
```
[ ] Yes
[ x] No
```

Dmp 4471 ARM IU file cleanup set status

---

src/integrationTest/java/uk/gov/hmcts/darts/common/controller/CourthouseApiTest.java
src/main/java/uk/gov/hmcts/darts/courthouse/service/impl/CourthouseServiceImpl.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4619)
This Git diff reflects changes made to the `CourthouseApiTest.java` and `CourthouseServiceImpl.java` files in a Java project. The modifications primarily involve the order of courthouse names in the tests and the addition of sorting logic in the service implementation.
- Added sorting logic to the `mapFromEntitiesToExtendedCourthouses` method to sort the list of `extendedCourthouses` by courthouse name in ascending order:
```java
extendedCourthouses.sort((o1, o2) -> o1.getCourthouseName().compareTo(o2.getCourthouseName()));
```
```
[ ] Yes
[X] No
```

DMP-4619: Courthouse search results look to default sorting to last updated date

---

charts/darts-api/Chart.yaml
charts/darts-api/values.yaml
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRpoPollServiceIntTest.java
src/integrationTest/resources/application-intTest.yaml
src/main/java/uk/gov/hmcts/darts/arm/client/model/UpdateMetadataRequest.java
src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/BaseRpoResponse.java
src/main/java/uk/gov/hmcts/darts/arm/client/model/rpo/ResponseStatusMessage.java
src/main/java/uk/gov/hmcts/darts/arm/enums/ArmRpoResponseStatusCode.java
src/main/java/uk/gov/hmcts/darts/arm/helper/ArmRpoHelper.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApi.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/util/ArmRpoUtil.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/arm/helper/ArmRpoHelperMocks.java
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiAddAsyncSearchTest.java
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiCreateExportBasedOnSearchResultsTableTest.java
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetExtendedSearchesByMatterTest.java
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetIndexesByMatterIdTest.java
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetProductionOutputFilesTest.java
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiGetProfileEntitlementsTest.java
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiRemoveProductionTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/arm/util/ArmRpoUtilTest.java

https://tools.hmcts.net/jira/browse/DMP-4655
1) Added UUID and _CSV to production name so that it is always unique each time its polled and pass to  createExportBasedOnSearchResultsTable and  getExtendedProductionsByMatter
2) Changed createExportBasedOnSearchResultsTable catch feign response to handle bad request by using e.contentUTF8(), convert to BaseRpoRresponse and then pass to processCreateExportBasedOnSearchResultsTableResponse
3) Set thread sleep to 60 seconds
4) Added NonNull check to updateMetadata
```
[ ] Yes
[x] No
```

DMP-4655 ARM RPO Amendments

---

src/main/java/uk/gov/hmcts/darts/task/model/AutomatedTaskTrigger.java
src/main/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImpl.java
src/test/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImplTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4554)
This Git diff introduces a new class `AutomatedTaskTrigger` that extends `TriggerTask`, and modifies the `AutomatedTaskServiceImpl` and its test class to utilize this new class. The changes facilitate better handling and cancellation of automated tasks by integrating the new trigger mechanism.
- **New Class Added:** 
- `AutomatedTaskTrigger` created in `AutomatedTaskTrigger.java`, which extends `TriggerTask`.
- Includes a constructor to initialize `AutomatedTask` along with its `Trigger`.
- **Modifications in `AutomatedTaskServiceImpl`:**
- Replaced instances of `TriggerTask` with `AutomatedTaskTrigger` in method checks and logic.
- Updated methods to retrieve and cancel automated tasks with the new trigger class.
- **Updates in …

DMP-4554: Upgrade Spring Boot to 3.4.1

---

src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/AssociatedObjectDataExpiryDeletionAutomatedTaskITest.java
src/main/java/uk/gov/hmcts/darts/task/runner/impl/AssociatedObjectDataExpiryDeletionAutomatedTask.java
src/test/java/uk/gov/hmcts/darts/task/runner/impl/AssociatedObjectDataExpiryDeletionAutomatedTaskTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4682)
The logic spec'd out in DMP-4358 had a slight error. This is what it said: 
* add a check if the object's retain_until_ts matches the object's event_dt {color:#FF0000}minus{color} 100 years (event-date-adjustment-years from application.yaml) in external_object_directory table for ARM record i.e. the event_date for the object is calculated and its same as object's retain_until_ts before DELETING the object.
When it should have said:
* add a check if the object's retain_until_ts matches the object's event_dt {color:#FF0000}plus{color} 100 years (event-date-adjustment-years from application.yaml) in external_object_directory table for ARM record i.e. the event_date for the object is calculated and its same as object's retain_until_ts …

DMP-4682: Associated object automated task should add 100 years when comparing event date with retain until date

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/component/impl/AudioRequestBeingProcessedFromArchiveQueryImplIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/repository/EodRepositoryHasMediaNotBeenCopiedFromInboundStorageIntTest.java
src/main/java/uk/gov/hmcts/darts/audio/component/impl/AudioRequestBeingProcessedFromArchiveQueryImpl.java
src/main/java/uk/gov/hmcts/darts/audio/component/impl/AudioRequestBeingProcessedFromArchiveQueryResultRowMapper.java
src/main/java/uk/gov/hmcts/darts/audio/model/AudioRequestBeingProcessedFromArchiveQueryResult.java
src/main/java/uk/gov/hmcts/darts/common/enums/ObjectRecordStatusEnum.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/MediaRequestServiceImplTest.java

[DMP-4168](https://tools.hmcts.net/jira/browse/DMP-4168)
- using the same logic as checking archived audio for the DARTS portal
- EOD record for stored in ARM, and no record for unstructured or DETS
- deprecating `DISABLED` status as it's not used
```
[ ] Yes
[ ] No
```

DMP-4168 Fixing logic for archived audio email

---

charts/darts-api/Chart.yaml
charts/darts-api/values.yaml
src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiCreateExportBasedOnSearchResultsTableIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArpRpoApiGetMasterIndexFieldByRecordClassSchemaIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRpoPollServiceIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApi.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/ArmRpoPollService.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/entity/ArmRpoExecutionDetailEntity.java
src/main/java/uk/gov/hmcts/darts/task/config/ArmRpoPollAutomatedTaskConfig.java
src/main/java/uk/gov/hmcts/darts/task/runner/impl/ArmRpoPollingAutomatedTask.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiCreateExportBasedOnSearchResultsTableCheckTest.java
src/test/java/uk/gov/hmcts/darts/arm/rpo/impl/ArmRpoApiCreateExportBasedOnSearchResultsTableTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/task/runner/impl/ArmRpoPollAutomatedTaskTest.java

https://tools.hmcts.net/jira/browse/DMP-4667
https://tools.hmcts.net/jira/browse/DMP-4658
1. Add a new field 'production_name' to arm_rpo_execution_details entity.
2. When the 'CreateExportBasedOnSearchResultsTable' is called and the result is 200, updates the production_name in arm_rpo_execution_detail table.
3. Before calling 'getExtendedProductionsByMatter', uses 'production_name' from arm_rpo_execution_detail. 
4. In the beginning of ARMPolling job, add a check if the current execution state is 11 (getExtendedProductionsByMatter)  then skip the following endpoints and call getExtendedProductionsByMatter:
getExtendedSearchesByMatter
getMasterIndexFieldByRecordClassSchema
createExportBasedOnSearchResultsTable
5. When the 'CreateExportBasedOnSearchResultsTable' called for the first time …

Dmp 4667 armrpo get extended productions by matter change polling logic

---

src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1OkJsonAndXml/expectedResponse.json
src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1OkJsonAndXml/expectedResponse2.json
src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1_duplicate_ok/expectedResponse.json
src/integrationTest/resources/tests/dailylist/DailyListServiceTest/insert1_ok/expectedResponse.json
src/main/java/uk/gov/hmcts/darts/common/entity/AnnotationDocumentEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/DailyListEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/MediaEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/ObjectRetrievalQueueEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/TranscriptionDocumentEntity.java
src/main/resources/db/migration/common/V1_443__adding_storage_id_to_some_tables.sql

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4707)
Add *storage_id* attribute as char varying to the following 5 tables:
 
This is similar change as data_ticket attribute.
```
[ ] Yes
[X] No
```

DMP-4707: Flyway changes - Adding storage_id for 5 tables for Data Migration

---

bin/migrate-dets.sh

A convenience script to simplify the process of applying flyway migrations to DETS.
See https://tools.hmcts.net/confluence/display/DMP/Applying+Flyway+changes+to+Migration for accompanying documentation.

Add DETS migration script

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioMetaDataNoSessionIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioMetadataIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioMetadataMediaLinkIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioNoSessionIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerAddAudioWithMetadataIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAttachTranscriptIntTest.java
src/integrationTest/resources/application-intTest.yaml
src/main/java/uk/gov/hmcts/darts/audio/config/AudioConfigurationProperties.java
src/main/java/uk/gov/hmcts/darts/audio/exception/AudioApiError.java
src/main/java/uk/gov/hmcts/darts/audio/validation/AddAudioFileValidator.java
src/main/java/uk/gov/hmcts/darts/audio/validation/AddAudioMetaDataValidator.java
src/main/resources/application.yaml
src/main/resources/openapi/audio.yaml
src/test/java/uk/gov/hmcts/darts/audio/validation/AddAudioMetaDataValidatorTest.java

https://tools.hmcts.net/jira/browse/DMP-4712
Remove audio config from DARTS API that is no longer required. This is handled in DARTS Gateway instead. 
```
[ ] Yes
[ x] No
```

DMP-4712 Remove redundant audio config

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/DetsToArmBatchPushProcessorIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/task/service/UnstructuredToArmBatchProcessorIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/component/impl/ArchiveRecordFileGeneratorImpl.java
src/main/java/uk/gov/hmcts/darts/arm/helper/DataStoreToArmHelper.java
src/main/java/uk/gov/hmcts/darts/arm/model/batch/ArmBatchItem.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchPushProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/UnstructuredToArmBatchProcessorImpl.java
src/test/java/uk/gov/hmcts/darts/arm/component/impl/ArchiveRecordFileGeneratorImplTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/ArchiveRecordServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/DetsToArmBatchPushProcessorImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4705
Added code to set the eod manifest file to null if the push fails
```
[ ] Yes
[ x] No
```

Dmp 4705 fix issue with manifest file getting set when push failed

---

src/main/java/uk/gov/hmcts/darts/common/controller/HiddenReasonsController.java
src/main/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityGroupController.java
src/main/java/uk/gov/hmcts/darts/usermanagement/controller/SecurityRoleController.java

Some of our `@RestControllers` are not conditional on the `api-pod` property, meaning their associated endpoints will be active when the darts-api-function pods are running, which is undesirable.
This PR address this issue, see comments on the Jira ticket for analysis performed.
```
[ ] Yes
[X] No
```

DMP-4640: Make all RestControllers conditional on property

---

src/integrationTest/java/uk/gov/hmcts/darts/noderegistration/controller/NodeRegistrationControllerTest.java
src/main/java/uk/gov/hmcts/darts/common/service/RetrieveCoreObjectService.java

https://tools.hmcts.net/jira/browse/DMP-4653
Primarily fixing courtroom name unique constraint violations.
- plus hearing, case and judge constraint violations
- increasing the attempts made by the Retryable annotation, up to 10 attempts retying every 50ms, spending a total of 500ms before failing
- most of these are used by requests via the SOAP service and if a failure did happen it would be retried by the external system
- creating a new transaction so that the retried method has the latest data, before it was stuck with a stable view when retrying and never doing anything
- adding javadoc for all methods in `RetrieveCoreObjectService` to help explain how they are used
- deprecating some methods as they are only used in tests
- removing the Retryable annotation from some methods …

DMP-4653 Fixing courtroom name unique constraint violation

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/rpo/ArmRpoApiCreateExportBasedOnSearchResultsTableIntTest.java

https://tools.hmcts.net/jira/browse/DMP-4658
Added a test to prove AC2 as its not possible to test ARM not sending back a request with the polling duration
```
[ ] Yes
[x] No
```

DMP-4658 ARM RPO - Add max retry logic for RPO polling

---

src/main/java/uk/gov/hmcts/darts/audit/model/RevisionInfo.java

Starting the application locally (with the `local` spring profile) performs a DDL validation check on startup. This ensures the modelled Entities are aligned with the underlying schema.
Some misalignment in the `RevisionInfo` entity causes validataion to fail. This PR addresses this.
```
[ ] Yes
[x] No
```

Align RevisionInfo entity to schema, such that ddl validation passes

---

src/main/resources/db/migration/common/V1_453__rasso_disable_global_access.sql

This PR covers Part 1 of DMP-4723, which is limited to disabling global_access for the `rasso_users` security group.
```
[ ] Yes
[x] No
```

DMP-4723: Disable global_access for rasso_users security group

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRpoPollServiceIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRpoServiceIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/service/ArmRpoPollService.java
src/main/java/uk/gov/hmcts/darts/arm/service/ArmRpoService.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java
src/main/java/uk/gov/hmcts/darts/task/config/ArmRpoPollAutomatedTaskConfig.java
src/main/java/uk/gov/hmcts/darts/task/runner/impl/ArmRpoPollingAutomatedTask.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/task/runner/impl/ArmRpoPollAutomatedTaskTest.java

https://tools.hmcts.net/jira/browse/DMP-4646
Added batching to ArmRpoPolling automated task
```
[ ] Yes
[ x] No
```

Dmp 4646 implement batching arm rpo polling automated task

---

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/EventRepositoryTest.java
src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerAdminGetVersionsByEventIdTest.java
src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java
src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java
src/main/java/uk/gov/hmcts/darts/event/controller/EventsController.java
src/main/java/uk/gov/hmcts/darts/event/mapper/EventMapper.java
src/main/java/uk/gov/hmcts/darts/event/service/EventService.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/EventServiceImpl.java
src/main/resources/openapi/event.yaml
src/test/java/uk/gov/hmcts/darts/event/mapper/EventMapperTest.java
src/test/java/uk/gov/hmcts/darts/event/service/impl/EventServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-3409
New endpoint to get all versions associated to an event.
If event id is zero, it means it is the first version of an event which is a bug in XHIBIT and therefore exclude these from the query otherwise millions of events would be pulled back. 
```
[ ] Yes
[x ] No
```

DMP-3409 Build admin get event versions endpoint

---

bin/migrate-dets.sh

Improving the safety of the dets migration script by adding guardrails to:
* Ensure master branch is locally checked out, as we shouldn't be performing migrations from any other branch
* Ensure master branch is in a clean working state with no pending changes, as we should only be applying migrations that have gone through the review process and have been merged to master
The script now also includes the mandatory `./gradlew clean assemble` step, whereas before the onus was on the user to run that as a prereq.
This prevents some issues that almost bit me when performing DETS migrations.
```
[ ] Yes
[x] No
```

Safety improvements to migrate-dets.sh

---

src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java
src/test/java/uk/gov/hmcts/darts/cases/controller/CaseControllerTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-3945)
The Git diff shows a modification in the `casesSearchPost` method within the `CaseController.java` file. Specifically, the case number handling has been updated to avoid trimming null values, which may improve the handling of case numbers in search requests.
- **Modification in Case Number Handling**: 
- The line that sets the `caseNumber` changed from using `StringUtils.trimToNull` to directly using `advancedSearchRequest.getCaseNumber()`. 
- **Impact**: 
- This change may allow for case numbers that are not trimmed, preventing the potential loss of leading or trailing spaces which could be significant in some cases.
```
[ ] Yes
[X] No
```

DMP-3945: Whitespaces could cause duplicate cases to be created

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CasesControllerGetTranscriptsTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepositoryTest.java
src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsControllerGetTranscriptsTest.java
src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionRepository.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4872)
This Git diff shows updates made to the `TranscriptionRepositoryTest` and `TranscriptionRepository` classes in the `uk.gov.hmcts.darts` project. The changes primarily involve enhancing the testing of transcription retrieval methods and refining the SQL queries used for fetching transcriptions.
- **Imports**: Added `assertThat` from AssertJ for better assertions.
- **Setup Method**: Refactored the `setupData` method to directly assign `hearingEntity` instead of declaring it as a new local variable.
- **New Methods**: Introduced `createStandardTranscriptionWithDocument` to streamline the creation of standard transcriptions.
- **Tests Enhanced**:
- Updated assertions in tests to use `assertThat` instead of `assertEquals`.
- Added new …

DMP-4872: Automatic transcript from legacy with no document shown in case transcripts 

---

src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/AddAsyncSearchServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/CreateExportBasedOnSearchResultsTableServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetExtendedProductionsByMatterServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetExtendedSearchesByMatterServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetIndexesByMatterIdServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetMasterIndexFieldByRecordClassSchemaServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetRecordManagementMatterServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/GetStorageAccountsServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/rpo/impl/RemoveProductionServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/AbstractArmBatchProcessResponseFiles.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoPollServiceImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AdminMediaServiceImpl.java
src/test/java/uk/gov/hmcts/darts/authorisation/util/AuthorisationUnitOfWorkTest.java
src/test/java/uk/gov/hmcts/darts/event/service/impl/EventDispatcherImplTest.java
src/test/java/uk/gov/hmcts/darts/task/service/impl/AutomatedTaskServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4633
Fixed sonar complaints:
- Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation.
- Change this instance-reference to a static reference
- Rename this variable to not match a restricted identifier.
- Use java.nio.file.Files#delete here for better messages on error conditions
```
[ ] Yes
[x] No
```

Dmp 4633 resolve sonar issues6

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerSearchPostTest.java
src/main/java/uk/gov/hmcts/darts/cases/util/RequestValidator.java
src/main/resources/openapi/cases.yaml
src/test/java/uk/gov/hmcts/darts/cases/util/RequestValidatorTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4826)
The recent changes to the `CaseControllerSearchPostTest.java`, `RequestValidator.java`, and OpenAPI specifications introduce additional validation tests for the `/cases/search` endpoint. Specifically, the changes enforce minimum length requirements for several fields in the request body, ensuring they are between 3 and 2000 characters. These updates enhance the robustness of the API by preventing invalid requests from being processed.
- **New Test Cases Added:**
- Tests to validate the length of `event_text_contains`, `judge_name`, `defendant_name`, and `courthouse` fields. Each must be at least 3 characters long.
- Each test checks for a "400 Bad Request" response when the corresponding field is less than the required length.
- …

DMP-4826: Return error when search does not meet minimum characters to prevent performance impacting queries from running

---

src/integrationTest/java/uk/gov/hmcts/darts/retention/controller/RetentionControllerPostRetentionIntTest.java
src/main/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/common/exception/DartsApiException.java
src/main/resources/openapi/cases.yaml
src/main/resources/openapi/retentions.yaml
src/test/java/uk/gov/hmcts/darts/audio/component/impl/OutboundFileProcessorImplTest.java
src/test/java/uk/gov/hmcts/darts/cases/util/RequestValidatorTest.java

Some exception messages were adding a full stop where the log formatter was also adding a full stop, so ended up with double full stop in the logged out message. This change fixes this. 
```
[ ] Yes
[ x] No
```

Tidy up exception log formatting

---

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/SentencingRemarksAndRetentionPolicyHandlerTest.java
src/main/java/uk/gov/hmcts/darts/event/service/handler/SentencingRemarksAndRetentionPolicyHandler.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4890)
The provided Git Diff indicates updates to the `SentencingRemarksAndRetentionPolicyHandlerTest` and `SentencingRemarksAndRetentionPolicyHandler` classes in a Java project. The primary change involves updating the transcription urgency from `STANDARD` to `WORKING_DAYS_12` in both the test and the service handler classes.
- **File Changes:**
- `SentencingRemarksAndRetentionPolicyHandlerTest.java`
- Added import for `WORKING_DAYS_12` urgency.
- Updated test assertion to check for `WORKING_DAYS_12` instead of `STANDARD`.
- `SentencingRemarksAndRetentionPolicyHandler.java`
- Changed the import from `STANDARD` to `WORKING_DAYS_12`.
- Updated the transcription urgency ID set in transcription request details from `STANDARD` to …

DMP-4890: update auto transcript urgency to up to 12 days 

---

src/integrationTest/java/uk/gov/hmcts/darts/task/service/OutboundAudioDeleterProcessorTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/UserAccountStub.java
src/main/java/uk/gov/hmcts/darts/audio/service/OutboundAudioDeleterProcessor.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/TransformedMediaRepository.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4883)
This diff introduces significant changes to the `OutboundAudioDeleterProcessorTest` class and related components in the Darts audio processing module. Key modifications include the addition of parameterized tests for security group handling and the refactoring of deletion logic in the `OutboundAudioDeleterProcessorImpl` class.
- **Test Class Modifications**:
- Added parameterized tests to handle different `SecurityGroupEnum` values, particularly excluding "MEDIA_IN_PERPETUITY".
- Refactored setup methods and replaced direct field injection with Mockito's `@MockitoSpyBean` for better test isolation and mocking.
- **New Test Cases**:
- Implemented tests to verify that media requests owned by security groups other than …

DMP-4883: SUPER_ADMIN and SUPER_USER roles should not prevent transformed media expiry

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventSearchControllerTest.java
src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/AdminEventSearchTest.java
src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTaskITest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/stubs/DartsDatabaseStub.java
src/main/java/uk/gov/hmcts/darts/casedocument/mapper/CourtCaseDocumentMapper.java
src/main/java/uk/gov/hmcts/darts/cases/helper/AdvancedSearchRequestHelper.java
src/main/java/uk/gov/hmcts/darts/cases/mapper/EventMapper.java
src/main/java/uk/gov/hmcts/darts/cases/service/impl/CloseOldCasesProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/common/entity/EventEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/EventLinkedCaseEntity.java
src/main/java/uk/gov/hmcts/darts/common/entity/HearingEntity.java
src/main/java/uk/gov/hmcts/darts/common/repository/HearingRepository.java
src/main/java/uk/gov/hmcts/darts/event/mapper/EventEntityToCourtLogMapper.java
src/main/java/uk/gov/hmcts/darts/event/mapper/EventMapper.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/CleanupCurrentFlagEventProcessorImpl.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/OutboundFileZipGeneratorHelperImplTest.java
src/test/java/uk/gov/hmcts/darts/common/helper/MediaLinkedCaseHelperTest.java
src/test/java/uk/gov/hmcts/darts/common/service/impl/DataAnonymisationServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/common/util/CommonTestDataUtil.java
src/test/java/uk/gov/hmcts/darts/event/mapper/EventMapperTest.java
src/testCommon/java/uk/gov/hmcts/darts/test/common/data/EventTestData.java
src/testCommon/java/uk/gov/hmcts/darts/test/common/data/builder/TestEventEntity.java
src/testCommon/java/uk/gov/hmcts/darts/test/common/data/builder/TestHearingEntity.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4795)
This Git diff primarily involves refactoring the handling of `HearingEntity` collections in various Java classes, changing from `List<HearingEntity>` to `Set<HearingEntity>`. This change aims to improve data integrity when managing relationships between events and hearings, reducing issues related to duplication and deletion of entries.
- **Refactoring of Hearing Entities**:
- Changed the type for `hearingEntities` from `List` to `Set` in `EventEntity`, which prevents data integrity issues during insertion/deletion.
- Updated methods across multiple tests and classes to accommodate the switch to `Set`, including `getHearingEntities()` and other related methods.
- **Controller and Mapper Adjustments**:
- The `EventSearchControllerTest` …

DMP-4795: DataIntegrityViolationException when deleting duplicate events

---

src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java
src/test/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapperTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4975)
The recent changes to the `TranscriptionResponseMapper.java` file primarily involve refactoring and enhancements to the mapping logic for various entities related to transcriptions. The updates introduce new helper methods to streamline the mapping process and improve code readability. These changes include the addition of a method to retrieve the first non-null object from a list of objects and modifications to existing methods for better handling of null values.
- **New Method Added**:
- `getFirstNotNull(T... objects)`: A utility method that returns the first non-null object from the provided arguments.
- **Refactoring of Mapping Logic**:
- Updated the `mapTranscriptionDocumentMarkedForDeletion` method to utilize new helper methods …

DMP-4975: Handle transcription documents marked for deletion linked through case_transcription_ae

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/MediaControllerAdminPostMediaIntTest.java
src/main/resources/openapi/audio.yaml

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4832)
This diff introduces new functionality to the `MediaControllerAdminPostMediaIntTest` Java class, specifically adding a test to validate the handling of a null value for the `isHidden` field in `MediaHideRequest`. Additionally, it updates the OpenAPI specification to reflect changes related to the required field for `MediaHideRequest`.
- **New Test Case Added**: 
- A test method `postAdminHideMediaId_usingNullIsHidden_shouldBeRejected` is introduced to ensure that a null value for `isHidden` in `MediaHideRequest` is properly rejected, returning a 400 error with a specific violation message.
- **Modification in MediaHideRequest**:
- The `is_hidden` property in the `MediaHideRequest` schema is now marked as a required field.
- **OpenAPI …

DMP-4832: Validate "isHidden: null" in hide media request

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerTest.java
src/main/java/uk/gov/hmcts/darts/event/mapper/EventMapper.java
src/main/resources/openapi/event.yaml
src/test/java/uk/gov/hmcts/darts/event/mapper/EventMapperTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4915)
The recent changes to the codebase involve updates to the `EventsControllerTest`, `EventMapper`, and `EventMapperTest` files. The modifications primarily focus on adding new assertions and mappings related to the `eventStatus` and `isDataAnonymised` fields, ensuring that these properties are correctly handled and tested in the API responses.
- **New Assertions in EventsControllerTest**:
- Added assertions to verify that `isDataAnonymised` and `eventStatus` properties of the event entity are accurately reflected in the API response.
- **Mapping Enhancements in EventMapper**:
- Updated the `mapToAdminGetEventsResponseFor` method to include the `eventStatus` mapping along with the existing `isDataAnonymised`.
- **OpenAPI Specification …

DMP-4915: update backend to make is_data_anonymised and event_status available on the FE eventID screen

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetEventByCaseIdTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/IntegrationBase.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/TestBase.java
src/main/java/uk/gov/hmcts/darts/cases/controller/CaseController.java
src/main/java/uk/gov/hmcts/darts/cases/mapper/EventMapper.java
src/main/java/uk/gov/hmcts/darts/cases/service/CaseService.java
src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java
src/main/java/uk/gov/hmcts/darts/event/mapper/EventMapper.java
src/main/java/uk/gov/hmcts/darts/util/pagination/PaginatedList.java
src/main/java/uk/gov/hmcts/darts/util/pagination/PaginationDto.java
src/main/resources/openapi/cases.yaml
src/main/resources/openapi/common.yaml
src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRetentionEventDateProcessorImplTest.java
src/test/java/uk/gov/hmcts/darts/cases/controller/CaseControllerTest.java
src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/common/datamanagement/api/DataManagementFacadeImplTest.java
src/test/java/uk/gov/hmcts/darts/util/pagination/PaginatedListTest.java
src/test/java/uk/gov/hmcts/darts/util/pagination/PaginationDtoTest.java
src/testCommon/java/uk/gov/hmcts/darts/test/common/PaginationTestSupport.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4946)
This Git diff introduces significant changes to the `CaseControllerGetEventByCaseIdTest` class, adding pagination support to the event retrieval process for court cases. It also modifies related classes and introduces new utility classes for pagination.
- **New Pagination Support**:
- A new nested class `CasesGetEventsPaginated` is added to `CaseControllerGetEventByCaseIdTest`.
- New test cases are implemented to verify pagination functionality for event retrieval based on various criteria.
- **Modified Method Signatures**:
- The method `casesCaseIdEventsGet` in `CaseController` now accepts pagination parameters (`sortBy`, `sortOrder`, `pageNumber`, `pageSize`).
- **New Pagination Classes**:
- Introduced `PaginatedList` and …

DMP-4946: Paginate the court log tab

---

src/main/java/uk/gov/hmcts/darts/admin/test/TestSupportController.java
src/main/java/uk/gov/hmcts/darts/arm/exception/UnableToReadArmFileException.java
src/main/java/uk/gov/hmcts/darts/audio/helper/TransformedMediaHelper.java
src/main/java/uk/gov/hmcts/darts/notification/entity/NotificationEntity.java
src/test/java/uk/gov/hmcts/darts/datamanagement/service/InboundToUnstructuredProcessorImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4633
Fixed major sonar compliants - Rename field 'x' to prevent any misunderstanding/clash with field 'X' and add at least one assertion to this test case. Also high sonar complaint Remove this use of 'createNativeQuery'; it is deprecated.
```
[ ] Yes
[x ] No
```

DMP-4633 Review and resolve sonar issues with the master branch

---

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetTranscriberTranscriptsIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsIntTest.java
src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java
src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/YourTranscriptsQueryImpl.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DMP-5016
The 90 day limit on transcriptions has been superseded by the requirement to close transcriptions older than 30 days. This PR clears up this redundant code. 
```
[ ] Yes
[ x] No
```

DMP-5016 Remove 90 day limit on transcription queries

---

src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetEventByCaseIdTest.java
src/main/java/uk/gov/hmcts/darts/cases/mapper/EventMapper.java
src/main/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java
src/main/resources/openapi/cases.yaml
src/test/java/uk/gov/hmcts/darts/cases/mapper/EventMapperTest.java
src/test/java/uk/gov/hmcts/darts/cases/service/impl/CaseServiceImplTest.java
src/test/resources/Tests/cases/CaseServiceTest/testGetEventsByCase/expectedResponse.json

>[Jira](https://tools.hmcts.net/jira/browse/DMP-3379)
This Git diff introduces several enhancements and modifications to the case management system, primarily focusing on the handling of event data related to court cases. Key changes include the addition of courtroom information in various components, updates to sorting parameters, and enhancements to JSON response formats for better clarity and usability.
- **New Import**: Added `TestUtils` to the `CaseControllerGetEventByCaseIdTest` for improved testing capabilities.
- **JSON Response Update**: Enhanced the expected JSON response structure in the integration test to include fields such as `courtroom` and updated the naming of existing fields for consistency (e.g., `timestamp` to `time`).
- **Sorting Parameter Changes**: Updated sorting …

DMP-3379: Get events for case on admin portal

---

.github/workflows/close-pr.yml
.github/workflows/on-pr.yml
.idea/codeStyles/Project.xml
Jenkinsfile_CNP
charts/darts-api/values.dev.template.yaml

>[Jira](https://tools.hmcts.net/jira/browse/DMP-5045)
The recent changes to the `Jenkinsfile_CNP` and `values.dev.template.yaml` files introduce enhancements related to the DARTS portal deployment. A new environment variable for the DARTS portal image suffix has been added, allowing for more flexible image tagging during deployment in the development and pull request environments.
- **Added Environment Variable**: 
- Introduced `env.DEV_DARTS_PORTAL_IMAGE_SUFFIX` in `Jenkinsfile_CNP`, defaulting to "latest".
- **Conditional Logic for PR Deployments**:
- Added logic to set `DEV_DARTS_PORTAL_IMAGE_SUFFIX` based on the label when enabling the DARTS portal in pull request environments.
- Updated the echo statement to reflect the chosen image suffix during deployment.
- **Updated Image …

DMP-5045: Can we point 2 services at a single Dev environment

---

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerGetYourTranscriptsLegacyIntTest.java
src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/YourTranscriptsQueryImpl.java

https://tools.hmcts.net/jira/browse/DMP-5053
When a transcription is only associated to a hearing through hearing_transcription_ae table it wasn't appearing on the your work tab for requestors or approvers. This change fixes this issue.  
```
[ ] Yes
[x ] No
```

DMP-5053 Fix your transcriptions query to find transcriptions only associated to hearing

---

src/main/java/uk/gov/hmcts/darts/cases/mapper/HearingEntityToCaseHearing.java
src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionDocumentRepository.java
src/test/java/uk/gov/hmcts/darts/cases/mapper/HearingEntityToCaseHearingTest.java

https://tools.hmcts.net/jira/browse/DMP-5094
- exclude legacy automated transcriptions where no documents are associated
- fixing `TranscriptionDocumentRepository.findByTranscriptionIdAndHiddenTrueIncludeDeleted` parameters name to be clearer
```
[ ] Yes
[ ] No
```

DMP-5094 Hearing transcription count fix for legacy automated transcriptions

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRpoServiceIntTest.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImpl.java

https://tools.hmcts.net/jira/browse/DMP-5100
Reset the input_upload_processed_ts to null when EOD status is set to replay in the ARM reconciliation
```
[ ] Yes
[ x] No
```

DMP-5100-ARMNeedsToResetInputUploadProcessedTs

---

src/integrationTest/java/uk/gov/hmcts/darts/common/repository/TranscriptionDocumentTest.java
src/main/java/uk/gov/hmcts/darts/common/repository/TranscriptionDocumentRepository.java

N/A
To ensure we can see transcription documents even if the associated transcription requested by is null
```
[ ] Yes
[ ] No
```

Fixing transcription documents search when tra.requested_by is null

---

src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/TranscriptionServiceImplTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-5101)
This diff introduces several modifications to the `TranscriptionServiceImpl` class and its corresponding test class, `TranscriptionServiceImplTest`. The primary change involves the removal of the `CaseService` dependency from both the implementation and test classes. As a result, references to case-related functionality have been eliminated, streamlining the code.
- **Removed CaseService Dependency**: 
- The `CaseService` field was removed from `TranscriptionServiceImpl`.
- Corresponding mock object and references in `TranscriptionServiceImplTest` were also deleted.
- **Code Cleanup**:
- Unused code related to `CaseService` was eliminated from method implementations, particularly in the `saveTranscription` method and various test …

DMP-5101: Remove link to case_transcription_ae table for modernised transcriptions

---

src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRpoReplayServiceIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/arm/service/ArmRpoServiceIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepositoryTest.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoReplayServiceImpl.java
src/main/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/ExternalObjectDirectoryRepository.java
src/test/java/uk/gov/hmcts/darts/arm/service/impl/ArmRpoReplayServiceImplTest.java
src/test/java/uk/gov/hmcts/darts/task/runner/impl/ArmRpoReplayAutomatedTaskTest.java

https://tools.hmcts.net/jira/browse/DMP-5100
Changed the location where the input_upload_processed_ts is reset to when the replay job is called. Moved the private methods below the tests. I also had to fix the issue where the ids are now longs not ints on the EOD records. 
```
[ ] Yes
[x ] No
```

DMP-5100 ARM Replay needs to reset input_upload_processed_ts

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerUpdateTransformedMediaLastAccessedTimestampIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/GivenBuilder.java
src/integrationTest/java/uk/gov/hmcts/darts/testutils/TestBase.java
src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/AuthorisationImpl.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-5082)
This Git diff introduces changes primarily focused on enhancing the integration test for the `AudioRequestsController`. Key modifications involve the removal of mock authorization checks, improvements to user authentication during tests, and adjustments to the way media requests are validated against user roles. The `GivenBuilder` utility has been updated to facilitate user role assignment more effectively.
- **Removed Mock Authorisation**: The previous mock authorization checks in the `AudioRequestsControllerUpdateTransformedMediaLastAccessedTimestampIntTest` class have been removed to streamline the test process.
- **Enhanced User Authentication**: A new method `authenticateValid()` has been introduced to handle user authentication …

DMP-5082: Transformed media with changed owner is not accessible to the new owner

---

src/main/java/uk/gov/hmcts/darts/transcriptions/component/impl/TranscriberTranscriptsQueryImpl.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-5092)
Fixed performance of some transcription queries as using or in the joins bypasses some indexes which significantly degraded performance of the API (95 percentile was well over 5 minutes for the call)
The diff shows modifications made to the `TranscriberTranscriptsQueryImpl.java` file, specifically changing the way `JOIN` operations are constructed in SQL queries. The changes involve replacing a complex conditional join with a more succinct use of the `COALESCE` function.
- **Code Changes**:
- Replaced complex join conditions with `COALESCE` in SQL queries to improve clarity and maintainability.
- The affected SQL joins are located in multiple methods: `getTranscriptRequests`, `getTranscriberTranscriptions`, and a count query.
- …

DMP-5092: Legacy Transcription performance fix

---

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAdminPostTranscriptionIntTest.java
src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java
src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapperTest.java
src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionServiceTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-5063)
This Git diff reflects changes made to the `AdminTranscriptionServiceImpl.java` and `AdminTranscriptionServiceTest.java` files in the transcription service of the HMCTS DARTS project. The modifications focus on the handling of transcription document hiding logic, particularly around the management of deletion markers and user accounts.
- **User Account Handling**: 
- Replaced direct calls to `userIdentity.getUserAccount()` with a stored variable `currentUser` for clarity and performance.
- **Object Admin Action Entity Modifications**:
- The method now checks if the `objectHiddenReason` is marked for deletion before setting the `markedForManualDeletion` flag.
- If marked for deletion, the fields for manual deletion are set using …

DMP-5063: Transcription marked for deletion ts genrated with is marked for deletion flag false

---

src/integrationTest/java/uk/gov/hmcts/darts/event/controller/EventsControllerPatchAdminEventByIdIntTest.java
src/main/java/uk/gov/hmcts/darts/common/exception/CommonApiError.java
src/main/java/uk/gov/hmcts/darts/event/exception/EventError.java
src/main/java/uk/gov/hmcts/darts/event/service/impl/EventServiceImpl.java
src/main/resources/openapi/event.yaml
src/test/java/uk/gov/hmcts/darts/event/service/impl/EventServiceImplTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-3411)
This is needed to add an additional layer of protection such that event_id 0 that is_current = false (which should not happen) does cause catastrophic data issues by linking all event_ids = 0 and setting all other ones to false 
The Git Diff reflects a series of changes made to the event management service in the codebase. Key changes include updating error handling for API requests, modifying test cases, and adding new error codes for specific scenarios.
- **Error Handling Update**: The error response for when `isCurrent` is set to `false` has been changed from HTTP status `422 Unprocessable Entity` to `400 Bad Request` in both the integration test and the event service implementation.
- **New Error Code**: Introduced a new error code …

DMP-3411: Implement endpoint to make event current version

---

src/integrationTest/java/uk/gov/hmcts/darts/authorisation/controller/AuthorisationControllerIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/authorisation/service/AuthorisationServiceTest.java
src/main/java/uk/gov/hmcts/darts/authorisation/model/UserState.java
src/main/java/uk/gov/hmcts/darts/authorisation/service/impl/AuthorisationServiceImpl.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-5061)
The changes in this Git Diff primarily involve the addition of an `email_address` field to the `UserState` model and its associated tests. This enhancement allows the system to return user email addresses in various user state responses, ensuring consistency in the data being handled.
- **Integration Tests Updated**:
- Added `email_address` field to the assertions in the tests located in `AuthorisationControllerIntTest.java`.
- The email address is now included in the expected JSON responses for various user states.
- **Service Tests Updated**:
- The `AuthorisationServiceTest.java` includes assertions for the `email_address` for multiple test cases, ensuring the email is correctly retrieved and asserted for different user roles.
- …

DMP-5061: Need to return user email address in /userstate endpoint

---

src/main/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionCaseAssociatedObjectsSingleCaseProcessorImpl.java
src/test/java/uk/gov/hmcts/darts/retention/service/impl/ApplyRetentionCaseAssociatedObjectsSingleCaseProcessorImplTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-5086)
This Git diff introduces enhancements to the `ApplyRetentionCaseAssociatedObjectsSingleCaseProcessorImpl` class by adding a new import and modifying the logic for handling media linked to court cases. It enhances the retrieval of cases associated with media by ensuring that only non-null linked cases are considered. Additionally, the test file for this implementation has been updated to accommodate these changes.
- **New Import Added**: 
- `MediaLinkedCaseEntity` is now imported to facilitate handling media linked to court cases.
- **Code Modifications**: 
- The method `applyRetentionToMedias` was updated to utilize a stream for retrieving court cases linked to media, filtering out any null cases.
- Code now uses `Objects::nonNull` to …

DMP-5086: ApplyRetentionCaseAssociatedObjects -> Fails if media_linked_case has a cas_id that is null

---

src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/StopAndCloseHandlerTest.java
src/main/java/uk/gov/hmcts/darts/event/service/handler/StopAndCloseHandler.java
src/main/java/uk/gov/hmcts/darts/retention/service/CloseCaseWithRetentionService.java
src/main/java/uk/gov/hmcts/darts/retention/service/impl/CloseCaseWithRetentionServiceImpl.java
src/test/java/uk/gov/hmcts/darts/retention/service/impl/CloseCaseWithRetentionServiceImplTest.java

https://tools.hmcts.net/jira/browse/DMP-4910
Always set the case closed date on a case, even if the event date is before a previously received one. This aligns with legacy behaviour.
This change also includes a refactor to remove the PMD warning about coupling between objects in this class. 
```
[ ] Yes
[x ] No
```

DMP-4910 Always set case closed date on case closed event

---

src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAdminPostTranscriptionIntTest.java
src/main/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapper.java
src/main/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionServiceImpl.java
src/test/java/uk/gov/hmcts/darts/transcriptions/mapper/TranscriptionResponseMapperTest.java
src/test/java/uk/gov/hmcts/darts/transcriptions/service/impl/AdminTranscriptionServiceTest.java

https://tools.hmcts.net/jira/browse/DMP-5063
- the "marked_for_manual_deletion", "marked_for_manual_del_by" and "marked_for_manual_del_ts" columns should not be set when the deletion is first requested
- these should be thought of as "approved for manual deletion" columns, which are set when the deletion is approved by the second admin, and this is already implemented
```
[ ] Yes
[ ] No
```

DMP-5063 Fixes for requesting transcription document deletion

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/MediaControllerPostAdminMediasSearchIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/repository/CaseRepositoryIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/repository/EventRepositoryIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/repository/HearingRepositoryIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/event/service/impl/AdminEventSearchTest.java
src/main/java/uk/gov/hmcts/darts/audio/helper/PostAdminMediasSearchHelper.java
src/main/java/uk/gov/hmcts/darts/cases/mapper/AdminCasesSearchResponseMapper.java
src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java
src/main/java/uk/gov/hmcts/darts/common/repository/EventRepository.java
src/main/java/uk/gov/hmcts/darts/common/repository/HearingRepository.java

https://tools.hmcts.net/jira/browse/DMP-5054
Amended the default sort order for admin portal search results, returned from the API, as follows
Cases
courthouse_name ASC, case_number ASC
Hearings
courthouse display_name ASC, courtroom_name ASC, hearing_date ASC, case_number ASC
Events
courthouse_name ASC, courtroom_name ASC, event_ts ASC
Audio
start_ts ASC, channel ASC
```
[ ] Yes
[ x] No
```

Dmp 5054 amend admin portal search default sort order

---

src/main/resources/db/reference/manual-data-fixes/003_reset_failed_arm_objects/reset_failed_arm_objects.sql
src/main/resources/db/reference/manual-data-fixes/README.md

https://tools.hmcts.net/jira/browse/DMP-5154
Due to the last CI/CD release, which restarted the pods, few of the ARM objects were moved to stale status which will require resetting those status back so that it can replayed.
```
[ ] Yes
[x] No
```

DMP-5154 : reset failed ARM objects

---

src/main/java/uk/gov/hmcts/darts/audio/service/OutboundAudioDeleterProcessorSingleElement.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorImpl.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/OutboundAudioDeleterProcessorSingleElementImpl.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-5140)
NOTE: No new tests have been added apart of this ticket as Lazy loading errors in this instance can not be detected apart of the integration tests. I have tried a few things but I can not seem to replicate the issue (but I am open to ideas :))
I have however, manually replicated the issue with darts-portal -> darts-api, in which the old code throw a lazy load error and following this fix it did not.
This Git diff outlines several modifications made to the `OutboundAudioDeleterProcessorSingleElement` interface and its implementation classes. The primary change involves updating the `markMediaRequestAsExpired` method to accept a media request ID instead of a `MediaRequestEntity` object, streamlining the deletion process for transformed …

DMP-5140: When running the OutboundAudioDeleterProcessorImpl the Job fails due to LazyLoad errors

---

src/integrationTest/java/uk/gov/hmcts/darts/task/runner/impl/CaseExpiryDeletionAutomatedTaskIntTest.java
src/main/java/uk/gov/hmcts/darts/common/repository/CaseRepository.java

https://tools.hmcts.net/jira/browse/DMP-5076
When anonymising case data, a query is run to find all 'Complete' retention records where the retention date exceeds the current date/time. This PR ensures only the latest 'Complete' record is chosen, preventing a case from being anonymised prematurely.
```
[ ] Yes
[ ] No
```

DMP-5076 Use retention date from latest retention record if multiple exist

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioControllerGetMetadataIntTest.java
src/main/java/uk/gov/hmcts/darts/audio/controller/AudioController.java
src/main/java/uk/gov/hmcts/darts/audio/service/AudioService.java
src/main/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImpl.java
src/main/java/uk/gov/hmcts/darts/common/repository/MediaRepository.java
src/test/java/uk/gov/hmcts/darts/audio/service/impl/AudioServiceImplTest.java

>[Jira](https://tools.hmcts.net/jira/browse/DMP-4998)
This Git diff introduces significant changes primarily in the `AudioController`, `AudioService`, and their respective tests. The main focus is on modifying how audio metadata is retrieved by changing the method of fetching media entities, leading to the selection of the lowest channel for each media group. Additionally, updates were made to the integration tests to reflect the revised logic.
- **Refactoring Method Signatures:**
- Changed `getMediaEntitiesByHearingAndChannel` to `getMediaEntitiesByHearingAndLowestChannel` in `AudioService` and `MediaRepository`.
- **Logic Update in AudioService Implementation:**
- The new implementation of `getMediaEntitiesByHearingAndLowestChannel` groups media entities by courtroom, start time, end …

DMP-4998: Deviation between legacy and modernised when only channel 4 audio is available

---

src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerAddAudioRequestDownloadIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/audio/controller/AudioRequestsControllerAddAudioRequestPlaybackIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/authentication/controller/impl/TokenValidatorTest.java
src/integrationTest/java/uk/gov/hmcts/darts/authorisation/controller/AuthorisationControllerIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetAnnotationsIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseByIdTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetCaseHearingsTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerGetEventByCaseIdTest.java
src/integrationTest/java/uk/gov/hmcts/darts/cases/controller/CaseControllerSearchPostTest.java
src/integrationTest/java/uk/gov/hmcts/darts/common/controller/CourthouseApiTest.java
src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsGetControllerTest.java
src/integrationTest/java/uk/gov/hmcts/darts/hearings/controller/HearingsGetEventsControllerTest.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerAttachTranscriptIntTest.java
src/integrationTest/java/uk/gov/hmcts/darts/transcriptions/controller/TranscriptionControllerDownloadTranscriptIntTest.java
src/main/java/uk/gov/hmcts/darts/authorisation/component/impl/UserIdentityImpl.java
src/main/java/uk/gov/hmcts/darts/authorisation/exception/AuthorisationError.java
src/main/java/uk/gov/hmcts/darts/common/config/security/SecurityConfig.java
src/main/java/uk/gov/hmcts/darts/common/exception/DartsApiTrait.java
src/main/java/uk/gov/hmcts/darts/common/repository/UserAccountRepository.java
src/main/resources/openapi/common.yaml

https://tools.hmcts.net/jira/browse/DMP-5162
- amending `USER_DETAILS_INVALID` error to return 401
- amending request filter to only set 403 error when the user is inactive
- otherwise 401 used as the user could not be found and should authenticate again
```
[ ] Yes
[ ] No
```

DMP-5162 Better differentiate between 403 and 401 errors
